// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AgentSessionsColumns holds the columns for the "agent_sessions" table.
	AgentSessionsColumns = []*schema.Column{
		{Name: "agent_id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString},
		{Name: "session_epoch", Type: field.TypeInt64},
		{Name: "controller_node", Type: field.TypeString},
		{Name: "remote_addr", Type: field.TypeString, Default: ""},
		{Name: "agent_version", Type: field.TypeString, Default: ""},
		{Name: "capabilities", Type: field.TypeJSON, Nullable: true},
		{Name: "connected_at", Type: field.TypeTime},
		{Name: "last_seen_at", Type: field.TypeTime},
	}
	// AgentSessionsTable holds the schema information for the "agent_sessions" table.
	AgentSessionsTable = &schema.Table{
		Name:       "agent_sessions",
		Columns:    AgentSessionsColumns,
		PrimaryKey: []*schema.Column{AgentSessionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "agentsession_org_id_agent_id",
				Unique:  true,
				Columns: []*schema.Column{AgentSessionsColumns[1], AgentSessionsColumns[0]},
			},
		},
	}
	// AgentStateColumns holds the columns for the "agent_state" table.
	AgentStateColumns = []*schema.Column{
		{Name: "agent_id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString},
		{Name: "boot_id", Type: field.TypeString, Default: ""},
		{Name: "clock_offset_ms", Type: field.TypeInt64, Default: 0},
		{Name: "applied_db_epoch", Type: field.TypeString, Default: ""},
		{Name: "applied_seq", Type: field.TypeInt64, Default: 0},
		{Name: "applied_hash", Type: field.TypeBytes, Nullable: true},
		{Name: "last_ack_at", Type: field.TypeTime, Nullable: true},
		{Name: "pushed_db_epoch", Type: field.TypeString, Default: ""},
		{Name: "pushed_seq", Type: field.TypeInt64, Default: 0},
		{Name: "pushed_hash", Type: field.TypeBytes, Nullable: true},
		{Name: "pushed_at", Type: field.TypeTime, Nullable: true},
		{Name: "rejected_db_epoch", Type: field.TypeString, Default: ""},
		{Name: "rejected_seq", Type: field.TypeInt64, Default: 0},
		{Name: "rejected_hash", Type: field.TypeBytes, Nullable: true},
		{Name: "last_rejection", Type: field.TypeJSON, Nullable: true},
	}
	// AgentStateTable holds the schema information for the "agent_state" table.
	AgentStateTable = &schema.Table{
		Name:       "agent_state",
		Columns:    AgentStateColumns,
		PrimaryKey: []*schema.Column{AgentStateColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "agentstate_org_id_agent_id",
				Unique:  true,
				Columns: []*schema.Column{AgentStateColumns[1], AgentStateColumns[0]},
			},
		},
	}
	// AuditLogColumns holds the columns for the "audit_log" table.
	AuditLogColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString, Nullable: true},
		{Name: "seq", Type: field.TypeInt64},
		{Name: "prev_hash", Type: field.TypeBytes},
		{Name: "hash", Type: field.TypeBytes},
		{Name: "ts", Type: field.TypeTime},
		{Name: "actor_type", Type: field.TypeEnum, Enums: []string{"user", "agent", "system", "anonymous"}},
		{Name: "actor_id", Type: field.TypeString, Default: ""},
		{Name: "credential_id", Type: field.TypeString, Default: ""},
		{Name: "auth_method", Type: field.TypeString, Default: ""},
		{Name: "ip", Type: field.TypeString, Default: ""},
		{Name: "user_agent", Type: field.TypeString, Default: ""},
		{Name: "request_id", Type: field.TypeString, Default: ""},
		{Name: "action", Type: field.TypeString},
		{Name: "target_type", Type: field.TypeString, Default: ""},
		{Name: "target_id", Type: field.TypeString, Default: ""},
		{Name: "result", Type: field.TypeEnum, Enums: []string{"success", "failure", "denied"}},
		{Name: "diff", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "reason", Type: field.TypeString, Default: ""},
	}
	// AuditLogTable holds the schema information for the "audit_log" table.
	AuditLogTable = &schema.Table{
		Name:       "audit_log",
		Columns:    AuditLogColumns,
		PrimaryKey: []*schema.Column{AuditLogColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditentry_org_id_seq",
				Unique:  true,
				Columns: []*schema.Column{AuditLogColumns[1], AuditLogColumns[2]},
			},
			{
				Name:    "auditentry_instance_seq",
				Unique:  true,
				Columns: []*schema.Column{AuditLogColumns[2]},
				Annotation: &entsql.IndexAnnotation{
					Where: "org_id IS NULL",
				},
			},
		},
	}
	// AuditHeadsColumns holds the columns for the "audit_heads" table.
	AuditHeadsColumns = []*schema.Column{
		{Name: "chain", Type: field.TypeString},
		{Name: "seq", Type: field.TypeInt64},
		{Name: "hash", Type: field.TypeBytes},
	}
	// AuditHeadsTable holds the schema information for the "audit_heads" table.
	AuditHeadsTable = &schema.Table{
		Name:       "audit_heads",
		Columns:    AuditHeadsColumns,
		PrimaryKey: []*schema.Column{AuditHeadsColumns[0]},
	}
	// CaKeysColumns holds the columns for the "ca_keys" table.
	CaKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"root", "intermediate", "config_signing", "audit_checkpoint"}},
		{Name: "algorithm", Type: field.TypeString},
		{Name: "public_key", Type: field.TypeBytes},
		{Name: "certificate", Type: field.TypeBytes},
		{Name: "key_enc", Type: field.TypeBytes, Nullable: true},
		{Name: "not_before", Type: field.TypeTime},
		{Name: "not_after", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"next", "active", "retired"}},
	}
	// CaKeysTable holds the schema information for the "ca_keys" table.
	CaKeysTable = &schema.Table{
		Name:       "ca_keys",
		Columns:    CaKeysColumns,
		PrimaryKey: []*schema.Column{CaKeysColumns[0]},
	}
	// CompiledSnapshotsColumns holds the columns for the "compiled_snapshots" table.
	CompiledSnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "org_id", Type: field.TypeString},
		{Name: "agent_id", Type: field.TypeString},
		{Name: "db_epoch", Type: field.TypeString},
		{Name: "seq", Type: field.TypeInt64},
		{Name: "hash", Type: field.TypeBytes},
		{Name: "size_bytes", Type: field.TypeInt},
		{Name: "payload", Type: field.TypeBytes},
		{Name: "signature", Type: field.TypeBytes},
		{Name: "key_id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// CompiledSnapshotsTable holds the schema information for the "compiled_snapshots" table.
	CompiledSnapshotsTable = &schema.Table{
		Name:       "compiled_snapshots",
		Columns:    CompiledSnapshotsColumns,
		PrimaryKey: []*schema.Column{CompiledSnapshotsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "compiledsnapshot_org_id_id",
				Unique:  true,
				Columns: []*schema.Column{CompiledSnapshotsColumns[1], CompiledSnapshotsColumns[0]},
			},
			{
				Name:    "compiledsnapshot_agent_id_id",
				Unique:  false,
				Columns: []*schema.Column{CompiledSnapshotsColumns[2], CompiledSnapshotsColumns[0]},
			},
		},
	}
	// ConfigRevisionsColumns holds the columns for the "config_revisions" table.
	ConfigRevisionsColumns = []*schema.Column{
		{Name: "seq", Type: field.TypeInt64, Increment: true},
		{Name: "db_epoch", Type: field.TypeString},
		{Name: "actor", Type: field.TypeString},
		{Name: "changed_resources", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ConfigRevisionsTable holds the schema information for the "config_revisions" table.
	ConfigRevisionsTable = &schema.Table{
		Name:       "config_revisions",
		Columns:    ConfigRevisionsColumns,
		PrimaryKey: []*schema.Column{ConfigRevisionsColumns[0]},
	}
	// ConfigSeqColumns holds the columns for the "config_seq" table.
	ConfigSeqColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "seq", Type: field.TypeInt64},
	}
	// ConfigSeqTable holds the schema information for the "config_seq" table.
	ConfigSeqTable = &schema.Table{
		Name:       "config_seq",
		Columns:    ConfigSeqColumns,
		PrimaryKey: []*schema.Column{ConfigSeqColumns[0]},
	}
	// ConnectorsColumns holds the columns for the "connectors" table.
	ConnectorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "spiffe_id", Type: field.TypeString},
		{Name: "pubkey_sha256", Type: field.TypeString},
		{Name: "ephemeral", Type: field.TypeBool, Default: false},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "transport", Type: field.TypeEnum, Nullable: true, Enums: []string{"auto", "quic", "h2"}},
		{Name: "desired_version", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "decommissioned_at", Type: field.TypeTime, Nullable: true},
	}
	// ConnectorsTable holds the schema information for the "connectors" table.
	ConnectorsTable = &schema.Table{
		Name:       "connectors",
		Columns:    ConnectorsColumns,
		PrimaryKey: []*schema.Column{ConnectorsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "connector_org_id_id",
				Unique:  true,
				Columns: []*schema.Column{ConnectorsColumns[1], ConnectorsColumns[0]},
			},
			{
				Name:    "connector_org_id_name",
				Unique:  true,
				Columns: []*schema.Column{ConnectorsColumns[1], ConnectorsColumns[2]},
			},
		},
	}
	// EnrollmentTokensColumns holds the columns for the "enrollment_tokens" table.
	EnrollmentTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString},
		{Name: "token_hash", Type: field.TypeBytes, Unique: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"connector", "gateway"}},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "ephemeral", Type: field.TypeBool, Default: false},
		{Name: "max_uses", Type: field.TypeInt, Nullable: true},
		{Name: "use_count", Type: field.TypeInt, Default: 0},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_used_ip", Type: field.TypeString, Nullable: true},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "gateway_group_id", Type: field.TypeString, Nullable: true},
		{Name: "gateway_id", Type: field.TypeString, Nullable: true},
		{Name: "connector_id", Type: field.TypeString, Nullable: true},
	}
	// EnrollmentTokensTable holds the schema information for the "enrollment_tokens" table.
	EnrollmentTokensTable = &schema.Table{
		Name:       "enrollment_tokens",
		Columns:    EnrollmentTokensColumns,
		PrimaryKey: []*schema.Column{EnrollmentTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "enrollment_tokens_gateway_groups_group",
				Columns:    []*schema.Column{EnrollmentTokensColumns[14]},
				RefColumns: []*schema.Column{GatewayGroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "enrollment_tokens_gateways_gateway",
				Columns:    []*schema.Column{EnrollmentTokensColumns[15]},
				RefColumns: []*schema.Column{GatewaysColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "enrollment_tokens_connectors_connector",
				Columns:    []*schema.Column{EnrollmentTokensColumns[16]},
				RefColumns: []*schema.Column{ConnectorsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "enrollmenttoken_org_id_id",
				Unique:  true,
				Columns: []*schema.Column{EnrollmentTokensColumns[1], EnrollmentTokensColumns[0]},
			},
		},
	}
	// GatewaysColumns holds the columns for the "gateways" table.
	GatewaysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "slot", Type: field.TypeInt},
		{Name: "tunnel_endpoints", Type: field.TypeJSON},
		{Name: "spiffe_id", Type: field.TypeString, Nullable: true},
		{Name: "pubkey_sha256", Type: field.TypeString, Nullable: true},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "desired_version", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "decommissioned_at", Type: field.TypeTime, Nullable: true},
		{Name: "gateway_group_id", Type: field.TypeString},
	}
	// GatewaysTable holds the schema information for the "gateways" table.
	GatewaysTable = &schema.Table{
		Name:       "gateways",
		Columns:    GatewaysColumns,
		PrimaryKey: []*schema.Column{GatewaysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "gateways_gateway_groups_group",
				Columns:    []*schema.Column{GatewaysColumns[11]},
				RefColumns: []*schema.Column{GatewayGroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "gateway_org_id_id",
				Unique:  true,
				Columns: []*schema.Column{GatewaysColumns[1], GatewaysColumns[0]},
			},
			{
				Name:    "gateway_org_id_name",
				Unique:  true,
				Columns: []*schema.Column{GatewaysColumns[1], GatewaysColumns[2]},
			},
			{
				Name:    "gateway_gateway_group_id_slot",
				Unique:  true,
				Columns: []*schema.Column{GatewaysColumns[11], GatewaysColumns[3]},
				Annotation: &entsql.IndexAnnotation{
					Where: "decommissioned_at IS NULL",
				},
			},
		},
	}
	// GatewayGroupsColumns holds the columns for the "gateway_groups" table.
	GatewayGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "region", Type: field.TypeString, Nullable: true},
		{Name: "public_hostnames", Type: field.TypeJSON, Nullable: true},
		{Name: "trusted_proxy_cidrs", Type: field.TypeJSON, Nullable: true},
	}
	// GatewayGroupsTable holds the schema information for the "gateway_groups" table.
	GatewayGroupsTable = &schema.Table{
		Name:       "gateway_groups",
		Columns:    GatewayGroupsColumns,
		PrimaryKey: []*schema.Column{GatewayGroupsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "gatewaygroup_org_id_id",
				Unique:  true,
				Columns: []*schema.Column{GatewayGroupsColumns[1], GatewayGroupsColumns[0]},
			},
			{
				Name:    "gatewaygroup_org_id_name",
				Unique:  true,
				Columns: []*schema.Column{GatewayGroupsColumns[1], GatewayGroupsColumns[2]},
			},
		},
	}
	// InstanceColumns holds the columns for the "instance" table.
	InstanceColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "trust_domain", Type: field.TypeString},
		{Name: "db_epoch", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// InstanceTable holds the schema information for the "instance" table.
	InstanceTable = &schema.Table{
		Name:       "instance",
		Columns:    InstanceColumns,
		PrimaryKey: []*schema.Column{InstanceColumns[0]},
	}
	// InstanceSettingsColumns holds the columns for the "instance_settings" table.
	InstanceSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "value", Type: field.TypeBytes},
		{Name: "version", Type: field.TypeInt64},
		{Name: "updated_by", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// InstanceSettingsTable holds the schema information for the "instance_settings" table.
	InstanceSettingsTable = &schema.Table{
		Name:       "instance_settings",
		Columns:    InstanceSettingsColumns,
		PrimaryKey: []*schema.Column{InstanceSettingsColumns[0]},
	}
	// IssuedCertificatesColumns holds the columns for the "issued_certificates" table.
	IssuedCertificatesColumns = []*schema.Column{
		{Name: "serial", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString, Nullable: true},
		{Name: "subject_type", Type: field.TypeEnum, Enums: []string{"connector", "gateway", "controller"}},
		{Name: "subject_id", Type: field.TypeString},
		{Name: "spiffe_id", Type: field.TypeString},
		{Name: "pubkey_sha256", Type: field.TypeString},
		{Name: "not_before", Type: field.TypeTime},
		{Name: "not_after", Type: field.TypeTime},
		{Name: "first_seen_at", Type: field.TypeTime, Nullable: true},
		{Name: "superseded_at", Type: field.TypeTime, Nullable: true},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "revocation_reason", Type: field.TypeString, Default: ""},
		{Name: "certificate", Type: field.TypeBytes, Nullable: true},
		{Name: "enrollment_token_id", Type: field.TypeString, Nullable: true},
	}
	// IssuedCertificatesTable holds the schema information for the "issued_certificates" table.
	IssuedCertificatesTable = &schema.Table{
		Name:       "issued_certificates",
		Columns:    IssuedCertificatesColumns,
		PrimaryKey: []*schema.Column{IssuedCertificatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "issued_certificates_enrollment_tokens_enrollment_token",
				Columns:    []*schema.Column{IssuedCertificatesColumns[13]},
				RefColumns: []*schema.Column{EnrollmentTokensColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "issuedcertificate_subject_id",
				Unique:  false,
				Columns: []*schema.Column{IssuedCertificatesColumns[3]},
			},
			{
				Name:    "issuedcertificate_enrollment_token_id",
				Unique:  false,
				Columns: []*schema.Column{IssuedCertificatesColumns[13]},
			},
		},
	}
	// LeasesColumns holds the columns for the "leases" table.
	LeasesColumns = []*schema.Column{
		{Name: "name", Type: field.TypeString},
		{Name: "holder", Type: field.TypeString},
		{Name: "fencing_token", Type: field.TypeInt64},
		{Name: "expires_at", Type: field.TypeInt64},
	}
	// LeasesTable holds the schema information for the "leases" table.
	LeasesTable = &schema.Table{
		Name:       "leases",
		Columns:    LeasesColumns,
		PrimaryKey: []*schema.Column{LeasesColumns[0]},
	}
	// OrgsColumns holds the columns for the "orgs" table.
	OrgsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// OrgsTable holds the schema information for the "orgs" table.
	OrgsTable = &schema.Table{
		Name:       "orgs",
		Columns:    OrgsColumns,
		PrimaryKey: []*schema.Column{OrgsColumns[0]},
	}
	// OrgSettingsColumns holds the columns for the "org_settings" table.
	OrgSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString},
		{Name: "value", Type: field.TypeBytes},
		{Name: "version", Type: field.TypeInt64},
		{Name: "updated_by", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OrgSettingsTable holds the schema information for the "org_settings" table.
	OrgSettingsTable = &schema.Table{
		Name:       "org_settings",
		Columns:    OrgSettingsColumns,
		PrimaryKey: []*schema.Column{OrgSettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "orgsetting_org_id_id",
				Unique:  true,
				Columns: []*schema.Column{OrgSettingsColumns[1], OrgSettingsColumns[0]},
			},
			{
				Name:    "orgsetting_org_id",
				Unique:  true,
				Columns: []*schema.Column{OrgSettingsColumns[1]},
			},
		},
	}
	// PortAllocationsColumns holds the columns for the "port_allocations" table.
	PortAllocationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString},
		{Name: "protocol", Type: field.TypeEnum, Enums: []string{"tcp", "udp"}},
		{Name: "port", Type: field.TypeInt},
		{Name: "route_id", Type: field.TypeString, Nullable: true},
		{Name: "gateway_group_id", Type: field.TypeString},
	}
	// PortAllocationsTable holds the schema information for the "port_allocations" table.
	PortAllocationsTable = &schema.Table{
		Name:       "port_allocations",
		Columns:    PortAllocationsColumns,
		PrimaryKey: []*schema.Column{PortAllocationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "port_allocations_gateway_groups_group",
				Columns:    []*schema.Column{PortAllocationsColumns[5]},
				RefColumns: []*schema.Column{GatewayGroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "portallocation_org_id_id",
				Unique:  true,
				Columns: []*schema.Column{PortAllocationsColumns[1], PortAllocationsColumns[0]},
			},
			{
				Name:    "portallocation_gateway_group_id_protocol_port",
				Unique:  true,
				Columns: []*schema.Column{PortAllocationsColumns[5], PortAllocationsColumns[2], PortAllocationsColumns[3]},
			},
		},
	}
	// PortPoolsColumns holds the columns for the "port_pools" table.
	PortPoolsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString},
		{Name: "protocol", Type: field.TypeEnum, Enums: []string{"tcp", "udp"}},
		{Name: "port_from", Type: field.TypeInt},
		{Name: "port_to", Type: field.TypeInt},
		{Name: "gateway_group_id", Type: field.TypeString},
	}
	// PortPoolsTable holds the schema information for the "port_pools" table.
	PortPoolsTable = &schema.Table{
		Name:       "port_pools",
		Columns:    PortPoolsColumns,
		PrimaryKey: []*schema.Column{PortPoolsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "port_pools_gateway_groups_group",
				Columns:    []*schema.Column{PortPoolsColumns[5]},
				RefColumns: []*schema.Column{GatewayGroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "portpool_org_id_id",
				Unique:  true,
				Columns: []*schema.Column{PortPoolsColumns[1], PortPoolsColumns[0]},
			},
		},
	}
	// PortQuotasColumns holds the columns for the "port_quotas" table.
	PortQuotasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString},
		{Name: "protocol", Type: field.TypeEnum, Enums: []string{"tcp", "udp"}},
		{Name: "max_ports", Type: field.TypeInt},
		{Name: "gateway_group_id", Type: field.TypeString},
	}
	// PortQuotasTable holds the schema information for the "port_quotas" table.
	PortQuotasTable = &schema.Table{
		Name:       "port_quotas",
		Columns:    PortQuotasColumns,
		PrimaryKey: []*schema.Column{PortQuotasColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "port_quotas_gateway_groups_group",
				Columns:    []*schema.Column{PortQuotasColumns[4]},
				RefColumns: []*schema.Column{GatewayGroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "portquota_org_id_id",
				Unique:  true,
				Columns: []*schema.Column{PortQuotasColumns[1], PortQuotasColumns[0]},
			},
			{
				Name:    "portquota_org_id_gateway_group_id_protocol",
				Unique:  true,
				Columns: []*schema.Column{PortQuotasColumns[1], PortQuotasColumns[4], PortQuotasColumns[2]},
			},
		},
	}
	// RevokedIdentitiesColumns holds the columns for the "revoked_identities" table.
	RevokedIdentitiesColumns = []*schema.Column{
		{Name: "spiffe_id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString, Nullable: true},
		{Name: "subject_type", Type: field.TypeEnum, Enums: []string{"connector", "gateway", "controller"}},
		{Name: "subject_id", Type: field.TypeString},
		{Name: "revoked_at", Type: field.TypeTime},
		{Name: "reason", Type: field.TypeString, Default: ""},
		{Name: "not_after", Type: field.TypeTime},
	}
	// RevokedIdentitiesTable holds the schema information for the "revoked_identities" table.
	RevokedIdentitiesTable = &schema.Table{
		Name:       "revoked_identities",
		Columns:    RevokedIdentitiesColumns,
		PrimaryKey: []*schema.Column{RevokedIdentitiesColumns[0]},
	}
	// RoutesColumns holds the columns for the "routes" table.
	RoutesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"http", "tcp", "udp", "tls_passthrough"}},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "transport", Type: field.TypeEnum, Nullable: true, Enums: []string{"auto", "quic", "h2"}},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "version", Type: field.TypeInt64, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "updated_by", Type: field.TypeString, Default: ""},
		{Name: "gateway_group_id", Type: field.TypeString},
	}
	// RoutesTable holds the schema information for the "routes" table.
	RoutesTable = &schema.Table{
		Name:       "routes",
		Columns:    RoutesColumns,
		PrimaryKey: []*schema.Column{RoutesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "routes_gateway_groups_group",
				Columns:    []*schema.Column{RoutesColumns[12]},
				RefColumns: []*schema.Column{GatewayGroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "route_org_id_id",
				Unique:  true,
				Columns: []*schema.Column{RoutesColumns[1], RoutesColumns[0]},
			},
			{
				Name:    "route_org_id_name",
				Unique:  true,
				Columns: []*schema.Column{RoutesColumns[1], RoutesColumns[2]},
			},
		},
	}
	// RouteTCPColumns holds the columns for the "route_tcp" table.
	RouteTCPColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "org_id", Type: field.TypeString},
		{Name: "listener_mode", Type: field.TypeEnum, Enums: []string{"plain", "http_connect"}, Default: "plain"},
		{Name: "idle_timeout_seconds", Type: field.TypeInt, Default: 3600},
		{Name: "route_id", Type: field.TypeString},
		{Name: "port_allocation_id", Type: field.TypeString},
	}
	// RouteTCPTable holds the schema information for the "route_tcp" table.
	RouteTCPTable = &schema.Table{
		Name:       "route_tcp",
		Columns:    RouteTCPColumns,
		PrimaryKey: []*schema.Column{RouteTCPColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "route_tcp_routes_route",
				Columns:    []*schema.Column{RouteTCPColumns[4]},
				RefColumns: []*schema.Column{RoutesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "route_tcp_port_allocations_port",
				Columns:    []*schema.Column{RouteTCPColumns[5]},
				RefColumns: []*schema.Column{PortAllocationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "routetcp_org_id_id",
				Unique:  true,
				Columns: []*schema.Column{RouteTCPColumns[1], RouteTCPColumns[0]},
			},
		},
	}
	// RouteTargetsColumns holds the columns for the "route_targets" table.
	RouteTargetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"address", "unix"}},
		{Name: "host", Type: field.TypeString, Default: ""},
		{Name: "port", Type: field.TypeInt, Default: 0},
		{Name: "unix_path", Type: field.TypeString, Default: ""},
		{Name: "upstream_protocol", Type: field.TypeEnum, Enums: []string{"tcp", "http", "https", "h2c"}, Default: "tcp"},
		{Name: "tls_server_name", Type: field.TypeString, Default: ""},
		{Name: "tls_spki_sha256", Type: field.TypeString, Default: ""},
		{Name: "proxy_protocol", Type: field.TypeEnum, Enums: []string{"none", "v1", "v2"}, Default: "none"},
		{Name: "weight", Type: field.TypeInt, Default: 1},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "route_id", Type: field.TypeString},
		{Name: "connector_id", Type: field.TypeString},
	}
	// RouteTargetsTable holds the schema information for the "route_targets" table.
	RouteTargetsTable = &schema.Table{
		Name:       "route_targets",
		Columns:    RouteTargetsColumns,
		PrimaryKey: []*schema.Column{RouteTargetsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "route_targets_routes_route",
				Columns:    []*schema.Column{RouteTargetsColumns[13]},
				RefColumns: []*schema.Column{RoutesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "route_targets_connectors_connector",
				Columns:    []*schema.Column{RouteTargetsColumns[14]},
				RefColumns: []*schema.Column{ConnectorsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "routetarget_org_id_id",
				Unique:  true,
				Columns: []*schema.Column{RouteTargetsColumns[1], RouteTargetsColumns[0]},
			},
			{
				Name:    "routetarget_route_id",
				Unique:  false,
				Columns: []*schema.Column{RouteTargetsColumns[13]},
			},
			{
				Name:    "routetarget_connector_id",
				Unique:  false,
				Columns: []*schema.Column{RouteTargetsColumns[14]},
			},
		},
	}
	// SecretsMetaColumns holds the columns for the "secrets_meta" table.
	SecretsMetaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "table_name", Type: field.TypeString},
		{Name: "row_id", Type: field.TypeString},
		{Name: "column_name", Type: field.TypeString},
		{Name: "kek_version", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// SecretsMetaTable holds the schema information for the "secrets_meta" table.
	SecretsMetaTable = &schema.Table{
		Name:       "secrets_meta",
		Columns:    SecretsMetaColumns,
		PrimaryKey: []*schema.Column{SecretsMetaColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "secretmeta_table_name_row_id_column_name",
				Unique:  true,
				Columns: []*schema.Column{SecretsMetaColumns[1], SecretsMetaColumns[2], SecretsMetaColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AgentSessionsTable,
		AgentStateTable,
		AuditLogTable,
		AuditHeadsTable,
		CaKeysTable,
		CompiledSnapshotsTable,
		ConfigRevisionsTable,
		ConfigSeqTable,
		ConnectorsTable,
		EnrollmentTokensTable,
		GatewaysTable,
		GatewayGroupsTable,
		InstanceTable,
		InstanceSettingsTable,
		IssuedCertificatesTable,
		LeasesTable,
		OrgsTable,
		OrgSettingsTable,
		PortAllocationsTable,
		PortPoolsTable,
		PortQuotasTable,
		RevokedIdentitiesTable,
		RoutesTable,
		RouteTCPTable,
		RouteTargetsTable,
		SecretsMetaTable,
	}
)

func init() {
	AgentSessionsTable.Annotation = &entsql.Annotation{
		Table: "agent_sessions",
	}
	AgentStateTable.Annotation = &entsql.Annotation{
		Table: "agent_state",
	}
	AuditLogTable.Annotation = &entsql.Annotation{
		Table: "audit_log",
	}
	AuditHeadsTable.Annotation = &entsql.Annotation{
		Table: "audit_heads",
	}
	CaKeysTable.Annotation = &entsql.Annotation{
		Table: "ca_keys",
	}
	CompiledSnapshotsTable.Annotation = &entsql.Annotation{
		Table: "compiled_snapshots",
	}
	ConfigSeqTable.Annotation = &entsql.Annotation{
		Table: "config_seq",
	}
	EnrollmentTokensTable.ForeignKeys[0].RefTable = GatewayGroupsTable
	EnrollmentTokensTable.ForeignKeys[1].RefTable = GatewaysTable
	EnrollmentTokensTable.ForeignKeys[2].RefTable = ConnectorsTable
	GatewaysTable.ForeignKeys[0].RefTable = GatewayGroupsTable
	InstanceTable.Annotation = &entsql.Annotation{
		Table: "instance",
	}
	InstanceSettingsTable.Annotation = &entsql.Annotation{
		Table: "instance_settings",
	}
	IssuedCertificatesTable.ForeignKeys[0].RefTable = EnrollmentTokensTable
	IssuedCertificatesTable.Annotation = &entsql.Annotation{
		Table: "issued_certificates",
	}
	LeasesTable.Annotation = &entsql.Annotation{
		Table: "leases",
	}
	OrgSettingsTable.Annotation = &entsql.Annotation{
		Table: "org_settings",
	}
	PortAllocationsTable.ForeignKeys[0].RefTable = GatewayGroupsTable
	PortAllocationsTable.Annotation = &entsql.Annotation{
		Table: "port_allocations",
	}
	PortPoolsTable.ForeignKeys[0].RefTable = GatewayGroupsTable
	PortPoolsTable.Annotation = &entsql.Annotation{
		Table: "port_pools",
	}
	PortQuotasTable.ForeignKeys[0].RefTable = GatewayGroupsTable
	PortQuotasTable.Annotation = &entsql.Annotation{
		Table: "port_quotas",
	}
	RevokedIdentitiesTable.Annotation = &entsql.Annotation{
		Table: "revoked_identities",
	}
	RoutesTable.ForeignKeys[0].RefTable = GatewayGroupsTable
	RoutesTable.Annotation = &entsql.Annotation{
		Table: "routes",
	}
	RouteTCPTable.ForeignKeys[0].RefTable = RoutesTable
	RouteTCPTable.ForeignKeys[1].RefTable = PortAllocationsTable
	RouteTCPTable.Annotation = &entsql.Annotation{
		Table: "route_tcp",
	}
	RouteTargetsTable.ForeignKeys[0].RefTable = RoutesTable
	RouteTargetsTable.ForeignKeys[1].RefTable = ConnectorsTable
	RouteTargetsTable.Annotation = &entsql.Annotation{
		Table: "route_targets",
	}
	SecretsMetaTable.Annotation = &entsql.Annotation{
		Table: "secrets_meta",
	}
}
