// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GatewayGroupsColumns holds the columns for the "gateway_groups" table.
	GatewayGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
	}
	// GatewayGroupsTable holds the schema information for the "gateway_groups" table.
	GatewayGroupsTable = &schema.Table{
		Name:       "gateway_groups",
		Columns:    GatewayGroupsColumns,
		PrimaryKey: []*schema.Column{GatewayGroupsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "gatewaygroup_org_id_id",
				Unique:  true,
				Columns: []*schema.Column{GatewayGroupsColumns[1], GatewayGroupsColumns[0]},
			},
			{
				Name:    "gatewaygroup_org_id_name",
				Unique:  true,
				Columns: []*schema.Column{GatewayGroupsColumns[1], GatewayGroupsColumns[2]},
			},
		},
	}
	// OrgsColumns holds the columns for the "orgs" table.
	OrgsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// OrgsTable holds the schema information for the "orgs" table.
	OrgsTable = &schema.Table{
		Name:       "orgs",
		Columns:    OrgsColumns,
		PrimaryKey: []*schema.Column{OrgsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GatewayGroupsTable,
		OrgsTable,
	}
)

func init() {
}
