// Code generated by ent, DO NOT EDIT.

package routehttp

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the routehttp type in the database.
	Label = "route_http"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrgID holds the string denoting the org_id field in the database.
	FieldOrgID = "org_id"
	// FieldRouteID holds the string denoting the route_id field in the database.
	FieldRouteID = "route_id"
	// FieldPathPrefix holds the string denoting the path_prefix field in the database.
	FieldPathPrefix = "path_prefix"
	// FieldHeaderMatches holds the string denoting the header_matches field in the database.
	FieldHeaderMatches = "header_matches"
	// FieldTLSMode holds the string denoting the tls_mode field in the database.
	FieldTLSMode = "tls_mode"
	// FieldCertificateID holds the string denoting the certificate_id field in the database.
	FieldCertificateID = "certificate_id"
	// FieldPort80 holds the string denoting the port80 field in the database.
	FieldPort80 = "port80"
	// FieldHostHeader holds the string denoting the host_header field in the database.
	FieldHostHeader = "host_header"
	// FieldRequestHeadersSet holds the string denoting the request_headers_set field in the database.
	FieldRequestHeadersSet = "request_headers_set"
	// FieldResponseHeadersSet holds the string denoting the response_headers_set field in the database.
	FieldResponseHeadersSet = "response_headers_set"
	// FieldWebsocket holds the string denoting the websocket field in the database.
	FieldWebsocket = "websocket"
	// FieldMaxBodyBytes holds the string denoting the max_body_bytes field in the database.
	FieldMaxBodyBytes = "max_body_bytes"
	// FieldDNSProxied holds the string denoting the dns_proxied field in the database.
	FieldDNSProxied = "dns_proxied"
	// EdgeRoute holds the string denoting the route edge name in mutations.
	EdgeRoute = "route"
	// EdgeCertificate holds the string denoting the certificate edge name in mutations.
	EdgeCertificate = "certificate"
	// Table holds the table name of the routehttp in the database.
	Table = "route_http"
	// RouteTable is the table that holds the route relation/edge.
	RouteTable = "route_http"
	// RouteInverseTable is the table name for the Route entity.
	// It exists in this package in order to avoid circular dependency with the "route" package.
	RouteInverseTable = "routes"
	// RouteColumn is the table column denoting the route relation/edge.
	RouteColumn = "route_id"
	// CertificateTable is the table that holds the certificate relation/edge.
	CertificateTable = "route_http"
	// CertificateInverseTable is the table name for the Certificate entity.
	// It exists in this package in order to avoid circular dependency with the "certificate" package.
	CertificateInverseTable = "certificates"
	// CertificateColumn is the table column denoting the certificate relation/edge.
	CertificateColumn = "certificate_id"
)

// Columns holds all SQL columns for routehttp fields.
var Columns = []string{
	FieldID,
	FieldOrgID,
	FieldRouteID,
	FieldPathPrefix,
	FieldHeaderMatches,
	FieldTLSMode,
	FieldCertificateID,
	FieldPort80,
	FieldHostHeader,
	FieldRequestHeadersSet,
	FieldResponseHeadersSet,
	FieldWebsocket,
	FieldMaxBodyBytes,
	FieldDNSProxied,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/felix-homelab/rpmgr/internal/store/ent/runtime"
var (
	Hooks        [2]ent.Hook
	Interceptors [1]ent.Interceptor
	Policy       ent.Policy
	// OrgIDValidator is a validator for the "org_id" field. It is called by the builders before save.
	OrgIDValidator func(string) error
	// RouteIDValidator is a validator for the "route_id" field. It is called by the builders before save.
	RouteIDValidator func(string) error
	// DefaultPathPrefix holds the default value on creation for the "path_prefix" field.
	DefaultPathPrefix string
	// DefaultHostHeader holds the default value on creation for the "host_header" field.
	DefaultHostHeader string
	// HostHeaderValidator is a validator for the "host_header" field. It is called by the builders before save.
	HostHeaderValidator func(string) error
	// DefaultWebsocket holds the default value on creation for the "websocket" field.
	DefaultWebsocket bool
	// DefaultMaxBodyBytes holds the default value on creation for the "max_body_bytes" field.
	DefaultMaxBodyBytes int64
	// MaxBodyBytesValidator is a validator for the "max_body_bytes" field. It is called by the builders before save.
	MaxBodyBytesValidator func(int64) error
	// DefaultDNSProxied holds the default value on creation for the "dns_proxied" field.
	DefaultDNSProxied bool
)

// TLSMode defines the type for the "tls_mode" enum field.
type TLSMode string

// TLSModeAcme is the default value of the TLSMode enum.
const DefaultTLSMode = TLSModeAcme

// TLSMode values.
const (
	TLSModeAcme        TLSMode = "acme"
	TLSModeCertificate TLSMode = "certificate"
)

func (tm TLSMode) String() string {
	return string(tm)
}

// TLSModeValidator is a validator for the "tls_mode" field enum values. It is called by the builders before save.
func TLSModeValidator(tm TLSMode) error {
	switch tm {
	case TLSModeAcme, TLSModeCertificate:
		return nil
	default:
		return fmt.Errorf("routehttp: invalid enum value for tls_mode field: %q", tm)
	}
}

// Port80 defines the type for the "port80" enum field.
type Port80 string

// Port80Redirect is the default value of the Port80 enum.
const DefaultPort80 = Port80Redirect

// Port80 values.
const (
	Port80Redirect Port80 = "redirect"
	Port80Serve    Port80 = "serve"
	Port80Off      Port80 = "off"
)

func (po Port80) String() string {
	return string(po)
}

// Port80Validator is a validator for the "port80" field enum values. It is called by the builders before save.
func Port80Validator(po Port80) error {
	switch po {
	case Port80Redirect, Port80Serve, Port80Off:
		return nil
	default:
		return fmt.Errorf("routehttp: invalid enum value for port80 field: %q", po)
	}
}

// OrderOption defines the ordering options for the RouteHTTP queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrgID orders the results by the org_id field.
func ByOrgID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrgID, opts...).ToFunc()
}

// ByRouteID orders the results by the route_id field.
func ByRouteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRouteID, opts...).ToFunc()
}

// ByPathPrefix orders the results by the path_prefix field.
func ByPathPrefix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPathPrefix, opts...).ToFunc()
}

// ByTLSMode orders the results by the tls_mode field.
func ByTLSMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTLSMode, opts...).ToFunc()
}

// ByCertificateID orders the results by the certificate_id field.
func ByCertificateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCertificateID, opts...).ToFunc()
}

// ByPort80 orders the results by the port80 field.
func ByPort80(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPort80, opts...).ToFunc()
}

// ByHostHeader orders the results by the host_header field.
func ByHostHeader(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostHeader, opts...).ToFunc()
}

// ByWebsocket orders the results by the websocket field.
func ByWebsocket(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebsocket, opts...).ToFunc()
}

// ByMaxBodyBytes orders the results by the max_body_bytes field.
func ByMaxBodyBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxBodyBytes, opts...).ToFunc()
}

// ByDNSProxied orders the results by the dns_proxied field.
func ByDNSProxied(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDNSProxied, opts...).ToFunc()
}

// ByRouteField orders the results by route field.
func ByRouteField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRouteStep(), sql.OrderByField(field, opts...))
	}
}

// ByCertificateField orders the results by certificate field.
func ByCertificateField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCertificateStep(), sql.OrderByField(field, opts...))
	}
}
func newRouteStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RouteInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RouteTable, RouteColumn),
	)
}
func newCertificateStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CertificateInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, CertificateTable, CertificateColumn),
	)
}
