// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felix-homelab/rpmgr/internal/store/ent/acmestorage"
	"github.com/felix-homelab/rpmgr/internal/store/ent/predicate"
)

// ACMEStorageDelete is the builder for deleting a ACMEStorage entity.
type ACMEStorageDelete struct {
	config
	hooks    []Hook
	mutation *ACMEStorageMutation
}

// Where appends a list predicates to the ACMEStorageDelete builder.
func (_d *ACMEStorageDelete) Where(ps ...predicate.ACMEStorage) *ACMEStorageDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ACMEStorageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ACMEStorageDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ACMEStorageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(acmestorage.Table, sqlgraph.NewFieldSpec(acmestorage.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ACMEStorageDeleteOne is the builder for deleting a single ACMEStorage entity.
type ACMEStorageDeleteOne struct {
	_d *ACMEStorageDelete
}

// Where appends a list predicates to the ACMEStorageDelete builder.
func (_d *ACMEStorageDeleteOne) Where(ps ...predicate.ACMEStorage) *ACMEStorageDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ACMEStorageDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{acmestorage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ACMEStorageDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
