// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/felix-homelab/rpmgr/internal/store/ent/agentstate"
	"github.com/felix-homelab/rpmgr/internal/store/ent/predicate"
)

// AgentStateUpdate is the builder for updating AgentState entities.
type AgentStateUpdate struct {
	config
	hooks    []Hook
	mutation *AgentStateMutation
}

// Where appends a list predicates to the AgentStateUpdate builder.
func (_u *AgentStateUpdate) Where(ps ...predicate.AgentState) *AgentStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBootID sets the "boot_id" field.
func (_u *AgentStateUpdate) SetBootID(v string) *AgentStateUpdate {
	_u.mutation.SetBootID(v)
	return _u
}

// SetNillableBootID sets the "boot_id" field if the given value is not nil.
func (_u *AgentStateUpdate) SetNillableBootID(v *string) *AgentStateUpdate {
	if v != nil {
		_u.SetBootID(*v)
	}
	return _u
}

// SetClockOffsetMs sets the "clock_offset_ms" field.
func (_u *AgentStateUpdate) SetClockOffsetMs(v int64) *AgentStateUpdate {
	_u.mutation.ResetClockOffsetMs()
	_u.mutation.SetClockOffsetMs(v)
	return _u
}

// SetNillableClockOffsetMs sets the "clock_offset_ms" field if the given value is not nil.
func (_u *AgentStateUpdate) SetNillableClockOffsetMs(v *int64) *AgentStateUpdate {
	if v != nil {
		_u.SetClockOffsetMs(*v)
	}
	return _u
}

// AddClockOffsetMs adds value to the "clock_offset_ms" field.
func (_u *AgentStateUpdate) AddClockOffsetMs(v int64) *AgentStateUpdate {
	_u.mutation.AddClockOffsetMs(v)
	return _u
}

// SetAppliedDbEpoch sets the "applied_db_epoch" field.
func (_u *AgentStateUpdate) SetAppliedDbEpoch(v string) *AgentStateUpdate {
	_u.mutation.SetAppliedDbEpoch(v)
	return _u
}

// SetNillableAppliedDbEpoch sets the "applied_db_epoch" field if the given value is not nil.
func (_u *AgentStateUpdate) SetNillableAppliedDbEpoch(v *string) *AgentStateUpdate {
	if v != nil {
		_u.SetAppliedDbEpoch(*v)
	}
	return _u
}

// SetAppliedSeq sets the "applied_seq" field.
func (_u *AgentStateUpdate) SetAppliedSeq(v int64) *AgentStateUpdate {
	_u.mutation.ResetAppliedSeq()
	_u.mutation.SetAppliedSeq(v)
	return _u
}

// SetNillableAppliedSeq sets the "applied_seq" field if the given value is not nil.
func (_u *AgentStateUpdate) SetNillableAppliedSeq(v *int64) *AgentStateUpdate {
	if v != nil {
		_u.SetAppliedSeq(*v)
	}
	return _u
}

// AddAppliedSeq adds value to the "applied_seq" field.
func (_u *AgentStateUpdate) AddAppliedSeq(v int64) *AgentStateUpdate {
	_u.mutation.AddAppliedSeq(v)
	return _u
}

// SetAppliedHash sets the "applied_hash" field.
func (_u *AgentStateUpdate) SetAppliedHash(v []byte) *AgentStateUpdate {
	_u.mutation.SetAppliedHash(v)
	return _u
}

// ClearAppliedHash clears the value of the "applied_hash" field.
func (_u *AgentStateUpdate) ClearAppliedHash() *AgentStateUpdate {
	_u.mutation.ClearAppliedHash()
	return _u
}

// SetLastAckAt sets the "last_ack_at" field.
func (_u *AgentStateUpdate) SetLastAckAt(v time.Time) *AgentStateUpdate {
	_u.mutation.SetLastAckAt(v)
	return _u
}

// SetNillableLastAckAt sets the "last_ack_at" field if the given value is not nil.
func (_u *AgentStateUpdate) SetNillableLastAckAt(v *time.Time) *AgentStateUpdate {
	if v != nil {
		_u.SetLastAckAt(*v)
	}
	return _u
}

// ClearLastAckAt clears the value of the "last_ack_at" field.
func (_u *AgentStateUpdate) ClearLastAckAt() *AgentStateUpdate {
	_u.mutation.ClearLastAckAt()
	return _u
}

// SetPushedDbEpoch sets the "pushed_db_epoch" field.
func (_u *AgentStateUpdate) SetPushedDbEpoch(v string) *AgentStateUpdate {
	_u.mutation.SetPushedDbEpoch(v)
	return _u
}

// SetNillablePushedDbEpoch sets the "pushed_db_epoch" field if the given value is not nil.
func (_u *AgentStateUpdate) SetNillablePushedDbEpoch(v *string) *AgentStateUpdate {
	if v != nil {
		_u.SetPushedDbEpoch(*v)
	}
	return _u
}

// SetPushedSeq sets the "pushed_seq" field.
func (_u *AgentStateUpdate) SetPushedSeq(v int64) *AgentStateUpdate {
	_u.mutation.ResetPushedSeq()
	_u.mutation.SetPushedSeq(v)
	return _u
}

// SetNillablePushedSeq sets the "pushed_seq" field if the given value is not nil.
func (_u *AgentStateUpdate) SetNillablePushedSeq(v *int64) *AgentStateUpdate {
	if v != nil {
		_u.SetPushedSeq(*v)
	}
	return _u
}

// AddPushedSeq adds value to the "pushed_seq" field.
func (_u *AgentStateUpdate) AddPushedSeq(v int64) *AgentStateUpdate {
	_u.mutation.AddPushedSeq(v)
	return _u
}

// SetPushedHash sets the "pushed_hash" field.
func (_u *AgentStateUpdate) SetPushedHash(v []byte) *AgentStateUpdate {
	_u.mutation.SetPushedHash(v)
	return _u
}

// ClearPushedHash clears the value of the "pushed_hash" field.
func (_u *AgentStateUpdate) ClearPushedHash() *AgentStateUpdate {
	_u.mutation.ClearPushedHash()
	return _u
}

// SetPushedAt sets the "pushed_at" field.
func (_u *AgentStateUpdate) SetPushedAt(v time.Time) *AgentStateUpdate {
	_u.mutation.SetPushedAt(v)
	return _u
}

// SetNillablePushedAt sets the "pushed_at" field if the given value is not nil.
func (_u *AgentStateUpdate) SetNillablePushedAt(v *time.Time) *AgentStateUpdate {
	if v != nil {
		_u.SetPushedAt(*v)
	}
	return _u
}

// ClearPushedAt clears the value of the "pushed_at" field.
func (_u *AgentStateUpdate) ClearPushedAt() *AgentStateUpdate {
	_u.mutation.ClearPushedAt()
	return _u
}

// SetRejectedDbEpoch sets the "rejected_db_epoch" field.
func (_u *AgentStateUpdate) SetRejectedDbEpoch(v string) *AgentStateUpdate {
	_u.mutation.SetRejectedDbEpoch(v)
	return _u
}

// SetNillableRejectedDbEpoch sets the "rejected_db_epoch" field if the given value is not nil.
func (_u *AgentStateUpdate) SetNillableRejectedDbEpoch(v *string) *AgentStateUpdate {
	if v != nil {
		_u.SetRejectedDbEpoch(*v)
	}
	return _u
}

// SetRejectedSeq sets the "rejected_seq" field.
func (_u *AgentStateUpdate) SetRejectedSeq(v int64) *AgentStateUpdate {
	_u.mutation.ResetRejectedSeq()
	_u.mutation.SetRejectedSeq(v)
	return _u
}

// SetNillableRejectedSeq sets the "rejected_seq" field if the given value is not nil.
func (_u *AgentStateUpdate) SetNillableRejectedSeq(v *int64) *AgentStateUpdate {
	if v != nil {
		_u.SetRejectedSeq(*v)
	}
	return _u
}

// AddRejectedSeq adds value to the "rejected_seq" field.
func (_u *AgentStateUpdate) AddRejectedSeq(v int64) *AgentStateUpdate {
	_u.mutation.AddRejectedSeq(v)
	return _u
}

// SetRejectedHash sets the "rejected_hash" field.
func (_u *AgentStateUpdate) SetRejectedHash(v []byte) *AgentStateUpdate {
	_u.mutation.SetRejectedHash(v)
	return _u
}

// ClearRejectedHash clears the value of the "rejected_hash" field.
func (_u *AgentStateUpdate) ClearRejectedHash() *AgentStateUpdate {
	_u.mutation.ClearRejectedHash()
	return _u
}

// SetLastRejection sets the "last_rejection" field.
func (_u *AgentStateUpdate) SetLastRejection(v []map[string]string) *AgentStateUpdate {
	_u.mutation.SetLastRejection(v)
	return _u
}

// AppendLastRejection appends value to the "last_rejection" field.
func (_u *AgentStateUpdate) AppendLastRejection(v []map[string]string) *AgentStateUpdate {
	_u.mutation.AppendLastRejection(v)
	return _u
}

// ClearLastRejection clears the value of the "last_rejection" field.
func (_u *AgentStateUpdate) ClearLastRejection() *AgentStateUpdate {
	_u.mutation.ClearLastRejection()
	return _u
}

// Mutation returns the AgentStateMutation object of the builder.
func (_u *AgentStateUpdate) Mutation() *AgentStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentStateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentStateUpdate) check() error {
	if v, ok := _u.mutation.AppliedSeq(); ok {
		if err := agentstate.AppliedSeqValidator(v); err != nil {
			return &ValidationError{Name: "applied_seq", err: fmt.Errorf(`ent: validator failed for field "AgentState.applied_seq": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PushedSeq(); ok {
		if err := agentstate.PushedSeqValidator(v); err != nil {
			return &ValidationError{Name: "pushed_seq", err: fmt.Errorf(`ent: validator failed for field "AgentState.pushed_seq": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RejectedSeq(); ok {
		if err := agentstate.RejectedSeqValidator(v); err != nil {
			return &ValidationError{Name: "rejected_seq", err: fmt.Errorf(`ent: validator failed for field "AgentState.rejected_seq": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentstate.Table, agentstate.Columns, sqlgraph.NewFieldSpec(agentstate.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BootID(); ok {
		_spec.SetField(agentstate.FieldBootID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClockOffsetMs(); ok {
		_spec.SetField(agentstate.FieldClockOffsetMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClockOffsetMs(); ok {
		_spec.AddField(agentstate.FieldClockOffsetMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AppliedDbEpoch(); ok {
		_spec.SetField(agentstate.FieldAppliedDbEpoch, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppliedSeq(); ok {
		_spec.SetField(agentstate.FieldAppliedSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAppliedSeq(); ok {
		_spec.AddField(agentstate.FieldAppliedSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AppliedHash(); ok {
		_spec.SetField(agentstate.FieldAppliedHash, field.TypeBytes, value)
	}
	if _u.mutation.AppliedHashCleared() {
		_spec.ClearField(agentstate.FieldAppliedHash, field.TypeBytes)
	}
	if value, ok := _u.mutation.LastAckAt(); ok {
		_spec.SetField(agentstate.FieldLastAckAt, field.TypeTime, value)
	}
	if _u.mutation.LastAckAtCleared() {
		_spec.ClearField(agentstate.FieldLastAckAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PushedDbEpoch(); ok {
		_spec.SetField(agentstate.FieldPushedDbEpoch, field.TypeString, value)
	}
	if value, ok := _u.mutation.PushedSeq(); ok {
		_spec.SetField(agentstate.FieldPushedSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPushedSeq(); ok {
		_spec.AddField(agentstate.FieldPushedSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PushedHash(); ok {
		_spec.SetField(agentstate.FieldPushedHash, field.TypeBytes, value)
	}
	if _u.mutation.PushedHashCleared() {
		_spec.ClearField(agentstate.FieldPushedHash, field.TypeBytes)
	}
	if value, ok := _u.mutation.PushedAt(); ok {
		_spec.SetField(agentstate.FieldPushedAt, field.TypeTime, value)
	}
	if _u.mutation.PushedAtCleared() {
		_spec.ClearField(agentstate.FieldPushedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RejectedDbEpoch(); ok {
		_spec.SetField(agentstate.FieldRejectedDbEpoch, field.TypeString, value)
	}
	if value, ok := _u.mutation.RejectedSeq(); ok {
		_spec.SetField(agentstate.FieldRejectedSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRejectedSeq(); ok {
		_spec.AddField(agentstate.FieldRejectedSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RejectedHash(); ok {
		_spec.SetField(agentstate.FieldRejectedHash, field.TypeBytes, value)
	}
	if _u.mutation.RejectedHashCleared() {
		_spec.ClearField(agentstate.FieldRejectedHash, field.TypeBytes)
	}
	if value, ok := _u.mutation.LastRejection(); ok {
		_spec.SetField(agentstate.FieldLastRejection, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLastRejection(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentstate.FieldLastRejection, value)
		})
	}
	if _u.mutation.LastRejectionCleared() {
		_spec.ClearField(agentstate.FieldLastRejection, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentStateUpdateOne is the builder for updating a single AgentState entity.
type AgentStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentStateMutation
}

// SetBootID sets the "boot_id" field.
func (_u *AgentStateUpdateOne) SetBootID(v string) *AgentStateUpdateOne {
	_u.mutation.SetBootID(v)
	return _u
}

// SetNillableBootID sets the "boot_id" field if the given value is not nil.
func (_u *AgentStateUpdateOne) SetNillableBootID(v *string) *AgentStateUpdateOne {
	if v != nil {
		_u.SetBootID(*v)
	}
	return _u
}

// SetClockOffsetMs sets the "clock_offset_ms" field.
func (_u *AgentStateUpdateOne) SetClockOffsetMs(v int64) *AgentStateUpdateOne {
	_u.mutation.ResetClockOffsetMs()
	_u.mutation.SetClockOffsetMs(v)
	return _u
}

// SetNillableClockOffsetMs sets the "clock_offset_ms" field if the given value is not nil.
func (_u *AgentStateUpdateOne) SetNillableClockOffsetMs(v *int64) *AgentStateUpdateOne {
	if v != nil {
		_u.SetClockOffsetMs(*v)
	}
	return _u
}

// AddClockOffsetMs adds value to the "clock_offset_ms" field.
func (_u *AgentStateUpdateOne) AddClockOffsetMs(v int64) *AgentStateUpdateOne {
	_u.mutation.AddClockOffsetMs(v)
	return _u
}

// SetAppliedDbEpoch sets the "applied_db_epoch" field.
func (_u *AgentStateUpdateOne) SetAppliedDbEpoch(v string) *AgentStateUpdateOne {
	_u.mutation.SetAppliedDbEpoch(v)
	return _u
}

// SetNillableAppliedDbEpoch sets the "applied_db_epoch" field if the given value is not nil.
func (_u *AgentStateUpdateOne) SetNillableAppliedDbEpoch(v *string) *AgentStateUpdateOne {
	if v != nil {
		_u.SetAppliedDbEpoch(*v)
	}
	return _u
}

// SetAppliedSeq sets the "applied_seq" field.
func (_u *AgentStateUpdateOne) SetAppliedSeq(v int64) *AgentStateUpdateOne {
	_u.mutation.ResetAppliedSeq()
	_u.mutation.SetAppliedSeq(v)
	return _u
}

// SetNillableAppliedSeq sets the "applied_seq" field if the given value is not nil.
func (_u *AgentStateUpdateOne) SetNillableAppliedSeq(v *int64) *AgentStateUpdateOne {
	if v != nil {
		_u.SetAppliedSeq(*v)
	}
	return _u
}

// AddAppliedSeq adds value to the "applied_seq" field.
func (_u *AgentStateUpdateOne) AddAppliedSeq(v int64) *AgentStateUpdateOne {
	_u.mutation.AddAppliedSeq(v)
	return _u
}

// SetAppliedHash sets the "applied_hash" field.
func (_u *AgentStateUpdateOne) SetAppliedHash(v []byte) *AgentStateUpdateOne {
	_u.mutation.SetAppliedHash(v)
	return _u
}

// ClearAppliedHash clears the value of the "applied_hash" field.
func (_u *AgentStateUpdateOne) ClearAppliedHash() *AgentStateUpdateOne {
	_u.mutation.ClearAppliedHash()
	return _u
}

// SetLastAckAt sets the "last_ack_at" field.
func (_u *AgentStateUpdateOne) SetLastAckAt(v time.Time) *AgentStateUpdateOne {
	_u.mutation.SetLastAckAt(v)
	return _u
}

// SetNillableLastAckAt sets the "last_ack_at" field if the given value is not nil.
func (_u *AgentStateUpdateOne) SetNillableLastAckAt(v *time.Time) *AgentStateUpdateOne {
	if v != nil {
		_u.SetLastAckAt(*v)
	}
	return _u
}

// ClearLastAckAt clears the value of the "last_ack_at" field.
func (_u *AgentStateUpdateOne) ClearLastAckAt() *AgentStateUpdateOne {
	_u.mutation.ClearLastAckAt()
	return _u
}

// SetPushedDbEpoch sets the "pushed_db_epoch" field.
func (_u *AgentStateUpdateOne) SetPushedDbEpoch(v string) *AgentStateUpdateOne {
	_u.mutation.SetPushedDbEpoch(v)
	return _u
}

// SetNillablePushedDbEpoch sets the "pushed_db_epoch" field if the given value is not nil.
func (_u *AgentStateUpdateOne) SetNillablePushedDbEpoch(v *string) *AgentStateUpdateOne {
	if v != nil {
		_u.SetPushedDbEpoch(*v)
	}
	return _u
}

// SetPushedSeq sets the "pushed_seq" field.
func (_u *AgentStateUpdateOne) SetPushedSeq(v int64) *AgentStateUpdateOne {
	_u.mutation.ResetPushedSeq()
	_u.mutation.SetPushedSeq(v)
	return _u
}

// SetNillablePushedSeq sets the "pushed_seq" field if the given value is not nil.
func (_u *AgentStateUpdateOne) SetNillablePushedSeq(v *int64) *AgentStateUpdateOne {
	if v != nil {
		_u.SetPushedSeq(*v)
	}
	return _u
}

// AddPushedSeq adds value to the "pushed_seq" field.
func (_u *AgentStateUpdateOne) AddPushedSeq(v int64) *AgentStateUpdateOne {
	_u.mutation.AddPushedSeq(v)
	return _u
}

// SetPushedHash sets the "pushed_hash" field.
func (_u *AgentStateUpdateOne) SetPushedHash(v []byte) *AgentStateUpdateOne {
	_u.mutation.SetPushedHash(v)
	return _u
}

// ClearPushedHash clears the value of the "pushed_hash" field.
func (_u *AgentStateUpdateOne) ClearPushedHash() *AgentStateUpdateOne {
	_u.mutation.ClearPushedHash()
	return _u
}

// SetPushedAt sets the "pushed_at" field.
func (_u *AgentStateUpdateOne) SetPushedAt(v time.Time) *AgentStateUpdateOne {
	_u.mutation.SetPushedAt(v)
	return _u
}

// SetNillablePushedAt sets the "pushed_at" field if the given value is not nil.
func (_u *AgentStateUpdateOne) SetNillablePushedAt(v *time.Time) *AgentStateUpdateOne {
	if v != nil {
		_u.SetPushedAt(*v)
	}
	return _u
}

// ClearPushedAt clears the value of the "pushed_at" field.
func (_u *AgentStateUpdateOne) ClearPushedAt() *AgentStateUpdateOne {
	_u.mutation.ClearPushedAt()
	return _u
}

// SetRejectedDbEpoch sets the "rejected_db_epoch" field.
func (_u *AgentStateUpdateOne) SetRejectedDbEpoch(v string) *AgentStateUpdateOne {
	_u.mutation.SetRejectedDbEpoch(v)
	return _u
}

// SetNillableRejectedDbEpoch sets the "rejected_db_epoch" field if the given value is not nil.
func (_u *AgentStateUpdateOne) SetNillableRejectedDbEpoch(v *string) *AgentStateUpdateOne {
	if v != nil {
		_u.SetRejectedDbEpoch(*v)
	}
	return _u
}

// SetRejectedSeq sets the "rejected_seq" field.
func (_u *AgentStateUpdateOne) SetRejectedSeq(v int64) *AgentStateUpdateOne {
	_u.mutation.ResetRejectedSeq()
	_u.mutation.SetRejectedSeq(v)
	return _u
}

// SetNillableRejectedSeq sets the "rejected_seq" field if the given value is not nil.
func (_u *AgentStateUpdateOne) SetNillableRejectedSeq(v *int64) *AgentStateUpdateOne {
	if v != nil {
		_u.SetRejectedSeq(*v)
	}
	return _u
}

// AddRejectedSeq adds value to the "rejected_seq" field.
func (_u *AgentStateUpdateOne) AddRejectedSeq(v int64) *AgentStateUpdateOne {
	_u.mutation.AddRejectedSeq(v)
	return _u
}

// SetRejectedHash sets the "rejected_hash" field.
func (_u *AgentStateUpdateOne) SetRejectedHash(v []byte) *AgentStateUpdateOne {
	_u.mutation.SetRejectedHash(v)
	return _u
}

// ClearRejectedHash clears the value of the "rejected_hash" field.
func (_u *AgentStateUpdateOne) ClearRejectedHash() *AgentStateUpdateOne {
	_u.mutation.ClearRejectedHash()
	return _u
}

// SetLastRejection sets the "last_rejection" field.
func (_u *AgentStateUpdateOne) SetLastRejection(v []map[string]string) *AgentStateUpdateOne {
	_u.mutation.SetLastRejection(v)
	return _u
}

// AppendLastRejection appends value to the "last_rejection" field.
func (_u *AgentStateUpdateOne) AppendLastRejection(v []map[string]string) *AgentStateUpdateOne {
	_u.mutation.AppendLastRejection(v)
	return _u
}

// ClearLastRejection clears the value of the "last_rejection" field.
func (_u *AgentStateUpdateOne) ClearLastRejection() *AgentStateUpdateOne {
	_u.mutation.ClearLastRejection()
	return _u
}

// Mutation returns the AgentStateMutation object of the builder.
func (_u *AgentStateUpdateOne) Mutation() *AgentStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the AgentStateUpdate builder.
func (_u *AgentStateUpdateOne) Where(ps ...predicate.AgentState) *AgentStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentStateUpdateOne) Select(field string, fields ...string) *AgentStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentState entity.
func (_u *AgentStateUpdateOne) Save(ctx context.Context) (*AgentState, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentStateUpdateOne) SaveX(ctx context.Context) *AgentState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentStateUpdateOne) check() error {
	if v, ok := _u.mutation.AppliedSeq(); ok {
		if err := agentstate.AppliedSeqValidator(v); err != nil {
			return &ValidationError{Name: "applied_seq", err: fmt.Errorf(`ent: validator failed for field "AgentState.applied_seq": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PushedSeq(); ok {
		if err := agentstate.PushedSeqValidator(v); err != nil {
			return &ValidationError{Name: "pushed_seq", err: fmt.Errorf(`ent: validator failed for field "AgentState.pushed_seq": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RejectedSeq(); ok {
		if err := agentstate.RejectedSeqValidator(v); err != nil {
			return &ValidationError{Name: "rejected_seq", err: fmt.Errorf(`ent: validator failed for field "AgentState.rejected_seq": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentStateUpdateOne) sqlSave(ctx context.Context) (_node *AgentState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentstate.Table, agentstate.Columns, sqlgraph.NewFieldSpec(agentstate.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentstate.FieldID)
		for _, f := range fields {
			if !agentstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BootID(); ok {
		_spec.SetField(agentstate.FieldBootID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClockOffsetMs(); ok {
		_spec.SetField(agentstate.FieldClockOffsetMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClockOffsetMs(); ok {
		_spec.AddField(agentstate.FieldClockOffsetMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AppliedDbEpoch(); ok {
		_spec.SetField(agentstate.FieldAppliedDbEpoch, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppliedSeq(); ok {
		_spec.SetField(agentstate.FieldAppliedSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAppliedSeq(); ok {
		_spec.AddField(agentstate.FieldAppliedSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AppliedHash(); ok {
		_spec.SetField(agentstate.FieldAppliedHash, field.TypeBytes, value)
	}
	if _u.mutation.AppliedHashCleared() {
		_spec.ClearField(agentstate.FieldAppliedHash, field.TypeBytes)
	}
	if value, ok := _u.mutation.LastAckAt(); ok {
		_spec.SetField(agentstate.FieldLastAckAt, field.TypeTime, value)
	}
	if _u.mutation.LastAckAtCleared() {
		_spec.ClearField(agentstate.FieldLastAckAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PushedDbEpoch(); ok {
		_spec.SetField(agentstate.FieldPushedDbEpoch, field.TypeString, value)
	}
	if value, ok := _u.mutation.PushedSeq(); ok {
		_spec.SetField(agentstate.FieldPushedSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPushedSeq(); ok {
		_spec.AddField(agentstate.FieldPushedSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PushedHash(); ok {
		_spec.SetField(agentstate.FieldPushedHash, field.TypeBytes, value)
	}
	if _u.mutation.PushedHashCleared() {
		_spec.ClearField(agentstate.FieldPushedHash, field.TypeBytes)
	}
	if value, ok := _u.mutation.PushedAt(); ok {
		_spec.SetField(agentstate.FieldPushedAt, field.TypeTime, value)
	}
	if _u.mutation.PushedAtCleared() {
		_spec.ClearField(agentstate.FieldPushedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RejectedDbEpoch(); ok {
		_spec.SetField(agentstate.FieldRejectedDbEpoch, field.TypeString, value)
	}
	if value, ok := _u.mutation.RejectedSeq(); ok {
		_spec.SetField(agentstate.FieldRejectedSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRejectedSeq(); ok {
		_spec.AddField(agentstate.FieldRejectedSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RejectedHash(); ok {
		_spec.SetField(agentstate.FieldRejectedHash, field.TypeBytes, value)
	}
	if _u.mutation.RejectedHashCleared() {
		_spec.ClearField(agentstate.FieldRejectedHash, field.TypeBytes)
	}
	if value, ok := _u.mutation.LastRejection(); ok {
		_spec.SetField(agentstate.FieldLastRejection, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLastRejection(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentstate.FieldLastRejection, value)
		})
	}
	if _u.mutation.LastRejectionCleared() {
		_spec.ClearField(agentstate.FieldLastRejection, field.TypeJSON)
	}
	_node = &AgentState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
