// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/felix-homelab/rpmgr/internal/store/ent/audithead"
)

// AuditHead is the model entity for the AuditHead schema.
type AuditHead struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Seq holds the value of the "seq" field.
	Seq int64 `json:"seq,omitempty"`
	// Hash holds the value of the "hash" field.
	Hash         []byte `json:"hash,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuditHead) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case audithead.FieldHash:
			values[i] = new([]byte)
		case audithead.FieldSeq:
			values[i] = new(sql.NullInt64)
		case audithead.FieldID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuditHead fields.
func (_m *AuditHead) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case audithead.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case audithead.FieldSeq:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field seq", values[i])
			} else if value.Valid {
				_m.Seq = value.Int64
			}
		case audithead.FieldHash:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value != nil {
				_m.Hash = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuditHead.
// This includes values selected through modifiers, order, etc.
func (_m *AuditHead) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AuditHead.
// Note that you need to call AuditHead.Unwrap() before calling this method if this AuditHead
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuditHead) Update() *AuditHeadUpdateOne {
	return NewAuditHeadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuditHead entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuditHead) Unwrap() *AuditHead {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuditHead is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuditHead) String() string {
	var builder strings.Builder
	builder.WriteString("AuditHead(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("seq=")
	builder.WriteString(fmt.Sprintf("%v", _m.Seq))
	builder.WriteString(", ")
	builder.WriteString("hash=")
	builder.WriteString(fmt.Sprintf("%v", _m.Hash))
	builder.WriteByte(')')
	return builder.String()
}

// AuditHeads is a parsable slice of AuditHead.
type AuditHeads []*AuditHead
