// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/felix-homelab/rpmgr/internal/store/ent/cakey"
)

// CAKey is the model entity for the CAKey schema.
type CAKey struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind cakey.Kind `json:"kind,omitempty"`
	// Algorithm holds the value of the "algorithm" field.
	Algorithm string `json:"algorithm,omitempty"`
	// PublicKey holds the value of the "public_key" field.
	PublicKey []byte `json:"public_key,omitempty"`
	// Certificate holds the value of the "certificate" field.
	Certificate []byte `json:"certificate,omitempty"`
	// KeyEnc holds the value of the "key_enc" field.
	KeyEnc *[]byte `json:"key_enc,omitempty"`
	// NotBefore holds the value of the "not_before" field.
	NotBefore time.Time `json:"not_before,omitempty"`
	// NotAfter holds the value of the "not_after" field.
	NotAfter time.Time `json:"not_after,omitempty"`
	// Status holds the value of the "status" field.
	Status       cakey.Status `json:"status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CAKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cakey.FieldPublicKey, cakey.FieldCertificate, cakey.FieldKeyEnc:
			values[i] = new([]byte)
		case cakey.FieldID, cakey.FieldKind, cakey.FieldAlgorithm, cakey.FieldStatus:
			values[i] = new(sql.NullString)
		case cakey.FieldNotBefore, cakey.FieldNotAfter:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CAKey fields.
func (_m *CAKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cakey.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case cakey.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = cakey.Kind(value.String)
			}
		case cakey.FieldAlgorithm:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field algorithm", values[i])
			} else if value.Valid {
				_m.Algorithm = value.String
			}
		case cakey.FieldPublicKey:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field public_key", values[i])
			} else if value != nil {
				_m.PublicKey = *value
			}
		case cakey.FieldCertificate:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field certificate", values[i])
			} else if value != nil {
				_m.Certificate = *value
			}
		case cakey.FieldKeyEnc:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field key_enc", values[i])
			} else if value != nil {
				_m.KeyEnc = value
			}
		case cakey.FieldNotBefore:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field not_before", values[i])
			} else if value.Valid {
				_m.NotBefore = value.Time
			}
		case cakey.FieldNotAfter:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field not_after", values[i])
			} else if value.Valid {
				_m.NotAfter = value.Time
			}
		case cakey.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = cakey.Status(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CAKey.
// This includes values selected through modifiers, order, etc.
func (_m *CAKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CAKey.
// Note that you need to call CAKey.Unwrap() before calling this method if this CAKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CAKey) Update() *CAKeyUpdateOne {
	return NewCAKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CAKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CAKey) Unwrap() *CAKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CAKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CAKey) String() string {
	var builder strings.Builder
	builder.WriteString("CAKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("algorithm=")
	builder.WriteString(_m.Algorithm)
	builder.WriteString(", ")
	builder.WriteString("public_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicKey))
	builder.WriteString(", ")
	builder.WriteString("certificate=")
	builder.WriteString(fmt.Sprintf("%v", _m.Certificate))
	builder.WriteString(", ")
	if v := _m.KeyEnc; v != nil {
		builder.WriteString("key_enc=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("not_before=")
	builder.WriteString(_m.NotBefore.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("not_after=")
	builder.WriteString(_m.NotAfter.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// CAKeys is a parsable slice of CAKey.
type CAKeys []*CAKey
