// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felix-homelab/rpmgr/internal/store/ent/cakey"
	"github.com/felix-homelab/rpmgr/internal/store/ent/predicate"
)

// CAKeyUpdate is the builder for updating CAKey entities.
type CAKeyUpdate struct {
	config
	hooks    []Hook
	mutation *CAKeyMutation
}

// Where appends a list predicates to the CAKeyUpdate builder.
func (_u *CAKeyUpdate) Where(ps ...predicate.CAKey) *CAKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKeyEnc sets the "key_enc" field.
func (_u *CAKeyUpdate) SetKeyEnc(v []byte) *CAKeyUpdate {
	_u.mutation.SetKeyEnc(v)
	return _u
}

// ClearKeyEnc clears the value of the "key_enc" field.
func (_u *CAKeyUpdate) ClearKeyEnc() *CAKeyUpdate {
	_u.mutation.ClearKeyEnc()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CAKeyUpdate) SetStatus(v cakey.Status) *CAKeyUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CAKeyUpdate) SetNillableStatus(v *cakey.Status) *CAKeyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the CAKeyMutation object of the builder.
func (_u *CAKeyUpdate) Mutation() *CAKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CAKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CAKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CAKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CAKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CAKeyUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := cakey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CAKey.status": %w`, err)}
		}
	}
	return nil
}

func (_u *CAKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cakey.Table, cakey.Columns, sqlgraph.NewFieldSpec(cakey.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.KeyEnc(); ok {
		_spec.SetField(cakey.FieldKeyEnc, field.TypeBytes, value)
	}
	if _u.mutation.KeyEncCleared() {
		_spec.ClearField(cakey.FieldKeyEnc, field.TypeBytes)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(cakey.FieldStatus, field.TypeEnum, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cakey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CAKeyUpdateOne is the builder for updating a single CAKey entity.
type CAKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CAKeyMutation
}

// SetKeyEnc sets the "key_enc" field.
func (_u *CAKeyUpdateOne) SetKeyEnc(v []byte) *CAKeyUpdateOne {
	_u.mutation.SetKeyEnc(v)
	return _u
}

// ClearKeyEnc clears the value of the "key_enc" field.
func (_u *CAKeyUpdateOne) ClearKeyEnc() *CAKeyUpdateOne {
	_u.mutation.ClearKeyEnc()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CAKeyUpdateOne) SetStatus(v cakey.Status) *CAKeyUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CAKeyUpdateOne) SetNillableStatus(v *cakey.Status) *CAKeyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the CAKeyMutation object of the builder.
func (_u *CAKeyUpdateOne) Mutation() *CAKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the CAKeyUpdate builder.
func (_u *CAKeyUpdateOne) Where(ps ...predicate.CAKey) *CAKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CAKeyUpdateOne) Select(field string, fields ...string) *CAKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CAKey entity.
func (_u *CAKeyUpdateOne) Save(ctx context.Context) (*CAKey, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CAKeyUpdateOne) SaveX(ctx context.Context) *CAKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CAKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CAKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CAKeyUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := cakey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CAKey.status": %w`, err)}
		}
	}
	return nil
}

func (_u *CAKeyUpdateOne) sqlSave(ctx context.Context) (_node *CAKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cakey.Table, cakey.Columns, sqlgraph.NewFieldSpec(cakey.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CAKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cakey.FieldID)
		for _, f := range fields {
			if !cakey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cakey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.KeyEnc(); ok {
		_spec.SetField(cakey.FieldKeyEnc, field.TypeBytes, value)
	}
	if _u.mutation.KeyEncCleared() {
		_spec.ClearField(cakey.FieldKeyEnc, field.TypeBytes)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(cakey.FieldStatus, field.TypeEnum, value)
	}
	_node = &CAKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cakey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
