// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felix-homelab/rpmgr/internal/store/ent/certificate"
)

// CertificateCreate is the builder for creating a Certificate entity.
type CertificateCreate struct {
	config
	mutation *CertificateMutation
	hooks    []Hook
}

// SetOrgID sets the "org_id" field.
func (_c *CertificateCreate) SetOrgID(v string) *CertificateCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *CertificateCreate) SetSource(v certificate.Source) *CertificateCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetSans sets the "sans" field.
func (_c *CertificateCreate) SetSans(v []string) *CertificateCreate {
	_c.mutation.SetSans(v)
	return _c
}

// SetNotBefore sets the "not_before" field.
func (_c *CertificateCreate) SetNotBefore(v time.Time) *CertificateCreate {
	_c.mutation.SetNotBefore(v)
	return _c
}

// SetNotAfter sets the "not_after" field.
func (_c *CertificateCreate) SetNotAfter(v time.Time) *CertificateCreate {
	_c.mutation.SetNotAfter(v)
	return _c
}

// SetChain sets the "chain" field.
func (_c *CertificateCreate) SetChain(v []byte) *CertificateCreate {
	_c.mutation.SetChain(v)
	return _c
}

// SetKeyEnc sets the "key_enc" field.
func (_c *CertificateCreate) SetKeyEnc(v []byte) *CertificateCreate {
	_c.mutation.SetKeyEnc(v)
	return _c
}

// SetContentSha256 sets the "content_sha256" field.
func (_c *CertificateCreate) SetContentSha256(v []byte) *CertificateCreate {
	_c.mutation.SetContentSha256(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *CertificateCreate) SetStatus(v certificate.Status) *CertificateCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableStatus(v *certificate.Status) *CertificateCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *CertificateCreate) SetLastError(v string) *CertificateCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableLastError(v *string) *CertificateCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetIssuer sets the "issuer" field.
func (_c *CertificateCreate) SetIssuer(v string) *CertificateCreate {
	_c.mutation.SetIssuer(v)
	return _c
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableIssuer(v *string) *CertificateCreate {
	if v != nil {
		_c.SetIssuer(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CertificateCreate) SetCreatedAt(v time.Time) *CertificateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableCreatedAt(v *time.Time) *CertificateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *CertificateCreate) SetVersion(v int64) *CertificateCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableVersion(v *int64) *CertificateCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CertificateCreate) SetID(v string) *CertificateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableID(v *string) *CertificateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the CertificateMutation object of the builder.
func (_c *CertificateCreate) Mutation() *CertificateMutation {
	return _c.mutation
}

// Save creates the Certificate in the database.
func (_c *CertificateCreate) Save(ctx context.Context) (*Certificate, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CertificateCreate) SaveX(ctx context.Context) *Certificate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CertificateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CertificateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CertificateCreate) defaults() error {
	if _, ok := _c.mutation.Status(); !ok {
		v := certificate.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if certificate.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized certificate.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := certificate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := certificate.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if certificate.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized certificate.DefaultID (forgotten import ent/runtime?)")
		}
		v := certificate.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *CertificateCreate) check() error {
	if _, ok := _c.mutation.OrgID(); !ok {
		return &ValidationError{Name: "org_id", err: errors.New(`ent: missing required field "Certificate.org_id"`)}
	}
	if v, ok := _c.mutation.OrgID(); ok {
		if err := certificate.OrgIDValidator(v); err != nil {
			return &ValidationError{Name: "org_id", err: fmt.Errorf(`ent: validator failed for field "Certificate.org_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Certificate.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := certificate.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Certificate.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sans(); !ok {
		return &ValidationError{Name: "sans", err: errors.New(`ent: missing required field "Certificate.sans"`)}
	}
	if _, ok := _c.mutation.NotBefore(); !ok {
		return &ValidationError{Name: "not_before", err: errors.New(`ent: missing required field "Certificate.not_before"`)}
	}
	if _, ok := _c.mutation.NotAfter(); !ok {
		return &ValidationError{Name: "not_after", err: errors.New(`ent: missing required field "Certificate.not_after"`)}
	}
	if _, ok := _c.mutation.Chain(); !ok {
		return &ValidationError{Name: "chain", err: errors.New(`ent: missing required field "Certificate.chain"`)}
	}
	if v, ok := _c.mutation.Chain(); ok {
		if err := certificate.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "Certificate.chain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyEnc(); !ok {
		return &ValidationError{Name: "key_enc", err: errors.New(`ent: missing required field "Certificate.key_enc"`)}
	}
	if v, ok := _c.mutation.KeyEnc(); ok {
		if err := certificate.KeyEncValidator(v); err != nil {
			return &ValidationError{Name: "key_enc", err: fmt.Errorf(`ent: validator failed for field "Certificate.key_enc": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentSha256(); !ok {
		return &ValidationError{Name: "content_sha256", err: errors.New(`ent: missing required field "Certificate.content_sha256"`)}
	}
	if v, ok := _c.mutation.ContentSha256(); ok {
		if err := certificate.ContentSha256Validator(v); err != nil {
			return &ValidationError{Name: "content_sha256", err: fmt.Errorf(`ent: validator failed for field "Certificate.content_sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Certificate.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := certificate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Certificate.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Certificate.created_at"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Certificate.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := certificate.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Certificate.version": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := certificate.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Certificate.id": %w`, err)}
		}
	}
	return nil
}

func (_c *CertificateCreate) sqlSave(ctx context.Context) (*Certificate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Certificate.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CertificateCreate) createSpec() (*Certificate, *sqlgraph.CreateSpec) {
	var (
		_node = &Certificate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(certificate.Table, sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OrgID(); ok {
		_spec.SetField(certificate.FieldOrgID, field.TypeString, value)
		_node.OrgID = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(certificate.FieldSource, field.TypeEnum, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Sans(); ok {
		_spec.SetField(certificate.FieldSans, field.TypeJSON, value)
		_node.Sans = value
	}
	if value, ok := _c.mutation.NotBefore(); ok {
		_spec.SetField(certificate.FieldNotBefore, field.TypeTime, value)
		_node.NotBefore = value
	}
	if value, ok := _c.mutation.NotAfter(); ok {
		_spec.SetField(certificate.FieldNotAfter, field.TypeTime, value)
		_node.NotAfter = value
	}
	if value, ok := _c.mutation.Chain(); ok {
		_spec.SetField(certificate.FieldChain, field.TypeBytes, value)
		_node.Chain = value
	}
	if value, ok := _c.mutation.KeyEnc(); ok {
		_spec.SetField(certificate.FieldKeyEnc, field.TypeBytes, value)
		_node.KeyEnc = value
	}
	if value, ok := _c.mutation.ContentSha256(); ok {
		_spec.SetField(certificate.FieldContentSha256, field.TypeBytes, value)
		_node.ContentSha256 = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(certificate.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(certificate.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.Issuer(); ok {
		_spec.SetField(certificate.FieldIssuer, field.TypeString, value)
		_node.Issuer = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(certificate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(certificate.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	return _node, _spec
}

// CertificateCreateBulk is the builder for creating many Certificate entities in bulk.
type CertificateCreateBulk struct {
	config
	err      error
	builders []*CertificateCreate
}

// Save creates the Certificate entities in the database.
func (_c *CertificateCreateBulk) Save(ctx context.Context) ([]*Certificate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Certificate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CertificateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CertificateCreateBulk) SaveX(ctx context.Context) []*Certificate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CertificateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CertificateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
