// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felix-homelab/rpmgr/internal/store/ent/enrollmenttoken"
	"github.com/felix-homelab/rpmgr/internal/store/ent/predicate"
)

// EnrollmentTokenUpdate is the builder for updating EnrollmentToken entities.
type EnrollmentTokenUpdate struct {
	config
	hooks    []Hook
	mutation *EnrollmentTokenMutation
}

// Where appends a list predicates to the EnrollmentTokenUpdate builder.
func (_u *EnrollmentTokenUpdate) Where(ps ...predicate.EnrollmentToken) *EnrollmentTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLabels sets the "labels" field.
func (_u *EnrollmentTokenUpdate) SetLabels(v map[string]string) *EnrollmentTokenUpdate {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *EnrollmentTokenUpdate) ClearLabels() *EnrollmentTokenUpdate {
	_u.mutation.ClearLabels()
	return _u
}

// SetUseCount sets the "use_count" field.
func (_u *EnrollmentTokenUpdate) SetUseCount(v int) *EnrollmentTokenUpdate {
	_u.mutation.ResetUseCount()
	_u.mutation.SetUseCount(v)
	return _u
}

// SetNillableUseCount sets the "use_count" field if the given value is not nil.
func (_u *EnrollmentTokenUpdate) SetNillableUseCount(v *int) *EnrollmentTokenUpdate {
	if v != nil {
		_u.SetUseCount(*v)
	}
	return _u
}

// AddUseCount adds value to the "use_count" field.
func (_u *EnrollmentTokenUpdate) AddUseCount(v int) *EnrollmentTokenUpdate {
	_u.mutation.AddUseCount(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *EnrollmentTokenUpdate) SetLastUsedAt(v time.Time) *EnrollmentTokenUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *EnrollmentTokenUpdate) SetNillableLastUsedAt(v *time.Time) *EnrollmentTokenUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *EnrollmentTokenUpdate) ClearLastUsedAt() *EnrollmentTokenUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetLastUsedIP sets the "last_used_ip" field.
func (_u *EnrollmentTokenUpdate) SetLastUsedIP(v string) *EnrollmentTokenUpdate {
	_u.mutation.SetLastUsedIP(v)
	return _u
}

// SetNillableLastUsedIP sets the "last_used_ip" field if the given value is not nil.
func (_u *EnrollmentTokenUpdate) SetNillableLastUsedIP(v *string) *EnrollmentTokenUpdate {
	if v != nil {
		_u.SetLastUsedIP(*v)
	}
	return _u
}

// ClearLastUsedIP clears the value of the "last_used_ip" field.
func (_u *EnrollmentTokenUpdate) ClearLastUsedIP() *EnrollmentTokenUpdate {
	_u.mutation.ClearLastUsedIP()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *EnrollmentTokenUpdate) SetRevokedAt(v time.Time) *EnrollmentTokenUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *EnrollmentTokenUpdate) SetNillableRevokedAt(v *time.Time) *EnrollmentTokenUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *EnrollmentTokenUpdate) ClearRevokedAt() *EnrollmentTokenUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the EnrollmentTokenMutation object of the builder.
func (_u *EnrollmentTokenUpdate) Mutation() *EnrollmentTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnrollmentTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnrollmentTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnrollmentTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnrollmentTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnrollmentTokenUpdate) check() error {
	if v, ok := _u.mutation.UseCount(); ok {
		if err := enrollmenttoken.UseCountValidator(v); err != nil {
			return &ValidationError{Name: "use_count", err: fmt.Errorf(`ent: validator failed for field "EnrollmentToken.use_count": %w`, err)}
		}
	}
	return nil
}

func (_u *EnrollmentTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enrollmenttoken.Table, enrollmenttoken.Columns, sqlgraph.NewFieldSpec(enrollmenttoken.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(enrollmenttoken.FieldLabels, field.TypeJSON, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(enrollmenttoken.FieldLabels, field.TypeJSON)
	}
	if value, ok := _u.mutation.UseCount(); ok {
		_spec.SetField(enrollmenttoken.FieldUseCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUseCount(); ok {
		_spec.AddField(enrollmenttoken.FieldUseCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(enrollmenttoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(enrollmenttoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedIP(); ok {
		_spec.SetField(enrollmenttoken.FieldLastUsedIP, field.TypeString, value)
	}
	if _u.mutation.LastUsedIPCleared() {
		_spec.ClearField(enrollmenttoken.FieldLastUsedIP, field.TypeString)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(enrollmenttoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(enrollmenttoken.FieldRevokedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enrollmenttoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnrollmentTokenUpdateOne is the builder for updating a single EnrollmentToken entity.
type EnrollmentTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnrollmentTokenMutation
}

// SetLabels sets the "labels" field.
func (_u *EnrollmentTokenUpdateOne) SetLabels(v map[string]string) *EnrollmentTokenUpdateOne {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *EnrollmentTokenUpdateOne) ClearLabels() *EnrollmentTokenUpdateOne {
	_u.mutation.ClearLabels()
	return _u
}

// SetUseCount sets the "use_count" field.
func (_u *EnrollmentTokenUpdateOne) SetUseCount(v int) *EnrollmentTokenUpdateOne {
	_u.mutation.ResetUseCount()
	_u.mutation.SetUseCount(v)
	return _u
}

// SetNillableUseCount sets the "use_count" field if the given value is not nil.
func (_u *EnrollmentTokenUpdateOne) SetNillableUseCount(v *int) *EnrollmentTokenUpdateOne {
	if v != nil {
		_u.SetUseCount(*v)
	}
	return _u
}

// AddUseCount adds value to the "use_count" field.
func (_u *EnrollmentTokenUpdateOne) AddUseCount(v int) *EnrollmentTokenUpdateOne {
	_u.mutation.AddUseCount(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *EnrollmentTokenUpdateOne) SetLastUsedAt(v time.Time) *EnrollmentTokenUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *EnrollmentTokenUpdateOne) SetNillableLastUsedAt(v *time.Time) *EnrollmentTokenUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *EnrollmentTokenUpdateOne) ClearLastUsedAt() *EnrollmentTokenUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetLastUsedIP sets the "last_used_ip" field.
func (_u *EnrollmentTokenUpdateOne) SetLastUsedIP(v string) *EnrollmentTokenUpdateOne {
	_u.mutation.SetLastUsedIP(v)
	return _u
}

// SetNillableLastUsedIP sets the "last_used_ip" field if the given value is not nil.
func (_u *EnrollmentTokenUpdateOne) SetNillableLastUsedIP(v *string) *EnrollmentTokenUpdateOne {
	if v != nil {
		_u.SetLastUsedIP(*v)
	}
	return _u
}

// ClearLastUsedIP clears the value of the "last_used_ip" field.
func (_u *EnrollmentTokenUpdateOne) ClearLastUsedIP() *EnrollmentTokenUpdateOne {
	_u.mutation.ClearLastUsedIP()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *EnrollmentTokenUpdateOne) SetRevokedAt(v time.Time) *EnrollmentTokenUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *EnrollmentTokenUpdateOne) SetNillableRevokedAt(v *time.Time) *EnrollmentTokenUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *EnrollmentTokenUpdateOne) ClearRevokedAt() *EnrollmentTokenUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the EnrollmentTokenMutation object of the builder.
func (_u *EnrollmentTokenUpdateOne) Mutation() *EnrollmentTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the EnrollmentTokenUpdate builder.
func (_u *EnrollmentTokenUpdateOne) Where(ps ...predicate.EnrollmentToken) *EnrollmentTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnrollmentTokenUpdateOne) Select(field string, fields ...string) *EnrollmentTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EnrollmentToken entity.
func (_u *EnrollmentTokenUpdateOne) Save(ctx context.Context) (*EnrollmentToken, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnrollmentTokenUpdateOne) SaveX(ctx context.Context) *EnrollmentToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnrollmentTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnrollmentTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnrollmentTokenUpdateOne) check() error {
	if v, ok := _u.mutation.UseCount(); ok {
		if err := enrollmenttoken.UseCountValidator(v); err != nil {
			return &ValidationError{Name: "use_count", err: fmt.Errorf(`ent: validator failed for field "EnrollmentToken.use_count": %w`, err)}
		}
	}
	return nil
}

func (_u *EnrollmentTokenUpdateOne) sqlSave(ctx context.Context) (_node *EnrollmentToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enrollmenttoken.Table, enrollmenttoken.Columns, sqlgraph.NewFieldSpec(enrollmenttoken.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EnrollmentToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enrollmenttoken.FieldID)
		for _, f := range fields {
			if !enrollmenttoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != enrollmenttoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(enrollmenttoken.FieldLabels, field.TypeJSON, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(enrollmenttoken.FieldLabels, field.TypeJSON)
	}
	if value, ok := _u.mutation.UseCount(); ok {
		_spec.SetField(enrollmenttoken.FieldUseCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUseCount(); ok {
		_spec.AddField(enrollmenttoken.FieldUseCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(enrollmenttoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(enrollmenttoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedIP(); ok {
		_spec.SetField(enrollmenttoken.FieldLastUsedIP, field.TypeString, value)
	}
	if _u.mutation.LastUsedIPCleared() {
		_spec.ClearField(enrollmenttoken.FieldLastUsedIP, field.TypeString)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(enrollmenttoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(enrollmenttoken.FieldRevokedAt, field.TypeTime)
	}
	_node = &EnrollmentToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enrollmenttoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
