// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/felix-homelab/rpmgr/internal/store/ent/gatewaygroup"
	"github.com/felix-homelab/rpmgr/internal/store/ent/predicate"
)

// GatewayGroupUpdate is the builder for updating GatewayGroup entities.
type GatewayGroupUpdate struct {
	config
	hooks    []Hook
	mutation *GatewayGroupMutation
}

// Where appends a list predicates to the GatewayGroupUpdate builder.
func (_u *GatewayGroupUpdate) Where(ps ...predicate.GatewayGroup) *GatewayGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *GatewayGroupUpdate) SetName(v string) *GatewayGroupUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GatewayGroupUpdate) SetNillableName(v *string) *GatewayGroupUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *GatewayGroupUpdate) SetRegion(v string) *GatewayGroupUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *GatewayGroupUpdate) SetNillableRegion(v *string) *GatewayGroupUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// ClearRegion clears the value of the "region" field.
func (_u *GatewayGroupUpdate) ClearRegion() *GatewayGroupUpdate {
	_u.mutation.ClearRegion()
	return _u
}

// SetPublicHostnames sets the "public_hostnames" field.
func (_u *GatewayGroupUpdate) SetPublicHostnames(v []string) *GatewayGroupUpdate {
	_u.mutation.SetPublicHostnames(v)
	return _u
}

// AppendPublicHostnames appends value to the "public_hostnames" field.
func (_u *GatewayGroupUpdate) AppendPublicHostnames(v []string) *GatewayGroupUpdate {
	_u.mutation.AppendPublicHostnames(v)
	return _u
}

// ClearPublicHostnames clears the value of the "public_hostnames" field.
func (_u *GatewayGroupUpdate) ClearPublicHostnames() *GatewayGroupUpdate {
	_u.mutation.ClearPublicHostnames()
	return _u
}

// SetTrustedProxyCidrs sets the "trusted_proxy_cidrs" field.
func (_u *GatewayGroupUpdate) SetTrustedProxyCidrs(v []string) *GatewayGroupUpdate {
	_u.mutation.SetTrustedProxyCidrs(v)
	return _u
}

// AppendTrustedProxyCidrs appends value to the "trusted_proxy_cidrs" field.
func (_u *GatewayGroupUpdate) AppendTrustedProxyCidrs(v []string) *GatewayGroupUpdate {
	_u.mutation.AppendTrustedProxyCidrs(v)
	return _u
}

// ClearTrustedProxyCidrs clears the value of the "trusted_proxy_cidrs" field.
func (_u *GatewayGroupUpdate) ClearTrustedProxyCidrs() *GatewayGroupUpdate {
	_u.mutation.ClearTrustedProxyCidrs()
	return _u
}

// Mutation returns the GatewayGroupMutation object of the builder.
func (_u *GatewayGroupUpdate) Mutation() *GatewayGroupMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GatewayGroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GatewayGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GatewayGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GatewayGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GatewayGroupUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := gatewaygroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "GatewayGroup.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicHostnames(); ok {
		if err := gatewaygroup.PublicHostnamesValidator(v); err != nil {
			return &ValidationError{Name: "public_hostnames", err: fmt.Errorf(`ent: validator failed for field "GatewayGroup.public_hostnames": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TrustedProxyCidrs(); ok {
		if err := gatewaygroup.TrustedProxyCidrsValidator(v); err != nil {
			return &ValidationError{Name: "trusted_proxy_cidrs", err: fmt.Errorf(`ent: validator failed for field "GatewayGroup.trusted_proxy_cidrs": %w`, err)}
		}
	}
	return nil
}

func (_u *GatewayGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gatewaygroup.Table, gatewaygroup.Columns, sqlgraph.NewFieldSpec(gatewaygroup.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(gatewaygroup.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(gatewaygroup.FieldRegion, field.TypeString, value)
	}
	if _u.mutation.RegionCleared() {
		_spec.ClearField(gatewaygroup.FieldRegion, field.TypeString)
	}
	if value, ok := _u.mutation.PublicHostnames(); ok {
		_spec.SetField(gatewaygroup.FieldPublicHostnames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPublicHostnames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gatewaygroup.FieldPublicHostnames, value)
		})
	}
	if _u.mutation.PublicHostnamesCleared() {
		_spec.ClearField(gatewaygroup.FieldPublicHostnames, field.TypeJSON)
	}
	if value, ok := _u.mutation.TrustedProxyCidrs(); ok {
		_spec.SetField(gatewaygroup.FieldTrustedProxyCidrs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTrustedProxyCidrs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gatewaygroup.FieldTrustedProxyCidrs, value)
		})
	}
	if _u.mutation.TrustedProxyCidrsCleared() {
		_spec.ClearField(gatewaygroup.FieldTrustedProxyCidrs, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gatewaygroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GatewayGroupUpdateOne is the builder for updating a single GatewayGroup entity.
type GatewayGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GatewayGroupMutation
}

// SetName sets the "name" field.
func (_u *GatewayGroupUpdateOne) SetName(v string) *GatewayGroupUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GatewayGroupUpdateOne) SetNillableName(v *string) *GatewayGroupUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *GatewayGroupUpdateOne) SetRegion(v string) *GatewayGroupUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *GatewayGroupUpdateOne) SetNillableRegion(v *string) *GatewayGroupUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// ClearRegion clears the value of the "region" field.
func (_u *GatewayGroupUpdateOne) ClearRegion() *GatewayGroupUpdateOne {
	_u.mutation.ClearRegion()
	return _u
}

// SetPublicHostnames sets the "public_hostnames" field.
func (_u *GatewayGroupUpdateOne) SetPublicHostnames(v []string) *GatewayGroupUpdateOne {
	_u.mutation.SetPublicHostnames(v)
	return _u
}

// AppendPublicHostnames appends value to the "public_hostnames" field.
func (_u *GatewayGroupUpdateOne) AppendPublicHostnames(v []string) *GatewayGroupUpdateOne {
	_u.mutation.AppendPublicHostnames(v)
	return _u
}

// ClearPublicHostnames clears the value of the "public_hostnames" field.
func (_u *GatewayGroupUpdateOne) ClearPublicHostnames() *GatewayGroupUpdateOne {
	_u.mutation.ClearPublicHostnames()
	return _u
}

// SetTrustedProxyCidrs sets the "trusted_proxy_cidrs" field.
func (_u *GatewayGroupUpdateOne) SetTrustedProxyCidrs(v []string) *GatewayGroupUpdateOne {
	_u.mutation.SetTrustedProxyCidrs(v)
	return _u
}

// AppendTrustedProxyCidrs appends value to the "trusted_proxy_cidrs" field.
func (_u *GatewayGroupUpdateOne) AppendTrustedProxyCidrs(v []string) *GatewayGroupUpdateOne {
	_u.mutation.AppendTrustedProxyCidrs(v)
	return _u
}

// ClearTrustedProxyCidrs clears the value of the "trusted_proxy_cidrs" field.
func (_u *GatewayGroupUpdateOne) ClearTrustedProxyCidrs() *GatewayGroupUpdateOne {
	_u.mutation.ClearTrustedProxyCidrs()
	return _u
}

// Mutation returns the GatewayGroupMutation object of the builder.
func (_u *GatewayGroupUpdateOne) Mutation() *GatewayGroupMutation {
	return _u.mutation
}

// Where appends a list predicates to the GatewayGroupUpdate builder.
func (_u *GatewayGroupUpdateOne) Where(ps ...predicate.GatewayGroup) *GatewayGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GatewayGroupUpdateOne) Select(field string, fields ...string) *GatewayGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GatewayGroup entity.
func (_u *GatewayGroupUpdateOne) Save(ctx context.Context) (*GatewayGroup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GatewayGroupUpdateOne) SaveX(ctx context.Context) *GatewayGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GatewayGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GatewayGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GatewayGroupUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := gatewaygroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "GatewayGroup.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicHostnames(); ok {
		if err := gatewaygroup.PublicHostnamesValidator(v); err != nil {
			return &ValidationError{Name: "public_hostnames", err: fmt.Errorf(`ent: validator failed for field "GatewayGroup.public_hostnames": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TrustedProxyCidrs(); ok {
		if err := gatewaygroup.TrustedProxyCidrsValidator(v); err != nil {
			return &ValidationError{Name: "trusted_proxy_cidrs", err: fmt.Errorf(`ent: validator failed for field "GatewayGroup.trusted_proxy_cidrs": %w`, err)}
		}
	}
	return nil
}

func (_u *GatewayGroupUpdateOne) sqlSave(ctx context.Context) (_node *GatewayGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gatewaygroup.Table, gatewaygroup.Columns, sqlgraph.NewFieldSpec(gatewaygroup.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GatewayGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gatewaygroup.FieldID)
		for _, f := range fields {
			if !gatewaygroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gatewaygroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(gatewaygroup.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(gatewaygroup.FieldRegion, field.TypeString, value)
	}
	if _u.mutation.RegionCleared() {
		_spec.ClearField(gatewaygroup.FieldRegion, field.TypeString)
	}
	if value, ok := _u.mutation.PublicHostnames(); ok {
		_spec.SetField(gatewaygroup.FieldPublicHostnames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPublicHostnames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gatewaygroup.FieldPublicHostnames, value)
		})
	}
	if _u.mutation.PublicHostnamesCleared() {
		_spec.ClearField(gatewaygroup.FieldPublicHostnames, field.TypeJSON)
	}
	if value, ok := _u.mutation.TrustedProxyCidrs(); ok {
		_spec.SetField(gatewaygroup.FieldTrustedProxyCidrs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTrustedProxyCidrs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gatewaygroup.FieldTrustedProxyCidrs, value)
		})
	}
	if _u.mutation.TrustedProxyCidrsCleared() {
		_spec.ClearField(gatewaygroup.FieldTrustedProxyCidrs, field.TypeJSON)
	}
	_node = &GatewayGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gatewaygroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
