// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felix-homelab/rpmgr/internal/store/ent/instance"
)

// InstanceCreate is the builder for creating a Instance entity.
type InstanceCreate struct {
	config
	mutation *InstanceMutation
	hooks    []Hook
}

// SetTrustDomain sets the "trust_domain" field.
func (_c *InstanceCreate) SetTrustDomain(v string) *InstanceCreate {
	_c.mutation.SetTrustDomain(v)
	return _c
}

// SetDbEpoch sets the "db_epoch" field.
func (_c *InstanceCreate) SetDbEpoch(v string) *InstanceCreate {
	_c.mutation.SetDbEpoch(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InstanceCreate) SetCreatedAt(v time.Time) *InstanceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InstanceCreate) SetNillableCreatedAt(v *time.Time) *InstanceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InstanceCreate) SetID(v int) *InstanceCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the InstanceMutation object of the builder.
func (_c *InstanceCreate) Mutation() *InstanceMutation {
	return _c.mutation
}

// Save creates the Instance in the database.
func (_c *InstanceCreate) Save(ctx context.Context) (*Instance, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InstanceCreate) SaveX(ctx context.Context) *Instance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InstanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InstanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InstanceCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if instance.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized instance.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := instance.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *InstanceCreate) check() error {
	if _, ok := _c.mutation.TrustDomain(); !ok {
		return &ValidationError{Name: "trust_domain", err: errors.New(`ent: missing required field "Instance.trust_domain"`)}
	}
	if v, ok := _c.mutation.TrustDomain(); ok {
		if err := instance.TrustDomainValidator(v); err != nil {
			return &ValidationError{Name: "trust_domain", err: fmt.Errorf(`ent: validator failed for field "Instance.trust_domain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DbEpoch(); !ok {
		return &ValidationError{Name: "db_epoch", err: errors.New(`ent: missing required field "Instance.db_epoch"`)}
	}
	if v, ok := _c.mutation.DbEpoch(); ok {
		if err := instance.DbEpochValidator(v); err != nil {
			return &ValidationError{Name: "db_epoch", err: fmt.Errorf(`ent: validator failed for field "Instance.db_epoch": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Instance.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := instance.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Instance.id": %w`, err)}
		}
	}
	return nil
}

func (_c *InstanceCreate) sqlSave(ctx context.Context) (*Instance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InstanceCreate) createSpec() (*Instance, *sqlgraph.CreateSpec) {
	var (
		_node = &Instance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(instance.Table, sqlgraph.NewFieldSpec(instance.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TrustDomain(); ok {
		_spec.SetField(instance.FieldTrustDomain, field.TypeString, value)
		_node.TrustDomain = value
	}
	if value, ok := _c.mutation.DbEpoch(); ok {
		_spec.SetField(instance.FieldDbEpoch, field.TypeString, value)
		_node.DbEpoch = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(instance.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// InstanceCreateBulk is the builder for creating many Instance entities in bulk.
type InstanceCreateBulk struct {
	config
	err      error
	builders []*InstanceCreate
}

// Save creates the Instance entities in the database.
func (_c *InstanceCreateBulk) Save(ctx context.Context) ([]*Instance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Instance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InstanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InstanceCreateBulk) SaveX(ctx context.Context) []*Instance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InstanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InstanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
