// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felix-homelab/rpmgr/internal/store/ent/instancesecret"
	"github.com/felix-homelab/rpmgr/internal/store/ent/predicate"
)

// InstanceSecretUpdate is the builder for updating InstanceSecret entities.
type InstanceSecretUpdate struct {
	config
	hooks    []Hook
	mutation *InstanceSecretMutation
}

// Where appends a list predicates to the InstanceSecretUpdate builder.
func (_u *InstanceSecretUpdate) Where(ps ...predicate.InstanceSecret) *InstanceSecretUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetValueEnc sets the "value_enc" field.
func (_u *InstanceSecretUpdate) SetValueEnc(v []byte) *InstanceSecretUpdate {
	_u.mutation.SetValueEnc(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InstanceSecretUpdate) SetUpdatedAt(v time.Time) *InstanceSecretUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *InstanceSecretUpdate) SetNillableUpdatedAt(v *time.Time) *InstanceSecretUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the InstanceSecretMutation object of the builder.
func (_u *InstanceSecretUpdate) Mutation() *InstanceSecretMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InstanceSecretUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InstanceSecretUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InstanceSecretUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InstanceSecretUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InstanceSecretUpdate) check() error {
	if v, ok := _u.mutation.ValueEnc(); ok {
		if err := instancesecret.ValueEncValidator(v); err != nil {
			return &ValidationError{Name: "value_enc", err: fmt.Errorf(`ent: validator failed for field "InstanceSecret.value_enc": %w`, err)}
		}
	}
	return nil
}

func (_u *InstanceSecretUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(instancesecret.Table, instancesecret.Columns, sqlgraph.NewFieldSpec(instancesecret.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ValueEnc(); ok {
		_spec.SetField(instancesecret.FieldValueEnc, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(instancesecret.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{instancesecret.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InstanceSecretUpdateOne is the builder for updating a single InstanceSecret entity.
type InstanceSecretUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InstanceSecretMutation
}

// SetValueEnc sets the "value_enc" field.
func (_u *InstanceSecretUpdateOne) SetValueEnc(v []byte) *InstanceSecretUpdateOne {
	_u.mutation.SetValueEnc(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InstanceSecretUpdateOne) SetUpdatedAt(v time.Time) *InstanceSecretUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *InstanceSecretUpdateOne) SetNillableUpdatedAt(v *time.Time) *InstanceSecretUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the InstanceSecretMutation object of the builder.
func (_u *InstanceSecretUpdateOne) Mutation() *InstanceSecretMutation {
	return _u.mutation
}

// Where appends a list predicates to the InstanceSecretUpdate builder.
func (_u *InstanceSecretUpdateOne) Where(ps ...predicate.InstanceSecret) *InstanceSecretUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InstanceSecretUpdateOne) Select(field string, fields ...string) *InstanceSecretUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InstanceSecret entity.
func (_u *InstanceSecretUpdateOne) Save(ctx context.Context) (*InstanceSecret, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InstanceSecretUpdateOne) SaveX(ctx context.Context) *InstanceSecret {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InstanceSecretUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InstanceSecretUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InstanceSecretUpdateOne) check() error {
	if v, ok := _u.mutation.ValueEnc(); ok {
		if err := instancesecret.ValueEncValidator(v); err != nil {
			return &ValidationError{Name: "value_enc", err: fmt.Errorf(`ent: validator failed for field "InstanceSecret.value_enc": %w`, err)}
		}
	}
	return nil
}

func (_u *InstanceSecretUpdateOne) sqlSave(ctx context.Context) (_node *InstanceSecret, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(instancesecret.Table, instancesecret.Columns, sqlgraph.NewFieldSpec(instancesecret.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InstanceSecret.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, instancesecret.FieldID)
		for _, f := range fields {
			if !instancesecret.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != instancesecret.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ValueEnc(); ok {
		_spec.SetField(instancesecret.FieldValueEnc, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(instancesecret.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &InstanceSecret{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{instancesecret.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
