// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/felix-homelab/rpmgr/internal/store/ent/issuedcertificate"
)

// IssuedCertificate is the model entity for the IssuedCertificate schema.
type IssuedCertificate struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// OrgID holds the value of the "org_id" field.
	OrgID *string `json:"org_id,omitempty"`
	// SubjectType holds the value of the "subject_type" field.
	SubjectType issuedcertificate.SubjectType `json:"subject_type,omitempty"`
	// SubjectID holds the value of the "subject_id" field.
	SubjectID string `json:"subject_id,omitempty"`
	// SpiffeID holds the value of the "spiffe_id" field.
	SpiffeID string `json:"spiffe_id,omitempty"`
	// PubkeySha256 holds the value of the "pubkey_sha256" field.
	PubkeySha256 string `json:"pubkey_sha256,omitempty"`
	// NotBefore holds the value of the "not_before" field.
	NotBefore time.Time `json:"not_before,omitempty"`
	// NotAfter holds the value of the "not_after" field.
	NotAfter time.Time `json:"not_after,omitempty"`
	// FirstSeenAt holds the value of the "first_seen_at" field.
	FirstSeenAt *time.Time `json:"first_seen_at,omitempty"`
	// SupersededAt holds the value of the "superseded_at" field.
	SupersededAt *time.Time `json:"superseded_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// RevocationReason holds the value of the "revocation_reason" field.
	RevocationReason string `json:"revocation_reason,omitempty"`
	selectValues     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IssuedCertificate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case issuedcertificate.FieldID, issuedcertificate.FieldOrgID, issuedcertificate.FieldSubjectType, issuedcertificate.FieldSubjectID, issuedcertificate.FieldSpiffeID, issuedcertificate.FieldPubkeySha256, issuedcertificate.FieldRevocationReason:
			values[i] = new(sql.NullString)
		case issuedcertificate.FieldNotBefore, issuedcertificate.FieldNotAfter, issuedcertificate.FieldFirstSeenAt, issuedcertificate.FieldSupersededAt, issuedcertificate.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IssuedCertificate fields.
func (_m *IssuedCertificate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case issuedcertificate.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case issuedcertificate.FieldOrgID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field org_id", values[i])
			} else if value.Valid {
				_m.OrgID = new(string)
				*_m.OrgID = value.String
			}
		case issuedcertificate.FieldSubjectType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject_type", values[i])
			} else if value.Valid {
				_m.SubjectType = issuedcertificate.SubjectType(value.String)
			}
		case issuedcertificate.FieldSubjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject_id", values[i])
			} else if value.Valid {
				_m.SubjectID = value.String
			}
		case issuedcertificate.FieldSpiffeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field spiffe_id", values[i])
			} else if value.Valid {
				_m.SpiffeID = value.String
			}
		case issuedcertificate.FieldPubkeySha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pubkey_sha256", values[i])
			} else if value.Valid {
				_m.PubkeySha256 = value.String
			}
		case issuedcertificate.FieldNotBefore:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field not_before", values[i])
			} else if value.Valid {
				_m.NotBefore = value.Time
			}
		case issuedcertificate.FieldNotAfter:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field not_after", values[i])
			} else if value.Valid {
				_m.NotAfter = value.Time
			}
		case issuedcertificate.FieldFirstSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_seen_at", values[i])
			} else if value.Valid {
				_m.FirstSeenAt = new(time.Time)
				*_m.FirstSeenAt = value.Time
			}
		case issuedcertificate.FieldSupersededAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field superseded_at", values[i])
			} else if value.Valid {
				_m.SupersededAt = new(time.Time)
				*_m.SupersededAt = value.Time
			}
		case issuedcertificate.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case issuedcertificate.FieldRevocationReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field revocation_reason", values[i])
			} else if value.Valid {
				_m.RevocationReason = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IssuedCertificate.
// This includes values selected through modifiers, order, etc.
func (_m *IssuedCertificate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IssuedCertificate.
// Note that you need to call IssuedCertificate.Unwrap() before calling this method if this IssuedCertificate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IssuedCertificate) Update() *IssuedCertificateUpdateOne {
	return NewIssuedCertificateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IssuedCertificate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IssuedCertificate) Unwrap() *IssuedCertificate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IssuedCertificate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IssuedCertificate) String() string {
	var builder strings.Builder
	builder.WriteString("IssuedCertificate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.OrgID; v != nil {
		builder.WriteString("org_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("subject_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubjectType))
	builder.WriteString(", ")
	builder.WriteString("subject_id=")
	builder.WriteString(_m.SubjectID)
	builder.WriteString(", ")
	builder.WriteString("spiffe_id=")
	builder.WriteString(_m.SpiffeID)
	builder.WriteString(", ")
	builder.WriteString("pubkey_sha256=")
	builder.WriteString(_m.PubkeySha256)
	builder.WriteString(", ")
	builder.WriteString("not_before=")
	builder.WriteString(_m.NotBefore.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("not_after=")
	builder.WriteString(_m.NotAfter.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FirstSeenAt; v != nil {
		builder.WriteString("first_seen_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SupersededAt; v != nil {
		builder.WriteString("superseded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("revocation_reason=")
	builder.WriteString(_m.RevocationReason)
	builder.WriteByte(')')
	return builder.String()
}

// IssuedCertificates is a parsable slice of IssuedCertificate.
type IssuedCertificates []*IssuedCertificate
