// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felix-homelab/rpmgr/internal/store/ent/orgsetting"
	"github.com/felix-homelab/rpmgr/internal/store/ent/predicate"
)

// OrgSettingDelete is the builder for deleting a OrgSetting entity.
type OrgSettingDelete struct {
	config
	hooks    []Hook
	mutation *OrgSettingMutation
}

// Where appends a list predicates to the OrgSettingDelete builder.
func (_d *OrgSettingDelete) Where(ps ...predicate.OrgSetting) *OrgSettingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OrgSettingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrgSettingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OrgSettingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(orgsetting.Table, sqlgraph.NewFieldSpec(orgsetting.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OrgSettingDeleteOne is the builder for deleting a single OrgSetting entity.
type OrgSettingDeleteOne struct {
	_d *OrgSettingDelete
}

// Where appends a list predicates to the OrgSettingDelete builder.
func (_d *OrgSettingDeleteOne) Where(ps ...predicate.OrgSetting) *OrgSettingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OrgSettingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{orgsetting.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrgSettingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
