// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felix-homelab/rpmgr/internal/store/ent/predicate"
	"github.com/felix-homelab/rpmgr/internal/store/ent/revokedserial"
)

// RevokedSerialUpdate is the builder for updating RevokedSerial entities.
type RevokedSerialUpdate struct {
	config
	hooks    []Hook
	mutation *RevokedSerialMutation
}

// Where appends a list predicates to the RevokedSerialUpdate builder.
func (_u *RevokedSerialUpdate) Where(ps ...predicate.RevokedSerial) *RevokedSerialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the RevokedSerialMutation object of the builder.
func (_u *RevokedSerialUpdate) Mutation() *RevokedSerialMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RevokedSerialUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RevokedSerialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RevokedSerialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RevokedSerialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RevokedSerialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(revokedserial.Table, revokedserial.Columns, sqlgraph.NewFieldSpec(revokedserial.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.OrgIDCleared() {
		_spec.ClearField(revokedserial.FieldOrgID, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{revokedserial.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RevokedSerialUpdateOne is the builder for updating a single RevokedSerial entity.
type RevokedSerialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RevokedSerialMutation
}

// Mutation returns the RevokedSerialMutation object of the builder.
func (_u *RevokedSerialUpdateOne) Mutation() *RevokedSerialMutation {
	return _u.mutation
}

// Where appends a list predicates to the RevokedSerialUpdate builder.
func (_u *RevokedSerialUpdateOne) Where(ps ...predicate.RevokedSerial) *RevokedSerialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RevokedSerialUpdateOne) Select(field string, fields ...string) *RevokedSerialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RevokedSerial entity.
func (_u *RevokedSerialUpdateOne) Save(ctx context.Context) (*RevokedSerial, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RevokedSerialUpdateOne) SaveX(ctx context.Context) *RevokedSerial {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RevokedSerialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RevokedSerialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RevokedSerialUpdateOne) sqlSave(ctx context.Context) (_node *RevokedSerial, err error) {
	_spec := sqlgraph.NewUpdateSpec(revokedserial.Table, revokedserial.Columns, sqlgraph.NewFieldSpec(revokedserial.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RevokedSerial.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, revokedserial.FieldID)
		for _, f := range fields {
			if !revokedserial.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != revokedserial.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.OrgIDCleared() {
		_spec.ClearField(revokedserial.FieldOrgID, field.TypeString)
	}
	_node = &RevokedSerial{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{revokedserial.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
