// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felix-homelab/rpmgr/internal/store/ent/predicate"
	"github.com/felix-homelab/rpmgr/internal/store/ent/routehostname"
)

// RouteHostnameDelete is the builder for deleting a RouteHostname entity.
type RouteHostnameDelete struct {
	config
	hooks    []Hook
	mutation *RouteHostnameMutation
}

// Where appends a list predicates to the RouteHostnameDelete builder.
func (_d *RouteHostnameDelete) Where(ps ...predicate.RouteHostname) *RouteHostnameDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RouteHostnameDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RouteHostnameDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RouteHostnameDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(routehostname.Table, sqlgraph.NewFieldSpec(routehostname.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RouteHostnameDeleteOne is the builder for deleting a single RouteHostname entity.
type RouteHostnameDeleteOne struct {
	_d *RouteHostnameDelete
}

// Where appends a list predicates to the RouteHostnameDelete builder.
func (_d *RouteHostnameDeleteOne) Where(ps ...predicate.RouteHostname) *RouteHostnameDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RouteHostnameDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{routehostname.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RouteHostnameDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
