// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felix-homelab/rpmgr/internal/store/ent/routetraffichourly"
)

// RouteTrafficHourlyCreate is the builder for creating a RouteTrafficHourly entity.
type RouteTrafficHourlyCreate struct {
	config
	mutation *RouteTrafficHourlyMutation
	hooks    []Hook
}

// SetOrgID sets the "org_id" field.
func (_c *RouteTrafficHourlyCreate) SetOrgID(v string) *RouteTrafficHourlyCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetRouteID sets the "route_id" field.
func (_c *RouteTrafficHourlyCreate) SetRouteID(v string) *RouteTrafficHourlyCreate {
	_c.mutation.SetRouteID(v)
	return _c
}

// SetBucket sets the "bucket" field.
func (_c *RouteTrafficHourlyCreate) SetBucket(v time.Time) *RouteTrafficHourlyCreate {
	_c.mutation.SetBucket(v)
	return _c
}

// SetBytesIn sets the "bytes_in" field.
func (_c *RouteTrafficHourlyCreate) SetBytesIn(v int64) *RouteTrafficHourlyCreate {
	_c.mutation.SetBytesIn(v)
	return _c
}

// SetBytesOut sets the "bytes_out" field.
func (_c *RouteTrafficHourlyCreate) SetBytesOut(v int64) *RouteTrafficHourlyCreate {
	_c.mutation.SetBytesOut(v)
	return _c
}

// SetConnections sets the "connections" field.
func (_c *RouteTrafficHourlyCreate) SetConnections(v int64) *RouteTrafficHourlyCreate {
	_c.mutation.SetConnections(v)
	return _c
}

// SetErrors sets the "errors" field.
func (_c *RouteTrafficHourlyCreate) SetErrors(v int64) *RouteTrafficHourlyCreate {
	_c.mutation.SetErrors(v)
	return _c
}

// SetID sets the "id" field.
func (_c *RouteTrafficHourlyCreate) SetID(v string) *RouteTrafficHourlyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RouteTrafficHourlyCreate) SetNillableID(v *string) *RouteTrafficHourlyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the RouteTrafficHourlyMutation object of the builder.
func (_c *RouteTrafficHourlyCreate) Mutation() *RouteTrafficHourlyMutation {
	return _c.mutation
}

// Save creates the RouteTrafficHourly in the database.
func (_c *RouteTrafficHourlyCreate) Save(ctx context.Context) (*RouteTrafficHourly, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RouteTrafficHourlyCreate) SaveX(ctx context.Context) *RouteTrafficHourly {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RouteTrafficHourlyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RouteTrafficHourlyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RouteTrafficHourlyCreate) defaults() error {
	if _, ok := _c.mutation.ID(); !ok {
		if routetraffichourly.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized routetraffichourly.DefaultID (forgotten import ent/runtime?)")
		}
		v := routetraffichourly.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *RouteTrafficHourlyCreate) check() error {
	if _, ok := _c.mutation.OrgID(); !ok {
		return &ValidationError{Name: "org_id", err: errors.New(`ent: missing required field "RouteTrafficHourly.org_id"`)}
	}
	if v, ok := _c.mutation.OrgID(); ok {
		if err := routetraffichourly.OrgIDValidator(v); err != nil {
			return &ValidationError{Name: "org_id", err: fmt.Errorf(`ent: validator failed for field "RouteTrafficHourly.org_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RouteID(); !ok {
		return &ValidationError{Name: "route_id", err: errors.New(`ent: missing required field "RouteTrafficHourly.route_id"`)}
	}
	if v, ok := _c.mutation.RouteID(); ok {
		if err := routetraffichourly.RouteIDValidator(v); err != nil {
			return &ValidationError{Name: "route_id", err: fmt.Errorf(`ent: validator failed for field "RouteTrafficHourly.route_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Bucket(); !ok {
		return &ValidationError{Name: "bucket", err: errors.New(`ent: missing required field "RouteTrafficHourly.bucket"`)}
	}
	if _, ok := _c.mutation.BytesIn(); !ok {
		return &ValidationError{Name: "bytes_in", err: errors.New(`ent: missing required field "RouteTrafficHourly.bytes_in"`)}
	}
	if v, ok := _c.mutation.BytesIn(); ok {
		if err := routetraffichourly.BytesInValidator(v); err != nil {
			return &ValidationError{Name: "bytes_in", err: fmt.Errorf(`ent: validator failed for field "RouteTrafficHourly.bytes_in": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BytesOut(); !ok {
		return &ValidationError{Name: "bytes_out", err: errors.New(`ent: missing required field "RouteTrafficHourly.bytes_out"`)}
	}
	if v, ok := _c.mutation.BytesOut(); ok {
		if err := routetraffichourly.BytesOutValidator(v); err != nil {
			return &ValidationError{Name: "bytes_out", err: fmt.Errorf(`ent: validator failed for field "RouteTrafficHourly.bytes_out": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Connections(); !ok {
		return &ValidationError{Name: "connections", err: errors.New(`ent: missing required field "RouteTrafficHourly.connections"`)}
	}
	if v, ok := _c.mutation.Connections(); ok {
		if err := routetraffichourly.ConnectionsValidator(v); err != nil {
			return &ValidationError{Name: "connections", err: fmt.Errorf(`ent: validator failed for field "RouteTrafficHourly.connections": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Errors(); !ok {
		return &ValidationError{Name: "errors", err: errors.New(`ent: missing required field "RouteTrafficHourly.errors"`)}
	}
	if v, ok := _c.mutation.Errors(); ok {
		if err := routetraffichourly.ErrorsValidator(v); err != nil {
			return &ValidationError{Name: "errors", err: fmt.Errorf(`ent: validator failed for field "RouteTrafficHourly.errors": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := routetraffichourly.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "RouteTrafficHourly.id": %w`, err)}
		}
	}
	return nil
}

func (_c *RouteTrafficHourlyCreate) sqlSave(ctx context.Context) (*RouteTrafficHourly, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RouteTrafficHourly.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RouteTrafficHourlyCreate) createSpec() (*RouteTrafficHourly, *sqlgraph.CreateSpec) {
	var (
		_node = &RouteTrafficHourly{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(routetraffichourly.Table, sqlgraph.NewFieldSpec(routetraffichourly.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OrgID(); ok {
		_spec.SetField(routetraffichourly.FieldOrgID, field.TypeString, value)
		_node.OrgID = value
	}
	if value, ok := _c.mutation.RouteID(); ok {
		_spec.SetField(routetraffichourly.FieldRouteID, field.TypeString, value)
		_node.RouteID = value
	}
	if value, ok := _c.mutation.Bucket(); ok {
		_spec.SetField(routetraffichourly.FieldBucket, field.TypeTime, value)
		_node.Bucket = value
	}
	if value, ok := _c.mutation.BytesIn(); ok {
		_spec.SetField(routetraffichourly.FieldBytesIn, field.TypeInt64, value)
		_node.BytesIn = value
	}
	if value, ok := _c.mutation.BytesOut(); ok {
		_spec.SetField(routetraffichourly.FieldBytesOut, field.TypeInt64, value)
		_node.BytesOut = value
	}
	if value, ok := _c.mutation.Connections(); ok {
		_spec.SetField(routetraffichourly.FieldConnections, field.TypeInt64, value)
		_node.Connections = value
	}
	if value, ok := _c.mutation.Errors(); ok {
		_spec.SetField(routetraffichourly.FieldErrors, field.TypeInt64, value)
		_node.Errors = value
	}
	return _node, _spec
}

// RouteTrafficHourlyCreateBulk is the builder for creating many RouteTrafficHourly entities in bulk.
type RouteTrafficHourlyCreateBulk struct {
	config
	err      error
	builders []*RouteTrafficHourlyCreate
}

// Save creates the RouteTrafficHourly entities in the database.
func (_c *RouteTrafficHourlyCreateBulk) Save(ctx context.Context) ([]*RouteTrafficHourly, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RouteTrafficHourly, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RouteTrafficHourlyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RouteTrafficHourlyCreateBulk) SaveX(ctx context.Context) []*RouteTrafficHourly {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RouteTrafficHourlyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RouteTrafficHourlyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
