// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/felix-homelab/rpmgr/internal/store/ent/predicate"
	"github.com/felix-homelab/rpmgr/internal/store/ent/session"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *SessionUpdate) SetTokenHash(v []byte) *SessionUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *SessionUpdate) SetLastSeenAt(v time.Time) *SessionUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableLastSeenAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetIdleExpiresAt sets the "idle_expires_at" field.
func (_u *SessionUpdate) SetIdleExpiresAt(v time.Time) *SessionUpdate {
	_u.mutation.SetIdleExpiresAt(v)
	return _u
}

// SetNillableIdleExpiresAt sets the "idle_expires_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableIdleExpiresAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetIdleExpiresAt(*v)
	}
	return _u
}

// SetElevatedUntil sets the "elevated_until" field.
func (_u *SessionUpdate) SetElevatedUntil(v time.Time) *SessionUpdate {
	_u.mutation.SetElevatedUntil(v)
	return _u
}

// SetNillableElevatedUntil sets the "elevated_until" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableElevatedUntil(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetElevatedUntil(*v)
	}
	return _u
}

// ClearElevatedUntil clears the value of the "elevated_until" field.
func (_u *SessionUpdate) ClearElevatedUntil() *SessionUpdate {
	_u.mutation.ClearElevatedUntil()
	return _u
}

// SetAmr sets the "amr" field.
func (_u *SessionUpdate) SetAmr(v []string) *SessionUpdate {
	_u.mutation.SetAmr(v)
	return _u
}

// AppendAmr appends value to the "amr" field.
func (_u *SessionUpdate) AppendAmr(v []string) *SessionUpdate {
	_u.mutation.AppendAmr(v)
	return _u
}

// SetIP sets the "ip" field.
func (_u *SessionUpdate) SetIP(v string) *SessionUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableIP(v *string) *SessionUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *SessionUpdate) SetUserAgent(v string) *SessionUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableUserAgent(v *string) *SessionUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *SessionUpdate) SetRevokedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableRevokedAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *SessionUpdate) ClearRevokedAt() *SessionUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdate) Mutation() *SessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdate) check() error {
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := session.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "Session.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IP(); ok {
		if err := session.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Session.ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := session.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "Session.user_agent": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Session.user"`)
	}
	return nil
}

func (_u *SessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(session.FieldTokenHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(session.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IdleExpiresAt(); ok {
		_spec.SetField(session.FieldIdleExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ElevatedUntil(); ok {
		_spec.SetField(session.FieldElevatedUntil, field.TypeTime, value)
	}
	if _u.mutation.ElevatedUntilCleared() {
		_spec.ClearField(session.FieldElevatedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.Amr(); ok {
		_spec.SetField(session.FieldAmr, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAmr(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, session.FieldAmr, value)
		})
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(session.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(session.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(session.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(session.FieldRevokedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetTokenHash sets the "token_hash" field.
func (_u *SessionUpdateOne) SetTokenHash(v []byte) *SessionUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *SessionUpdateOne) SetLastSeenAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableLastSeenAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetIdleExpiresAt sets the "idle_expires_at" field.
func (_u *SessionUpdateOne) SetIdleExpiresAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetIdleExpiresAt(v)
	return _u
}

// SetNillableIdleExpiresAt sets the "idle_expires_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableIdleExpiresAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetIdleExpiresAt(*v)
	}
	return _u
}

// SetElevatedUntil sets the "elevated_until" field.
func (_u *SessionUpdateOne) SetElevatedUntil(v time.Time) *SessionUpdateOne {
	_u.mutation.SetElevatedUntil(v)
	return _u
}

// SetNillableElevatedUntil sets the "elevated_until" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableElevatedUntil(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetElevatedUntil(*v)
	}
	return _u
}

// ClearElevatedUntil clears the value of the "elevated_until" field.
func (_u *SessionUpdateOne) ClearElevatedUntil() *SessionUpdateOne {
	_u.mutation.ClearElevatedUntil()
	return _u
}

// SetAmr sets the "amr" field.
func (_u *SessionUpdateOne) SetAmr(v []string) *SessionUpdateOne {
	_u.mutation.SetAmr(v)
	return _u
}

// AppendAmr appends value to the "amr" field.
func (_u *SessionUpdateOne) AppendAmr(v []string) *SessionUpdateOne {
	_u.mutation.AppendAmr(v)
	return _u
}

// SetIP sets the "ip" field.
func (_u *SessionUpdateOne) SetIP(v string) *SessionUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableIP(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *SessionUpdateOne) SetUserAgent(v string) *SessionUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableUserAgent(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *SessionUpdateOne) SetRevokedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableRevokedAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *SessionUpdateOne) ClearRevokedAt() *SessionUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdateOne) Mutation() *SessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Session entity.
func (_u *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdateOne) check() error {
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := session.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "Session.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IP(); ok {
		if err := session.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Session.ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := session.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "Session.user_agent": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Session.user"`)
	}
	return nil
}

func (_u *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(session.FieldTokenHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(session.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IdleExpiresAt(); ok {
		_spec.SetField(session.FieldIdleExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ElevatedUntil(); ok {
		_spec.SetField(session.FieldElevatedUntil, field.TypeTime, value)
	}
	if _u.mutation.ElevatedUntilCleared() {
		_spec.ClearField(session.FieldElevatedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.Amr(); ok {
		_spec.SetField(session.FieldAmr, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAmr(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, session.FieldAmr, value)
		})
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(session.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(session.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(session.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(session.FieldRevokedAt, field.TypeTime)
	}
	_node = &Session{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
