// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/felix-homelab/rpmgr/spikes/s5/ent/healthcheck"
	"github.com/felix-homelab/rpmgr/spikes/s5/ent/routetarget"
)

// HealthCheckCreate is the builder for creating a HealthCheck entity.
type HealthCheckCreate struct {
	config
	mutation *HealthCheckMutation
	hooks    []Hook
}

// SetOrgID sets the "org_id" field.
func (_c *HealthCheckCreate) SetOrgID(v string) *HealthCheckCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *HealthCheckCreate) SetType(v healthcheck.Type) *HealthCheckCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (_c *HealthCheckCreate) SetIntervalSeconds(v int) *HealthCheckCreate {
	_c.mutation.SetIntervalSeconds(v)
	return _c
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (_c *HealthCheckCreate) SetNillableIntervalSeconds(v *int) *HealthCheckCreate {
	if v != nil {
		_c.SetIntervalSeconds(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *HealthCheckCreate) SetID(v string) *HealthCheckCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *HealthCheckCreate) SetNillableID(v *string) *HealthCheckCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddTargetIDs adds the "targets" edge to the RouteTarget entity by IDs.
func (_c *HealthCheckCreate) AddTargetIDs(ids ...string) *HealthCheckCreate {
	_c.mutation.AddTargetIDs(ids...)
	return _c
}

// AddTargets adds the "targets" edges to the RouteTarget entity.
func (_c *HealthCheckCreate) AddTargets(v ...*RouteTarget) *HealthCheckCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTargetIDs(ids...)
}

// Mutation returns the HealthCheckMutation object of the builder.
func (_c *HealthCheckCreate) Mutation() *HealthCheckMutation {
	return _c.mutation
}

// Save creates the HealthCheck in the database.
func (_c *HealthCheckCreate) Save(ctx context.Context) (*HealthCheck, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HealthCheckCreate) SaveX(ctx context.Context) *HealthCheck {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HealthCheckCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HealthCheckCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HealthCheckCreate) defaults() error {
	if _, ok := _c.mutation.IntervalSeconds(); !ok {
		v := healthcheck.DefaultIntervalSeconds
		_c.mutation.SetIntervalSeconds(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if healthcheck.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized healthcheck.DefaultID (forgotten import ent/runtime?)")
		}
		v := healthcheck.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *HealthCheckCreate) check() error {
	if _, ok := _c.mutation.OrgID(); !ok {
		return &ValidationError{Name: "org_id", err: errors.New(`ent: missing required field "HealthCheck.org_id"`)}
	}
	if v, ok := _c.mutation.OrgID(); ok {
		if err := healthcheck.OrgIDValidator(v); err != nil {
			return &ValidationError{Name: "org_id", err: fmt.Errorf(`ent: validator failed for field "HealthCheck.org_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "HealthCheck.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := healthcheck.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "HealthCheck.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IntervalSeconds(); !ok {
		return &ValidationError{Name: "interval_seconds", err: errors.New(`ent: missing required field "HealthCheck.interval_seconds"`)}
	}
	if v, ok := _c.mutation.IntervalSeconds(); ok {
		if err := healthcheck.IntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "interval_seconds", err: fmt.Errorf(`ent: validator failed for field "HealthCheck.interval_seconds": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := healthcheck.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "HealthCheck.id": %w`, err)}
		}
	}
	return nil
}

func (_c *HealthCheckCreate) sqlSave(ctx context.Context) (*HealthCheck, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected HealthCheck.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HealthCheckCreate) createSpec() (*HealthCheck, *sqlgraph.CreateSpec) {
	var (
		_node = &HealthCheck{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(healthcheck.Table, sqlgraph.NewFieldSpec(healthcheck.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OrgID(); ok {
		_spec.SetField(healthcheck.FieldOrgID, field.TypeString, value)
		_node.OrgID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(healthcheck.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.IntervalSeconds(); ok {
		_spec.SetField(healthcheck.FieldIntervalSeconds, field.TypeInt, value)
		_node.IntervalSeconds = value
	}
	if nodes := _c.mutation.TargetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   healthcheck.TargetsTable,
			Columns: []string{healthcheck.TargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(routetarget.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HealthCheckCreateBulk is the builder for creating many HealthCheck entities in bulk.
type HealthCheckCreateBulk struct {
	config
	err      error
	builders []*HealthCheckCreate
}

// Save creates the HealthCheck entities in the database.
func (_c *HealthCheckCreateBulk) Save(ctx context.Context) ([]*HealthCheck, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HealthCheck, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HealthCheckMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HealthCheckCreateBulk) SaveX(ctx context.Context) []*HealthCheck {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HealthCheckCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HealthCheckCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
