-- Create "agent_state" table
CREATE TABLE "agent_state" ("agent_id" character varying NOT NULL, "org_id" character varying NOT NULL, "boot_id" character varying NOT NULL DEFAULT '', "clock_offset_ms" bigint NOT NULL DEFAULT 0, "applied_db_epoch" character varying NOT NULL DEFAULT '', "applied_seq" bigint NOT NULL DEFAULT 0, "applied_hash" bytea NULL, "last_ack_at" timestamptz NULL, "pushed_db_epoch" character varying NOT NULL DEFAULT '', "pushed_seq" bigint NOT NULL DEFAULT 0, "pushed_hash" bytea NULL, "pushed_at" timestamptz NULL, "rejected_db_epoch" character varying NOT NULL DEFAULT '', "rejected_seq" bigint NOT NULL DEFAULT 0, "rejected_hash" bytea NULL, "last_rejection" jsonb NULL, PRIMARY KEY ("agent_id"), CONSTRAINT "agent_state_orgs" FOREIGN KEY ("org_id") REFERENCES "orgs" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "agentstate_org_id_agent_id" to table: "agent_state"
CREATE UNIQUE INDEX "agentstate_org_id_agent_id" ON "agent_state" ("org_id", "agent_id");
-- Create "compiled_snapshots" table
CREATE TABLE "compiled_snapshots" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "org_id" character varying NOT NULL, "agent_id" character varying NOT NULL, "db_epoch" character varying NOT NULL, "seq" bigint NOT NULL, "hash" bytea NOT NULL, "size_bytes" bigint NOT NULL, "payload" bytea NOT NULL, "signature" bytea NOT NULL, "key_id" character varying NOT NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "compiled_snapshots_orgs" FOREIGN KEY ("org_id") REFERENCES "orgs" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "compiledsnapshot_agent_id_id" to table: "compiled_snapshots"
CREATE INDEX "compiledsnapshot_agent_id_id" ON "compiled_snapshots" ("agent_id", "id");
-- Create index "compiledsnapshot_org_id_id" to table: "compiled_snapshots"
CREATE UNIQUE INDEX "compiledsnapshot_org_id_id" ON "compiled_snapshots" ("org_id", "id");
