-- Create "ca_keys" table
CREATE TABLE "ca_keys" ("id" character varying NOT NULL, "kind" character varying NOT NULL, "algorithm" character varying NOT NULL, "public_key" bytea NOT NULL, "certificate" bytea NOT NULL, "key_enc" bytea NULL, "not_before" timestamptz NOT NULL, "not_after" timestamptz NOT NULL, "status" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "secrets_meta" table
CREATE TABLE "secrets_meta" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "table_name" character varying NOT NULL, "row_id" character varying NOT NULL, "column_name" character varying NOT NULL, "kek_version" character varying NOT NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "secretmeta_table_name_row_id_column_name" to table: "secrets_meta"
CREATE UNIQUE INDEX "secretmeta_table_name_row_id_column_name" ON "secrets_meta" ("table_name", "row_id", "column_name");
-- Create "issued_certificates" table
CREATE TABLE "issued_certificates" ("serial" character varying NOT NULL, "org_id" character varying NULL, "subject_type" character varying NOT NULL, "subject_id" character varying NOT NULL, "spiffe_id" character varying NOT NULL, "pubkey_sha256" character varying NOT NULL, "not_before" timestamptz NOT NULL, "not_after" timestamptz NOT NULL, "first_seen_at" timestamptz NULL, "superseded_at" timestamptz NULL, "revoked_at" timestamptz NULL, "revocation_reason" character varying NOT NULL DEFAULT '', PRIMARY KEY ("serial"), CONSTRAINT "issued_certificates_orgs" FOREIGN KEY ("org_id") REFERENCES "orgs" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "issuedcertificate_subject_id" to table: "issued_certificates"
CREATE INDEX "issuedcertificate_subject_id" ON "issued_certificates" ("subject_id");
