// Code generated by ent, DO NOT EDIT.

package route

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/felix-homelab/rpmgr/spikes/s5/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Route {
	return predicate.Route(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Route {
	return predicate.Route(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Route {
	return predicate.Route(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Route {
	return predicate.Route(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Route {
	return predicate.Route(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Route {
	return predicate.Route(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Route {
	return predicate.Route(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Route {
	return predicate.Route(sql.FieldContainsFold(FieldID, id))
}

// OrgID applies equality check predicate on the "org_id" field. It's identical to OrgIDEQ.
func OrgID(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldOrgID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldName, v))
}

// GatewayGroupID applies equality check predicate on the "gateway_group_id" field. It's identical to GatewayGroupIDEQ.
func GatewayGroupID(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldGatewayGroupID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldEnabled, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldDescription, v))
}

// OrgIDEQ applies the EQ predicate on the "org_id" field.
func OrgIDEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldOrgID, v))
}

// OrgIDNEQ applies the NEQ predicate on the "org_id" field.
func OrgIDNEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldOrgID, v))
}

// OrgIDIn applies the In predicate on the "org_id" field.
func OrgIDIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldIn(FieldOrgID, vs...))
}

// OrgIDNotIn applies the NotIn predicate on the "org_id" field.
func OrgIDNotIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldNotIn(FieldOrgID, vs...))
}

// OrgIDGT applies the GT predicate on the "org_id" field.
func OrgIDGT(v string) predicate.Route {
	return predicate.Route(sql.FieldGT(FieldOrgID, v))
}

// OrgIDGTE applies the GTE predicate on the "org_id" field.
func OrgIDGTE(v string) predicate.Route {
	return predicate.Route(sql.FieldGTE(FieldOrgID, v))
}

// OrgIDLT applies the LT predicate on the "org_id" field.
func OrgIDLT(v string) predicate.Route {
	return predicate.Route(sql.FieldLT(FieldOrgID, v))
}

// OrgIDLTE applies the LTE predicate on the "org_id" field.
func OrgIDLTE(v string) predicate.Route {
	return predicate.Route(sql.FieldLTE(FieldOrgID, v))
}

// OrgIDContains applies the Contains predicate on the "org_id" field.
func OrgIDContains(v string) predicate.Route {
	return predicate.Route(sql.FieldContains(FieldOrgID, v))
}

// OrgIDHasPrefix applies the HasPrefix predicate on the "org_id" field.
func OrgIDHasPrefix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasPrefix(FieldOrgID, v))
}

// OrgIDHasSuffix applies the HasSuffix predicate on the "org_id" field.
func OrgIDHasSuffix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasSuffix(FieldOrgID, v))
}

// OrgIDEqualFold applies the EqualFold predicate on the "org_id" field.
func OrgIDEqualFold(v string) predicate.Route {
	return predicate.Route(sql.FieldEqualFold(FieldOrgID, v))
}

// OrgIDContainsFold applies the ContainsFold predicate on the "org_id" field.
func OrgIDContainsFold(v string) predicate.Route {
	return predicate.Route(sql.FieldContainsFold(FieldOrgID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Route {
	return predicate.Route(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Route {
	return predicate.Route(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Route {
	return predicate.Route(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Route {
	return predicate.Route(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Route {
	return predicate.Route(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Route {
	return predicate.Route(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Route {
	return predicate.Route(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Route {
	return predicate.Route(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Route {
	return predicate.Route(sql.FieldNotIn(FieldType, vs...))
}

// GatewayGroupIDEQ applies the EQ predicate on the "gateway_group_id" field.
func GatewayGroupIDEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldGatewayGroupID, v))
}

// GatewayGroupIDNEQ applies the NEQ predicate on the "gateway_group_id" field.
func GatewayGroupIDNEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldGatewayGroupID, v))
}

// GatewayGroupIDIn applies the In predicate on the "gateway_group_id" field.
func GatewayGroupIDIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldIn(FieldGatewayGroupID, vs...))
}

// GatewayGroupIDNotIn applies the NotIn predicate on the "gateway_group_id" field.
func GatewayGroupIDNotIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldNotIn(FieldGatewayGroupID, vs...))
}

// GatewayGroupIDGT applies the GT predicate on the "gateway_group_id" field.
func GatewayGroupIDGT(v string) predicate.Route {
	return predicate.Route(sql.FieldGT(FieldGatewayGroupID, v))
}

// GatewayGroupIDGTE applies the GTE predicate on the "gateway_group_id" field.
func GatewayGroupIDGTE(v string) predicate.Route {
	return predicate.Route(sql.FieldGTE(FieldGatewayGroupID, v))
}

// GatewayGroupIDLT applies the LT predicate on the "gateway_group_id" field.
func GatewayGroupIDLT(v string) predicate.Route {
	return predicate.Route(sql.FieldLT(FieldGatewayGroupID, v))
}

// GatewayGroupIDLTE applies the LTE predicate on the "gateway_group_id" field.
func GatewayGroupIDLTE(v string) predicate.Route {
	return predicate.Route(sql.FieldLTE(FieldGatewayGroupID, v))
}

// GatewayGroupIDContains applies the Contains predicate on the "gateway_group_id" field.
func GatewayGroupIDContains(v string) predicate.Route {
	return predicate.Route(sql.FieldContains(FieldGatewayGroupID, v))
}

// GatewayGroupIDHasPrefix applies the HasPrefix predicate on the "gateway_group_id" field.
func GatewayGroupIDHasPrefix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasPrefix(FieldGatewayGroupID, v))
}

// GatewayGroupIDHasSuffix applies the HasSuffix predicate on the "gateway_group_id" field.
func GatewayGroupIDHasSuffix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasSuffix(FieldGatewayGroupID, v))
}

// GatewayGroupIDEqualFold applies the EqualFold predicate on the "gateway_group_id" field.
func GatewayGroupIDEqualFold(v string) predicate.Route {
	return predicate.Route(sql.FieldEqualFold(FieldGatewayGroupID, v))
}

// GatewayGroupIDContainsFold applies the ContainsFold predicate on the "gateway_group_id" field.
func GatewayGroupIDContainsFold(v string) predicate.Route {
	return predicate.Route(sql.FieldContainsFold(FieldGatewayGroupID, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldEnabled, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Route {
	return predicate.Route(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Route {
	return predicate.Route(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Route {
	return predicate.Route(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Route {
	return predicate.Route(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Route {
	return predicate.Route(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Route {
	return predicate.Route(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Route {
	return predicate.Route(sql.FieldContainsFold(FieldDescription, v))
}

// HasGatewayGroup applies the HasEdge predicate on the "gateway_group" edge.
func HasGatewayGroup() predicate.Route {
	return predicate.Route(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GatewayGroupTable, GatewayGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGatewayGroupWith applies the HasEdge predicate on the "gateway_group" edge with a given conditions (other predicates).
func HasGatewayGroupWith(preds ...predicate.GatewayGroup) predicate.Route {
	return predicate.Route(func(s *sql.Selector) {
		step := newGatewayGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTargets applies the HasEdge predicate on the "targets" edge.
func HasTargets() predicate.Route {
	return predicate.Route(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TargetsTable, TargetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetsWith applies the HasEdge predicate on the "targets" edge with a given conditions (other predicates).
func HasTargetsWith(preds ...predicate.RouteTarget) predicate.Route {
	return predicate.Route(func(s *sql.Selector) {
		step := newTargetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Route) predicate.Route {
	return predicate.Route(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Route) predicate.Route {
	return predicate.Route(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Route) predicate.Route {
	return predicate.Route(sql.NotPredicates(p))
}
