// Code generated by ent, DO NOT EDIT.

package routetarget

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/felix-homelab/rpmgr/internal/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContainsFold(FieldID, id))
}

// OrgID applies equality check predicate on the "org_id" field. It's identical to OrgIDEQ.
func OrgID(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldOrgID, v))
}

// RouteID applies equality check predicate on the "route_id" field. It's identical to RouteIDEQ.
func RouteID(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldRouteID, v))
}

// ConnectorID applies equality check predicate on the "connector_id" field. It's identical to ConnectorIDEQ.
func ConnectorID(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldConnectorID, v))
}

// Host applies equality check predicate on the "host" field. It's identical to HostEQ.
func Host(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldHost, v))
}

// Port applies equality check predicate on the "port" field. It's identical to PortEQ.
func Port(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldPort, v))
}

// UnixPath applies equality check predicate on the "unix_path" field. It's identical to UnixPathEQ.
func UnixPath(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldUnixPath, v))
}

// TLSServerName applies equality check predicate on the "tls_server_name" field. It's identical to TLSServerNameEQ.
func TLSServerName(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldTLSServerName, v))
}

// TLSCaBundleID applies equality check predicate on the "tls_ca_bundle_id" field. It's identical to TLSCaBundleIDEQ.
func TLSCaBundleID(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldTLSCaBundleID, v))
}

// TLSSpkiSha256 applies equality check predicate on the "tls_spki_sha256" field. It's identical to TLSSpkiSha256EQ.
func TLSSpkiSha256(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldTLSSpkiSha256, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldWeight, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldPriority, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldEnabled, v))
}

// OrgIDEQ applies the EQ predicate on the "org_id" field.
func OrgIDEQ(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldOrgID, v))
}

// OrgIDNEQ applies the NEQ predicate on the "org_id" field.
func OrgIDNEQ(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNEQ(FieldOrgID, v))
}

// OrgIDIn applies the In predicate on the "org_id" field.
func OrgIDIn(vs ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldIn(FieldOrgID, vs...))
}

// OrgIDNotIn applies the NotIn predicate on the "org_id" field.
func OrgIDNotIn(vs ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNotIn(FieldOrgID, vs...))
}

// OrgIDGT applies the GT predicate on the "org_id" field.
func OrgIDGT(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGT(FieldOrgID, v))
}

// OrgIDGTE applies the GTE predicate on the "org_id" field.
func OrgIDGTE(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGTE(FieldOrgID, v))
}

// OrgIDLT applies the LT predicate on the "org_id" field.
func OrgIDLT(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLT(FieldOrgID, v))
}

// OrgIDLTE applies the LTE predicate on the "org_id" field.
func OrgIDLTE(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLTE(FieldOrgID, v))
}

// OrgIDContains applies the Contains predicate on the "org_id" field.
func OrgIDContains(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContains(FieldOrgID, v))
}

// OrgIDHasPrefix applies the HasPrefix predicate on the "org_id" field.
func OrgIDHasPrefix(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldHasPrefix(FieldOrgID, v))
}

// OrgIDHasSuffix applies the HasSuffix predicate on the "org_id" field.
func OrgIDHasSuffix(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldHasSuffix(FieldOrgID, v))
}

// OrgIDEqualFold applies the EqualFold predicate on the "org_id" field.
func OrgIDEqualFold(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEqualFold(FieldOrgID, v))
}

// OrgIDContainsFold applies the ContainsFold predicate on the "org_id" field.
func OrgIDContainsFold(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContainsFold(FieldOrgID, v))
}

// RouteIDEQ applies the EQ predicate on the "route_id" field.
func RouteIDEQ(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldRouteID, v))
}

// RouteIDNEQ applies the NEQ predicate on the "route_id" field.
func RouteIDNEQ(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNEQ(FieldRouteID, v))
}

// RouteIDIn applies the In predicate on the "route_id" field.
func RouteIDIn(vs ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldIn(FieldRouteID, vs...))
}

// RouteIDNotIn applies the NotIn predicate on the "route_id" field.
func RouteIDNotIn(vs ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNotIn(FieldRouteID, vs...))
}

// RouteIDGT applies the GT predicate on the "route_id" field.
func RouteIDGT(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGT(FieldRouteID, v))
}

// RouteIDGTE applies the GTE predicate on the "route_id" field.
func RouteIDGTE(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGTE(FieldRouteID, v))
}

// RouteIDLT applies the LT predicate on the "route_id" field.
func RouteIDLT(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLT(FieldRouteID, v))
}

// RouteIDLTE applies the LTE predicate on the "route_id" field.
func RouteIDLTE(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLTE(FieldRouteID, v))
}

// RouteIDContains applies the Contains predicate on the "route_id" field.
func RouteIDContains(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContains(FieldRouteID, v))
}

// RouteIDHasPrefix applies the HasPrefix predicate on the "route_id" field.
func RouteIDHasPrefix(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldHasPrefix(FieldRouteID, v))
}

// RouteIDHasSuffix applies the HasSuffix predicate on the "route_id" field.
func RouteIDHasSuffix(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldHasSuffix(FieldRouteID, v))
}

// RouteIDEqualFold applies the EqualFold predicate on the "route_id" field.
func RouteIDEqualFold(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEqualFold(FieldRouteID, v))
}

// RouteIDContainsFold applies the ContainsFold predicate on the "route_id" field.
func RouteIDContainsFold(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContainsFold(FieldRouteID, v))
}

// ConnectorIDEQ applies the EQ predicate on the "connector_id" field.
func ConnectorIDEQ(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldConnectorID, v))
}

// ConnectorIDNEQ applies the NEQ predicate on the "connector_id" field.
func ConnectorIDNEQ(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNEQ(FieldConnectorID, v))
}

// ConnectorIDIn applies the In predicate on the "connector_id" field.
func ConnectorIDIn(vs ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldIn(FieldConnectorID, vs...))
}

// ConnectorIDNotIn applies the NotIn predicate on the "connector_id" field.
func ConnectorIDNotIn(vs ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNotIn(FieldConnectorID, vs...))
}

// ConnectorIDGT applies the GT predicate on the "connector_id" field.
func ConnectorIDGT(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGT(FieldConnectorID, v))
}

// ConnectorIDGTE applies the GTE predicate on the "connector_id" field.
func ConnectorIDGTE(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGTE(FieldConnectorID, v))
}

// ConnectorIDLT applies the LT predicate on the "connector_id" field.
func ConnectorIDLT(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLT(FieldConnectorID, v))
}

// ConnectorIDLTE applies the LTE predicate on the "connector_id" field.
func ConnectorIDLTE(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLTE(FieldConnectorID, v))
}

// ConnectorIDContains applies the Contains predicate on the "connector_id" field.
func ConnectorIDContains(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContains(FieldConnectorID, v))
}

// ConnectorIDHasPrefix applies the HasPrefix predicate on the "connector_id" field.
func ConnectorIDHasPrefix(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldHasPrefix(FieldConnectorID, v))
}

// ConnectorIDHasSuffix applies the HasSuffix predicate on the "connector_id" field.
func ConnectorIDHasSuffix(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldHasSuffix(FieldConnectorID, v))
}

// ConnectorIDEqualFold applies the EqualFold predicate on the "connector_id" field.
func ConnectorIDEqualFold(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEqualFold(FieldConnectorID, v))
}

// ConnectorIDContainsFold applies the ContainsFold predicate on the "connector_id" field.
func ConnectorIDContainsFold(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContainsFold(FieldConnectorID, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNotIn(FieldKind, vs...))
}

// HostEQ applies the EQ predicate on the "host" field.
func HostEQ(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldHost, v))
}

// HostNEQ applies the NEQ predicate on the "host" field.
func HostNEQ(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNEQ(FieldHost, v))
}

// HostIn applies the In predicate on the "host" field.
func HostIn(vs ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldIn(FieldHost, vs...))
}

// HostNotIn applies the NotIn predicate on the "host" field.
func HostNotIn(vs ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNotIn(FieldHost, vs...))
}

// HostGT applies the GT predicate on the "host" field.
func HostGT(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGT(FieldHost, v))
}

// HostGTE applies the GTE predicate on the "host" field.
func HostGTE(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGTE(FieldHost, v))
}

// HostLT applies the LT predicate on the "host" field.
func HostLT(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLT(FieldHost, v))
}

// HostLTE applies the LTE predicate on the "host" field.
func HostLTE(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLTE(FieldHost, v))
}

// HostContains applies the Contains predicate on the "host" field.
func HostContains(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContains(FieldHost, v))
}

// HostHasPrefix applies the HasPrefix predicate on the "host" field.
func HostHasPrefix(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldHasPrefix(FieldHost, v))
}

// HostHasSuffix applies the HasSuffix predicate on the "host" field.
func HostHasSuffix(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldHasSuffix(FieldHost, v))
}

// HostEqualFold applies the EqualFold predicate on the "host" field.
func HostEqualFold(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEqualFold(FieldHost, v))
}

// HostContainsFold applies the ContainsFold predicate on the "host" field.
func HostContainsFold(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContainsFold(FieldHost, v))
}

// PortEQ applies the EQ predicate on the "port" field.
func PortEQ(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldPort, v))
}

// PortNEQ applies the NEQ predicate on the "port" field.
func PortNEQ(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNEQ(FieldPort, v))
}

// PortIn applies the In predicate on the "port" field.
func PortIn(vs ...int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldIn(FieldPort, vs...))
}

// PortNotIn applies the NotIn predicate on the "port" field.
func PortNotIn(vs ...int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNotIn(FieldPort, vs...))
}

// PortGT applies the GT predicate on the "port" field.
func PortGT(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGT(FieldPort, v))
}

// PortGTE applies the GTE predicate on the "port" field.
func PortGTE(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGTE(FieldPort, v))
}

// PortLT applies the LT predicate on the "port" field.
func PortLT(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLT(FieldPort, v))
}

// PortLTE applies the LTE predicate on the "port" field.
func PortLTE(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLTE(FieldPort, v))
}

// UnixPathEQ applies the EQ predicate on the "unix_path" field.
func UnixPathEQ(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldUnixPath, v))
}

// UnixPathNEQ applies the NEQ predicate on the "unix_path" field.
func UnixPathNEQ(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNEQ(FieldUnixPath, v))
}

// UnixPathIn applies the In predicate on the "unix_path" field.
func UnixPathIn(vs ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldIn(FieldUnixPath, vs...))
}

// UnixPathNotIn applies the NotIn predicate on the "unix_path" field.
func UnixPathNotIn(vs ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNotIn(FieldUnixPath, vs...))
}

// UnixPathGT applies the GT predicate on the "unix_path" field.
func UnixPathGT(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGT(FieldUnixPath, v))
}

// UnixPathGTE applies the GTE predicate on the "unix_path" field.
func UnixPathGTE(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGTE(FieldUnixPath, v))
}

// UnixPathLT applies the LT predicate on the "unix_path" field.
func UnixPathLT(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLT(FieldUnixPath, v))
}

// UnixPathLTE applies the LTE predicate on the "unix_path" field.
func UnixPathLTE(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLTE(FieldUnixPath, v))
}

// UnixPathContains applies the Contains predicate on the "unix_path" field.
func UnixPathContains(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContains(FieldUnixPath, v))
}

// UnixPathHasPrefix applies the HasPrefix predicate on the "unix_path" field.
func UnixPathHasPrefix(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldHasPrefix(FieldUnixPath, v))
}

// UnixPathHasSuffix applies the HasSuffix predicate on the "unix_path" field.
func UnixPathHasSuffix(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldHasSuffix(FieldUnixPath, v))
}

// UnixPathEqualFold applies the EqualFold predicate on the "unix_path" field.
func UnixPathEqualFold(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEqualFold(FieldUnixPath, v))
}

// UnixPathContainsFold applies the ContainsFold predicate on the "unix_path" field.
func UnixPathContainsFold(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContainsFold(FieldUnixPath, v))
}

// UpstreamProtocolEQ applies the EQ predicate on the "upstream_protocol" field.
func UpstreamProtocolEQ(v UpstreamProtocol) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldUpstreamProtocol, v))
}

// UpstreamProtocolNEQ applies the NEQ predicate on the "upstream_protocol" field.
func UpstreamProtocolNEQ(v UpstreamProtocol) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNEQ(FieldUpstreamProtocol, v))
}

// UpstreamProtocolIn applies the In predicate on the "upstream_protocol" field.
func UpstreamProtocolIn(vs ...UpstreamProtocol) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldIn(FieldUpstreamProtocol, vs...))
}

// UpstreamProtocolNotIn applies the NotIn predicate on the "upstream_protocol" field.
func UpstreamProtocolNotIn(vs ...UpstreamProtocol) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNotIn(FieldUpstreamProtocol, vs...))
}

// TLSServerNameEQ applies the EQ predicate on the "tls_server_name" field.
func TLSServerNameEQ(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldTLSServerName, v))
}

// TLSServerNameNEQ applies the NEQ predicate on the "tls_server_name" field.
func TLSServerNameNEQ(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNEQ(FieldTLSServerName, v))
}

// TLSServerNameIn applies the In predicate on the "tls_server_name" field.
func TLSServerNameIn(vs ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldIn(FieldTLSServerName, vs...))
}

// TLSServerNameNotIn applies the NotIn predicate on the "tls_server_name" field.
func TLSServerNameNotIn(vs ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNotIn(FieldTLSServerName, vs...))
}

// TLSServerNameGT applies the GT predicate on the "tls_server_name" field.
func TLSServerNameGT(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGT(FieldTLSServerName, v))
}

// TLSServerNameGTE applies the GTE predicate on the "tls_server_name" field.
func TLSServerNameGTE(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGTE(FieldTLSServerName, v))
}

// TLSServerNameLT applies the LT predicate on the "tls_server_name" field.
func TLSServerNameLT(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLT(FieldTLSServerName, v))
}

// TLSServerNameLTE applies the LTE predicate on the "tls_server_name" field.
func TLSServerNameLTE(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLTE(FieldTLSServerName, v))
}

// TLSServerNameContains applies the Contains predicate on the "tls_server_name" field.
func TLSServerNameContains(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContains(FieldTLSServerName, v))
}

// TLSServerNameHasPrefix applies the HasPrefix predicate on the "tls_server_name" field.
func TLSServerNameHasPrefix(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldHasPrefix(FieldTLSServerName, v))
}

// TLSServerNameHasSuffix applies the HasSuffix predicate on the "tls_server_name" field.
func TLSServerNameHasSuffix(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldHasSuffix(FieldTLSServerName, v))
}

// TLSServerNameEqualFold applies the EqualFold predicate on the "tls_server_name" field.
func TLSServerNameEqualFold(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEqualFold(FieldTLSServerName, v))
}

// TLSServerNameContainsFold applies the ContainsFold predicate on the "tls_server_name" field.
func TLSServerNameContainsFold(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContainsFold(FieldTLSServerName, v))
}

// TLSCaBundleIDEQ applies the EQ predicate on the "tls_ca_bundle_id" field.
func TLSCaBundleIDEQ(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldTLSCaBundleID, v))
}

// TLSCaBundleIDNEQ applies the NEQ predicate on the "tls_ca_bundle_id" field.
func TLSCaBundleIDNEQ(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNEQ(FieldTLSCaBundleID, v))
}

// TLSCaBundleIDIn applies the In predicate on the "tls_ca_bundle_id" field.
func TLSCaBundleIDIn(vs ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldIn(FieldTLSCaBundleID, vs...))
}

// TLSCaBundleIDNotIn applies the NotIn predicate on the "tls_ca_bundle_id" field.
func TLSCaBundleIDNotIn(vs ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNotIn(FieldTLSCaBundleID, vs...))
}

// TLSCaBundleIDGT applies the GT predicate on the "tls_ca_bundle_id" field.
func TLSCaBundleIDGT(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGT(FieldTLSCaBundleID, v))
}

// TLSCaBundleIDGTE applies the GTE predicate on the "tls_ca_bundle_id" field.
func TLSCaBundleIDGTE(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGTE(FieldTLSCaBundleID, v))
}

// TLSCaBundleIDLT applies the LT predicate on the "tls_ca_bundle_id" field.
func TLSCaBundleIDLT(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLT(FieldTLSCaBundleID, v))
}

// TLSCaBundleIDLTE applies the LTE predicate on the "tls_ca_bundle_id" field.
func TLSCaBundleIDLTE(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLTE(FieldTLSCaBundleID, v))
}

// TLSCaBundleIDContains applies the Contains predicate on the "tls_ca_bundle_id" field.
func TLSCaBundleIDContains(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContains(FieldTLSCaBundleID, v))
}

// TLSCaBundleIDHasPrefix applies the HasPrefix predicate on the "tls_ca_bundle_id" field.
func TLSCaBundleIDHasPrefix(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldHasPrefix(FieldTLSCaBundleID, v))
}

// TLSCaBundleIDHasSuffix applies the HasSuffix predicate on the "tls_ca_bundle_id" field.
func TLSCaBundleIDHasSuffix(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldHasSuffix(FieldTLSCaBundleID, v))
}

// TLSCaBundleIDIsNil applies the IsNil predicate on the "tls_ca_bundle_id" field.
func TLSCaBundleIDIsNil() predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldIsNull(FieldTLSCaBundleID))
}

// TLSCaBundleIDNotNil applies the NotNil predicate on the "tls_ca_bundle_id" field.
func TLSCaBundleIDNotNil() predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNotNull(FieldTLSCaBundleID))
}

// TLSCaBundleIDEqualFold applies the EqualFold predicate on the "tls_ca_bundle_id" field.
func TLSCaBundleIDEqualFold(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEqualFold(FieldTLSCaBundleID, v))
}

// TLSCaBundleIDContainsFold applies the ContainsFold predicate on the "tls_ca_bundle_id" field.
func TLSCaBundleIDContainsFold(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContainsFold(FieldTLSCaBundleID, v))
}

// TLSSpkiSha256EQ applies the EQ predicate on the "tls_spki_sha256" field.
func TLSSpkiSha256EQ(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldTLSSpkiSha256, v))
}

// TLSSpkiSha256NEQ applies the NEQ predicate on the "tls_spki_sha256" field.
func TLSSpkiSha256NEQ(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNEQ(FieldTLSSpkiSha256, v))
}

// TLSSpkiSha256In applies the In predicate on the "tls_spki_sha256" field.
func TLSSpkiSha256In(vs ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldIn(FieldTLSSpkiSha256, vs...))
}

// TLSSpkiSha256NotIn applies the NotIn predicate on the "tls_spki_sha256" field.
func TLSSpkiSha256NotIn(vs ...string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNotIn(FieldTLSSpkiSha256, vs...))
}

// TLSSpkiSha256GT applies the GT predicate on the "tls_spki_sha256" field.
func TLSSpkiSha256GT(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGT(FieldTLSSpkiSha256, v))
}

// TLSSpkiSha256GTE applies the GTE predicate on the "tls_spki_sha256" field.
func TLSSpkiSha256GTE(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGTE(FieldTLSSpkiSha256, v))
}

// TLSSpkiSha256LT applies the LT predicate on the "tls_spki_sha256" field.
func TLSSpkiSha256LT(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLT(FieldTLSSpkiSha256, v))
}

// TLSSpkiSha256LTE applies the LTE predicate on the "tls_spki_sha256" field.
func TLSSpkiSha256LTE(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLTE(FieldTLSSpkiSha256, v))
}

// TLSSpkiSha256Contains applies the Contains predicate on the "tls_spki_sha256" field.
func TLSSpkiSha256Contains(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContains(FieldTLSSpkiSha256, v))
}

// TLSSpkiSha256HasPrefix applies the HasPrefix predicate on the "tls_spki_sha256" field.
func TLSSpkiSha256HasPrefix(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldHasPrefix(FieldTLSSpkiSha256, v))
}

// TLSSpkiSha256HasSuffix applies the HasSuffix predicate on the "tls_spki_sha256" field.
func TLSSpkiSha256HasSuffix(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldHasSuffix(FieldTLSSpkiSha256, v))
}

// TLSSpkiSha256EqualFold applies the EqualFold predicate on the "tls_spki_sha256" field.
func TLSSpkiSha256EqualFold(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEqualFold(FieldTLSSpkiSha256, v))
}

// TLSSpkiSha256ContainsFold applies the ContainsFold predicate on the "tls_spki_sha256" field.
func TLSSpkiSha256ContainsFold(v string) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldContainsFold(FieldTLSSpkiSha256, v))
}

// ProxyProtocolEQ applies the EQ predicate on the "proxy_protocol" field.
func ProxyProtocolEQ(v ProxyProtocol) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldProxyProtocol, v))
}

// ProxyProtocolNEQ applies the NEQ predicate on the "proxy_protocol" field.
func ProxyProtocolNEQ(v ProxyProtocol) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNEQ(FieldProxyProtocol, v))
}

// ProxyProtocolIn applies the In predicate on the "proxy_protocol" field.
func ProxyProtocolIn(vs ...ProxyProtocol) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldIn(FieldProxyProtocol, vs...))
}

// ProxyProtocolNotIn applies the NotIn predicate on the "proxy_protocol" field.
func ProxyProtocolNotIn(vs ...ProxyProtocol) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNotIn(FieldProxyProtocol, vs...))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLTE(FieldWeight, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldLTE(FieldPriority, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.RouteTarget {
	return predicate.RouteTarget(sql.FieldNEQ(FieldEnabled, v))
}

// HasRoute applies the HasEdge predicate on the "route" edge.
func HasRoute() predicate.RouteTarget {
	return predicate.RouteTarget(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RouteTable, RouteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRouteWith applies the HasEdge predicate on the "route" edge with a given conditions (other predicates).
func HasRouteWith(preds ...predicate.Route) predicate.RouteTarget {
	return predicate.RouteTarget(func(s *sql.Selector) {
		step := newRouteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasConnector applies the HasEdge predicate on the "connector" edge.
func HasConnector() predicate.RouteTarget {
	return predicate.RouteTarget(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ConnectorTable, ConnectorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConnectorWith applies the HasEdge predicate on the "connector" edge with a given conditions (other predicates).
func HasConnectorWith(preds ...predicate.Connector) predicate.RouteTarget {
	return predicate.RouteTarget(func(s *sql.Selector) {
		step := newConnectorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCaBundle applies the HasEdge predicate on the "ca_bundle" edge.
func HasCaBundle() predicate.RouteTarget {
	return predicate.RouteTarget(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, CaBundleTable, CaBundleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCaBundleWith applies the HasEdge predicate on the "ca_bundle" edge with a given conditions (other predicates).
func HasCaBundleWith(preds ...predicate.CABundle) predicate.RouteTarget {
	return predicate.RouteTarget(func(s *sql.Selector) {
		step := newCaBundleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RouteTarget) predicate.RouteTarget {
	return predicate.RouteTarget(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RouteTarget) predicate.RouteTarget {
	return predicate.RouteTarget(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RouteTarget) predicate.RouteTarget {
	return predicate.RouteTarget(sql.NotPredicates(p))
}
