// Code generated by ent, DO NOT EDIT.

package portpool

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the portpool type in the database.
	Label = "port_pool"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrgID holds the string denoting the org_id field in the database.
	FieldOrgID = "org_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldGatewayGroupID holds the string denoting the gateway_group_id field in the database.
	FieldGatewayGroupID = "gateway_group_id"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldPortFrom holds the string denoting the port_from field in the database.
	FieldPortFrom = "port_from"
	// FieldPortTo holds the string denoting the port_to field in the database.
	FieldPortTo = "port_to"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// Table holds the table name of the portpool in the database.
	Table = "port_pools"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "port_pools"
	// GroupInverseTable is the table name for the GatewayGroup entity.
	// It exists in this package in order to avoid circular dependency with the "gatewaygroup" package.
	GroupInverseTable = "gateway_groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "gateway_group_id"
)

// Columns holds all SQL columns for portpool fields.
var Columns = []string{
	FieldID,
	FieldOrgID,
	FieldVersion,
	FieldGatewayGroupID,
	FieldProtocol,
	FieldPortFrom,
	FieldPortTo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/felix-homelab/rpmgr/internal/store/ent/runtime"
var (
	Hooks        [3]ent.Hook
	Interceptors [1]ent.Interceptor
	Policy       ent.Policy
	// OrgIDValidator is a validator for the "org_id" field. It is called by the builders before save.
	OrgIDValidator func(string) error
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int64
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(int64) error
	// GatewayGroupIDValidator is a validator for the "gateway_group_id" field. It is called by the builders before save.
	GatewayGroupIDValidator func(string) error
	// PortFromValidator is a validator for the "port_from" field. It is called by the builders before save.
	PortFromValidator func(int) error
	// PortToValidator is a validator for the "port_to" field. It is called by the builders before save.
	PortToValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Protocol defines the type for the "protocol" enum field.
type Protocol string

// Protocol values.
const (
	ProtocolTCP Protocol = "tcp"
	ProtocolUDP Protocol = "udp"
)

func (pr Protocol) String() string {
	return string(pr)
}

// ProtocolValidator is a validator for the "protocol" field enum values. It is called by the builders before save.
func ProtocolValidator(pr Protocol) error {
	switch pr {
	case ProtocolTCP, ProtocolUDP:
		return nil
	default:
		return fmt.Errorf("portpool: invalid enum value for protocol field: %q", pr)
	}
}

// OrderOption defines the ordering options for the PortPool queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrgID orders the results by the org_id field.
func ByOrgID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrgID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByGatewayGroupID orders the results by the gateway_group_id field.
func ByGatewayGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGatewayGroupID, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// ByPortFrom orders the results by the port_from field.
func ByPortFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPortFrom, opts...).ToFunc()
}

// ByPortTo orders the results by the port_to field.
func ByPortTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPortTo, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
	)
}
