// Code generated by ent, DO NOT EDIT.

package cakey

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the cakey type in the database.
	Label = "ca_key"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldAlgorithm holds the string denoting the algorithm field in the database.
	FieldAlgorithm = "algorithm"
	// FieldPublicKey holds the string denoting the public_key field in the database.
	FieldPublicKey = "public_key"
	// FieldCertificate holds the string denoting the certificate field in the database.
	FieldCertificate = "certificate"
	// FieldKeyEnc holds the string denoting the key_enc field in the database.
	FieldKeyEnc = "key_enc"
	// FieldNotBefore holds the string denoting the not_before field in the database.
	FieldNotBefore = "not_before"
	// FieldNotAfter holds the string denoting the not_after field in the database.
	FieldNotAfter = "not_after"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the cakey in the database.
	Table = "ca_keys"
)

// Columns holds all SQL columns for cakey fields.
var Columns = []string{
	FieldID,
	FieldKind,
	FieldAlgorithm,
	FieldPublicKey,
	FieldCertificate,
	FieldKeyEnc,
	FieldNotBefore,
	FieldNotAfter,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/felix-homelab/rpmgr/internal/store/ent/runtime"
var (
	Hooks        [2]ent.Hook
	Interceptors [1]ent.Interceptor
	Policy       ent.Policy
	// AlgorithmValidator is a validator for the "algorithm" field. It is called by the builders before save.
	AlgorithmValidator func(string) error
	// PublicKeyValidator is a validator for the "public_key" field. It is called by the builders before save.
	PublicKeyValidator func([]byte) error
	// CertificateValidator is a validator for the "certificate" field. It is called by the builders before save.
	CertificateValidator func([]byte) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindRoot            Kind = "root"
	KindIntermediate    Kind = "intermediate"
	KindConfigSigning   Kind = "config_signing"
	KindAuditCheckpoint Kind = "audit_checkpoint"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindRoot, KindIntermediate, KindConfigSigning, KindAuditCheckpoint:
		return nil
	default:
		return fmt.Errorf("cakey: invalid enum value for kind field: %q", k)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusNext    Status = "next"
	StatusActive  Status = "active"
	StatusRetired Status = "retired"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusNext, StatusActive, StatusRetired:
		return nil
	default:
		return fmt.Errorf("cakey: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the CAKey queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByAlgorithm orders the results by the algorithm field.
func ByAlgorithm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlgorithm, opts...).ToFunc()
}

// ByNotBefore orders the results by the not_before field.
func ByNotBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotBefore, opts...).ToFunc()
}

// ByNotAfter orders the results by the not_after field.
func ByNotAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotAfter, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}
