// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Connector is the predicate function for connector builders.
type Connector func(*sql.Selector)

// GatewayGroup is the predicate function for gatewaygroup builders.
type GatewayGroup func(*sql.Selector)

// HealthCheck is the predicate function for healthcheck builders.
type HealthCheck func(*sql.Selector)

// Org is the predicate function for org builders.
type Org func(*sql.Selector)

// Route is the predicate function for route builders.
type Route func(*sql.Selector)

// RouteTarget is the predicate function for routetarget builders.
type RouteTarget func(*sql.Selector)
