// SPDX-License-Identifier: Apache-2.0

// Command s3summary turns the gateway's records of a real-client run (results/real-clients/
// <client>/) into one Markdown summary: the routing decision for every ClientHello, and what the
// handlers behind the router served.
package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/felix-homelab/rpmgr/spikes/s3/mux"
)

func main() {
	dir := flag.String("results", "", "results/real-clients directory")
	flag.Parse()
	clients, err := os.ReadDir(*dir)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("# S3 real-client run: what the gateway saw")
	fmt.Println()
	fmt.Println("Generated by `cmd/s3summary` from `tcp-events.jsonl` and `handler-notes.txt`. \"Via\":")
	fmt.Println("`direct` = loopback in one segment; `relay` = through the segmenting relay (≤ 1448-byte")
	fmt.Println("segments, 2 ms apart).")
	fmt.Println()
	fmt.Println("| Client | Via | SNI | ALPN offered | Decision | ClientHello bytes | Records | Reads | Key shares | n |")
	fmt.Println("|---|---|---|---|---|---|---|---|---|---|")
	var notes []string
	for _, c := range clients {
		if !c.IsDir() {
			continue
		}
		rows := map[string]int{}
		var order []string
		f, err := os.Open(filepath.Join(*dir, c.Name(), "tcp-events.jsonl"))
		if err != nil {
			continue
		}
		sc := bufio.NewScanner(f)
		for sc.Scan() {
			var ev mux.Event
			if err := json.Unmarshal(sc.Bytes(), &ev); err != nil {
				log.Fatal(err)
			}
			via := "direct"
			if strings.HasPrefix(ev.Remote, "127.0.0.2:") {
				via = "relay"
			}
			sni := ev.SNI
			if sni == "" {
				sni = "(none)"
			}
			dec := string(ev.Decision)
			if ev.Error != "" {
				dec += ": " + ev.Error
			}
			row := fmt.Sprintf("| %s | %s | `%s` | %s | %s | %d | %d | %d | %s |", c.Name(), via, sni,
				strings.Join(ev.ALPN, ", "), dec, ev.HelloSize, ev.Records, ev.Reads,
				strings.Join(ev.KeyShareGroups, " + "))
			if rows[row] == 0 {
				order = append(order, row)
			}
			rows[row]++
		}
		f.Close()
		for _, r := range order {
			fmt.Printf("%s %d |\n", r, rows[r])
		}
		if b, err := os.ReadFile(filepath.Join(*dir, c.Name(), "handler-notes.txt")); err == nil {
			counts := map[string]int{}
			ua := regexp.MustCompile(` ua=".*"$`)
			for _, l := range strings.Split(strings.TrimSpace(string(b)), "\n") {
				if l != "" {
					counts[c.Name()+": "+ua.ReplaceAllString(l, "")]++
				}
			}
			for k, n := range counts {
				notes = append(notes, fmt.Sprintf("- %s (×%d)", k, n))
			}
		}
	}
	sort.Strings(notes)
	fmt.Println()
	fmt.Println("## What the handlers behind the router served")
	fmt.Println()
	for _, n := range notes {
		fmt.Println(n)
	}
}
