// Code generated by ent, DO NOT EDIT.

package routehostname

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/felix-homelab/rpmgr/internal/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldLTE(FieldID, id))
}

// OrgID applies equality check predicate on the "org_id" field. It's identical to OrgIDEQ.
func OrgID(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEQ(FieldOrgID, v))
}

// RouteID applies equality check predicate on the "route_id" field. It's identical to RouteIDEQ.
func RouteID(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEQ(FieldRouteID, v))
}

// GatewayGroupID applies equality check predicate on the "gateway_group_id" field. It's identical to GatewayGroupIDEQ.
func GatewayGroupID(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEQ(FieldGatewayGroupID, v))
}

// Hostname applies equality check predicate on the "hostname" field. It's identical to HostnameEQ.
func Hostname(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEQ(FieldHostname, v))
}

// PathPrefix applies equality check predicate on the "path_prefix" field. It's identical to PathPrefixEQ.
func PathPrefix(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEQ(FieldPathPrefix, v))
}

// DomainID applies equality check predicate on the "domain_id" field. It's identical to DomainIDEQ.
func DomainID(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEQ(FieldDomainID, v))
}

// OrgIDEQ applies the EQ predicate on the "org_id" field.
func OrgIDEQ(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEQ(FieldOrgID, v))
}

// OrgIDNEQ applies the NEQ predicate on the "org_id" field.
func OrgIDNEQ(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldNEQ(FieldOrgID, v))
}

// OrgIDIn applies the In predicate on the "org_id" field.
func OrgIDIn(vs ...string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldIn(FieldOrgID, vs...))
}

// OrgIDNotIn applies the NotIn predicate on the "org_id" field.
func OrgIDNotIn(vs ...string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldNotIn(FieldOrgID, vs...))
}

// OrgIDGT applies the GT predicate on the "org_id" field.
func OrgIDGT(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldGT(FieldOrgID, v))
}

// OrgIDGTE applies the GTE predicate on the "org_id" field.
func OrgIDGTE(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldGTE(FieldOrgID, v))
}

// OrgIDLT applies the LT predicate on the "org_id" field.
func OrgIDLT(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldLT(FieldOrgID, v))
}

// OrgIDLTE applies the LTE predicate on the "org_id" field.
func OrgIDLTE(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldLTE(FieldOrgID, v))
}

// OrgIDContains applies the Contains predicate on the "org_id" field.
func OrgIDContains(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldContains(FieldOrgID, v))
}

// OrgIDHasPrefix applies the HasPrefix predicate on the "org_id" field.
func OrgIDHasPrefix(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldHasPrefix(FieldOrgID, v))
}

// OrgIDHasSuffix applies the HasSuffix predicate on the "org_id" field.
func OrgIDHasSuffix(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldHasSuffix(FieldOrgID, v))
}

// OrgIDEqualFold applies the EqualFold predicate on the "org_id" field.
func OrgIDEqualFold(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEqualFold(FieldOrgID, v))
}

// OrgIDContainsFold applies the ContainsFold predicate on the "org_id" field.
func OrgIDContainsFold(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldContainsFold(FieldOrgID, v))
}

// RouteIDEQ applies the EQ predicate on the "route_id" field.
func RouteIDEQ(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEQ(FieldRouteID, v))
}

// RouteIDNEQ applies the NEQ predicate on the "route_id" field.
func RouteIDNEQ(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldNEQ(FieldRouteID, v))
}

// RouteIDIn applies the In predicate on the "route_id" field.
func RouteIDIn(vs ...string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldIn(FieldRouteID, vs...))
}

// RouteIDNotIn applies the NotIn predicate on the "route_id" field.
func RouteIDNotIn(vs ...string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldNotIn(FieldRouteID, vs...))
}

// RouteIDGT applies the GT predicate on the "route_id" field.
func RouteIDGT(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldGT(FieldRouteID, v))
}

// RouteIDGTE applies the GTE predicate on the "route_id" field.
func RouteIDGTE(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldGTE(FieldRouteID, v))
}

// RouteIDLT applies the LT predicate on the "route_id" field.
func RouteIDLT(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldLT(FieldRouteID, v))
}

// RouteIDLTE applies the LTE predicate on the "route_id" field.
func RouteIDLTE(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldLTE(FieldRouteID, v))
}

// RouteIDContains applies the Contains predicate on the "route_id" field.
func RouteIDContains(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldContains(FieldRouteID, v))
}

// RouteIDHasPrefix applies the HasPrefix predicate on the "route_id" field.
func RouteIDHasPrefix(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldHasPrefix(FieldRouteID, v))
}

// RouteIDHasSuffix applies the HasSuffix predicate on the "route_id" field.
func RouteIDHasSuffix(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldHasSuffix(FieldRouteID, v))
}

// RouteIDEqualFold applies the EqualFold predicate on the "route_id" field.
func RouteIDEqualFold(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEqualFold(FieldRouteID, v))
}

// RouteIDContainsFold applies the ContainsFold predicate on the "route_id" field.
func RouteIDContainsFold(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldContainsFold(FieldRouteID, v))
}

// GatewayGroupIDEQ applies the EQ predicate on the "gateway_group_id" field.
func GatewayGroupIDEQ(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEQ(FieldGatewayGroupID, v))
}

// GatewayGroupIDNEQ applies the NEQ predicate on the "gateway_group_id" field.
func GatewayGroupIDNEQ(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldNEQ(FieldGatewayGroupID, v))
}

// GatewayGroupIDIn applies the In predicate on the "gateway_group_id" field.
func GatewayGroupIDIn(vs ...string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldIn(FieldGatewayGroupID, vs...))
}

// GatewayGroupIDNotIn applies the NotIn predicate on the "gateway_group_id" field.
func GatewayGroupIDNotIn(vs ...string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldNotIn(FieldGatewayGroupID, vs...))
}

// GatewayGroupIDGT applies the GT predicate on the "gateway_group_id" field.
func GatewayGroupIDGT(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldGT(FieldGatewayGroupID, v))
}

// GatewayGroupIDGTE applies the GTE predicate on the "gateway_group_id" field.
func GatewayGroupIDGTE(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldGTE(FieldGatewayGroupID, v))
}

// GatewayGroupIDLT applies the LT predicate on the "gateway_group_id" field.
func GatewayGroupIDLT(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldLT(FieldGatewayGroupID, v))
}

// GatewayGroupIDLTE applies the LTE predicate on the "gateway_group_id" field.
func GatewayGroupIDLTE(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldLTE(FieldGatewayGroupID, v))
}

// GatewayGroupIDContains applies the Contains predicate on the "gateway_group_id" field.
func GatewayGroupIDContains(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldContains(FieldGatewayGroupID, v))
}

// GatewayGroupIDHasPrefix applies the HasPrefix predicate on the "gateway_group_id" field.
func GatewayGroupIDHasPrefix(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldHasPrefix(FieldGatewayGroupID, v))
}

// GatewayGroupIDHasSuffix applies the HasSuffix predicate on the "gateway_group_id" field.
func GatewayGroupIDHasSuffix(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldHasSuffix(FieldGatewayGroupID, v))
}

// GatewayGroupIDEqualFold applies the EqualFold predicate on the "gateway_group_id" field.
func GatewayGroupIDEqualFold(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEqualFold(FieldGatewayGroupID, v))
}

// GatewayGroupIDContainsFold applies the ContainsFold predicate on the "gateway_group_id" field.
func GatewayGroupIDContainsFold(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldContainsFold(FieldGatewayGroupID, v))
}

// RouteTypeEQ applies the EQ predicate on the "route_type" field.
func RouteTypeEQ(v RouteType) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEQ(FieldRouteType, v))
}

// RouteTypeNEQ applies the NEQ predicate on the "route_type" field.
func RouteTypeNEQ(v RouteType) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldNEQ(FieldRouteType, v))
}

// RouteTypeIn applies the In predicate on the "route_type" field.
func RouteTypeIn(vs ...RouteType) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldIn(FieldRouteType, vs...))
}

// RouteTypeNotIn applies the NotIn predicate on the "route_type" field.
func RouteTypeNotIn(vs ...RouteType) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldNotIn(FieldRouteType, vs...))
}

// HostnameEQ applies the EQ predicate on the "hostname" field.
func HostnameEQ(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEQ(FieldHostname, v))
}

// HostnameNEQ applies the NEQ predicate on the "hostname" field.
func HostnameNEQ(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldNEQ(FieldHostname, v))
}

// HostnameIn applies the In predicate on the "hostname" field.
func HostnameIn(vs ...string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldIn(FieldHostname, vs...))
}

// HostnameNotIn applies the NotIn predicate on the "hostname" field.
func HostnameNotIn(vs ...string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldNotIn(FieldHostname, vs...))
}

// HostnameGT applies the GT predicate on the "hostname" field.
func HostnameGT(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldGT(FieldHostname, v))
}

// HostnameGTE applies the GTE predicate on the "hostname" field.
func HostnameGTE(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldGTE(FieldHostname, v))
}

// HostnameLT applies the LT predicate on the "hostname" field.
func HostnameLT(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldLT(FieldHostname, v))
}

// HostnameLTE applies the LTE predicate on the "hostname" field.
func HostnameLTE(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldLTE(FieldHostname, v))
}

// HostnameContains applies the Contains predicate on the "hostname" field.
func HostnameContains(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldContains(FieldHostname, v))
}

// HostnameHasPrefix applies the HasPrefix predicate on the "hostname" field.
func HostnameHasPrefix(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldHasPrefix(FieldHostname, v))
}

// HostnameHasSuffix applies the HasSuffix predicate on the "hostname" field.
func HostnameHasSuffix(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldHasSuffix(FieldHostname, v))
}

// HostnameEqualFold applies the EqualFold predicate on the "hostname" field.
func HostnameEqualFold(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEqualFold(FieldHostname, v))
}

// HostnameContainsFold applies the ContainsFold predicate on the "hostname" field.
func HostnameContainsFold(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldContainsFold(FieldHostname, v))
}

// PathPrefixEQ applies the EQ predicate on the "path_prefix" field.
func PathPrefixEQ(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEQ(FieldPathPrefix, v))
}

// PathPrefixNEQ applies the NEQ predicate on the "path_prefix" field.
func PathPrefixNEQ(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldNEQ(FieldPathPrefix, v))
}

// PathPrefixIn applies the In predicate on the "path_prefix" field.
func PathPrefixIn(vs ...string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldIn(FieldPathPrefix, vs...))
}

// PathPrefixNotIn applies the NotIn predicate on the "path_prefix" field.
func PathPrefixNotIn(vs ...string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldNotIn(FieldPathPrefix, vs...))
}

// PathPrefixGT applies the GT predicate on the "path_prefix" field.
func PathPrefixGT(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldGT(FieldPathPrefix, v))
}

// PathPrefixGTE applies the GTE predicate on the "path_prefix" field.
func PathPrefixGTE(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldGTE(FieldPathPrefix, v))
}

// PathPrefixLT applies the LT predicate on the "path_prefix" field.
func PathPrefixLT(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldLT(FieldPathPrefix, v))
}

// PathPrefixLTE applies the LTE predicate on the "path_prefix" field.
func PathPrefixLTE(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldLTE(FieldPathPrefix, v))
}

// PathPrefixContains applies the Contains predicate on the "path_prefix" field.
func PathPrefixContains(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldContains(FieldPathPrefix, v))
}

// PathPrefixHasPrefix applies the HasPrefix predicate on the "path_prefix" field.
func PathPrefixHasPrefix(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldHasPrefix(FieldPathPrefix, v))
}

// PathPrefixHasSuffix applies the HasSuffix predicate on the "path_prefix" field.
func PathPrefixHasSuffix(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldHasSuffix(FieldPathPrefix, v))
}

// PathPrefixEqualFold applies the EqualFold predicate on the "path_prefix" field.
func PathPrefixEqualFold(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEqualFold(FieldPathPrefix, v))
}

// PathPrefixContainsFold applies the ContainsFold predicate on the "path_prefix" field.
func PathPrefixContainsFold(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldContainsFold(FieldPathPrefix, v))
}

// DomainIDEQ applies the EQ predicate on the "domain_id" field.
func DomainIDEQ(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEQ(FieldDomainID, v))
}

// DomainIDNEQ applies the NEQ predicate on the "domain_id" field.
func DomainIDNEQ(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldNEQ(FieldDomainID, v))
}

// DomainIDIn applies the In predicate on the "domain_id" field.
func DomainIDIn(vs ...string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldIn(FieldDomainID, vs...))
}

// DomainIDNotIn applies the NotIn predicate on the "domain_id" field.
func DomainIDNotIn(vs ...string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldNotIn(FieldDomainID, vs...))
}

// DomainIDGT applies the GT predicate on the "domain_id" field.
func DomainIDGT(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldGT(FieldDomainID, v))
}

// DomainIDGTE applies the GTE predicate on the "domain_id" field.
func DomainIDGTE(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldGTE(FieldDomainID, v))
}

// DomainIDLT applies the LT predicate on the "domain_id" field.
func DomainIDLT(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldLT(FieldDomainID, v))
}

// DomainIDLTE applies the LTE predicate on the "domain_id" field.
func DomainIDLTE(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldLTE(FieldDomainID, v))
}

// DomainIDContains applies the Contains predicate on the "domain_id" field.
func DomainIDContains(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldContains(FieldDomainID, v))
}

// DomainIDHasPrefix applies the HasPrefix predicate on the "domain_id" field.
func DomainIDHasPrefix(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldHasPrefix(FieldDomainID, v))
}

// DomainIDHasSuffix applies the HasSuffix predicate on the "domain_id" field.
func DomainIDHasSuffix(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldHasSuffix(FieldDomainID, v))
}

// DomainIDEqualFold applies the EqualFold predicate on the "domain_id" field.
func DomainIDEqualFold(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldEqualFold(FieldDomainID, v))
}

// DomainIDContainsFold applies the ContainsFold predicate on the "domain_id" field.
func DomainIDContainsFold(v string) predicate.RouteHostname {
	return predicate.RouteHostname(sql.FieldContainsFold(FieldDomainID, v))
}

// HasRoute applies the HasEdge predicate on the "route" edge.
func HasRoute() predicate.RouteHostname {
	return predicate.RouteHostname(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RouteTable, RouteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRouteWith applies the HasEdge predicate on the "route" edge with a given conditions (other predicates).
func HasRouteWith(preds ...predicate.Route) predicate.RouteHostname {
	return predicate.RouteHostname(func(s *sql.Selector) {
		step := newRouteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDomain applies the HasEdge predicate on the "domain" edge.
func HasDomain() predicate.RouteHostname {
	return predicate.RouteHostname(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, DomainTable, DomainColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDomainWith applies the HasEdge predicate on the "domain" edge with a given conditions (other predicates).
func HasDomainWith(preds ...predicate.Domain) predicate.RouteHostname {
	return predicate.RouteHostname(func(s *sql.Selector) {
		step := newDomainStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RouteHostname) predicate.RouteHostname {
	return predicate.RouteHostname(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RouteHostname) predicate.RouteHostname {
	return predicate.RouteHostname(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RouteHostname) predicate.RouteHostname {
	return predicate.RouteHostname(sql.NotPredicates(p))
}
