// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"
	"time"

	"github.com/felix-homelab/rpmgr/internal/store/ent/agentsession"
	"github.com/felix-homelab/rpmgr/internal/store/ent/agentstate"
	"github.com/felix-homelab/rpmgr/internal/store/ent/auditentry"
	"github.com/felix-homelab/rpmgr/internal/store/ent/audithead"
	"github.com/felix-homelab/rpmgr/internal/store/ent/cakey"
	"github.com/felix-homelab/rpmgr/internal/store/ent/compiledsnapshot"
	"github.com/felix-homelab/rpmgr/internal/store/ent/configrevision"
	"github.com/felix-homelab/rpmgr/internal/store/ent/configseq"
	"github.com/felix-homelab/rpmgr/internal/store/ent/connector"
	"github.com/felix-homelab/rpmgr/internal/store/ent/enrollmenttoken"
	"github.com/felix-homelab/rpmgr/internal/store/ent/gateway"
	"github.com/felix-homelab/rpmgr/internal/store/ent/gatewaygroup"
	"github.com/felix-homelab/rpmgr/internal/store/ent/instance"
	"github.com/felix-homelab/rpmgr/internal/store/ent/instancesetting"
	"github.com/felix-homelab/rpmgr/internal/store/ent/issuedcertificate"
	"github.com/felix-homelab/rpmgr/internal/store/ent/lease"
	"github.com/felix-homelab/rpmgr/internal/store/ent/org"
	"github.com/felix-homelab/rpmgr/internal/store/ent/orgsetting"
	"github.com/felix-homelab/rpmgr/internal/store/ent/revokedidentity"
	"github.com/felix-homelab/rpmgr/internal/store/ent/schema"
	"github.com/felix-homelab/rpmgr/internal/store/ent/secretmeta"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentsessionMixin := schema.AgentSession{}.Mixin()
	agentsession.Policy = privacy.NewPolicies(agentsessionMixin[0], schema.AgentSession{})
	agentsession.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := agentsession.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	agentsessionMixinHooks0 := agentsessionMixin[0].Hooks()

	agentsession.Hooks[1] = agentsessionMixinHooks0[0]
	agentsessionMixinInters0 := agentsessionMixin[0].Interceptors()
	agentsession.Interceptors[0] = agentsessionMixinInters0[0]
	agentsessionMixinFields0 := agentsessionMixin[0].Fields()
	_ = agentsessionMixinFields0
	agentsessionFields := schema.AgentSession{}.Fields()
	_ = agentsessionFields
	// agentsessionDescOrgID is the schema descriptor for org_id field.
	agentsessionDescOrgID := agentsessionMixinFields0[0].Descriptor()
	// agentsession.OrgIDValidator is a validator for the "org_id" field. It is called by the builders before save.
	agentsession.OrgIDValidator = agentsessionDescOrgID.Validators[0].(func(string) error)
	// agentsessionDescSessionEpoch is the schema descriptor for session_epoch field.
	agentsessionDescSessionEpoch := agentsessionFields[1].Descriptor()
	// agentsession.SessionEpochValidator is a validator for the "session_epoch" field. It is called by the builders before save.
	agentsession.SessionEpochValidator = agentsessionDescSessionEpoch.Validators[0].(func(int64) error)
	// agentsessionDescControllerNode is the schema descriptor for controller_node field.
	agentsessionDescControllerNode := agentsessionFields[2].Descriptor()
	// agentsession.ControllerNodeValidator is a validator for the "controller_node" field. It is called by the builders before save.
	agentsession.ControllerNodeValidator = agentsessionDescControllerNode.Validators[0].(func(string) error)
	// agentsessionDescRemoteAddr is the schema descriptor for remote_addr field.
	agentsessionDescRemoteAddr := agentsessionFields[3].Descriptor()
	// agentsession.DefaultRemoteAddr holds the default value on creation for the remote_addr field.
	agentsession.DefaultRemoteAddr = agentsessionDescRemoteAddr.Default.(string)
	// agentsessionDescAgentVersion is the schema descriptor for agent_version field.
	agentsessionDescAgentVersion := agentsessionFields[4].Descriptor()
	// agentsession.DefaultAgentVersion holds the default value on creation for the agent_version field.
	agentsession.DefaultAgentVersion = agentsessionDescAgentVersion.Default.(string)
	// agentsessionDescConnectedAt is the schema descriptor for connected_at field.
	agentsessionDescConnectedAt := agentsessionFields[6].Descriptor()
	// agentsession.DefaultConnectedAt holds the default value on creation for the connected_at field.
	agentsession.DefaultConnectedAt = agentsessionDescConnectedAt.Default.(func() time.Time)
	// agentsessionDescLastSeenAt is the schema descriptor for last_seen_at field.
	agentsessionDescLastSeenAt := agentsessionFields[7].Descriptor()
	// agentsession.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	agentsession.DefaultLastSeenAt = agentsessionDescLastSeenAt.Default.(func() time.Time)
	// agentsessionDescID is the schema descriptor for id field.
	agentsessionDescID := agentsessionFields[0].Descriptor()
	// agentsession.IDValidator is a validator for the "id" field. It is called by the builders before save.
	agentsession.IDValidator = agentsessionDescID.Validators[0].(func(string) error)
	agentstateMixin := schema.AgentState{}.Mixin()
	agentstate.Policy = privacy.NewPolicies(agentstateMixin[0], schema.AgentState{})
	agentstate.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := agentstate.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	agentstateMixinHooks0 := agentstateMixin[0].Hooks()

	agentstate.Hooks[1] = agentstateMixinHooks0[0]
	agentstateMixinInters0 := agentstateMixin[0].Interceptors()
	agentstate.Interceptors[0] = agentstateMixinInters0[0]
	agentstateMixinFields0 := agentstateMixin[0].Fields()
	_ = agentstateMixinFields0
	agentstateFields := schema.AgentState{}.Fields()
	_ = agentstateFields
	// agentstateDescOrgID is the schema descriptor for org_id field.
	agentstateDescOrgID := agentstateMixinFields0[0].Descriptor()
	// agentstate.OrgIDValidator is a validator for the "org_id" field. It is called by the builders before save.
	agentstate.OrgIDValidator = agentstateDescOrgID.Validators[0].(func(string) error)
	// agentstateDescBootID is the schema descriptor for boot_id field.
	agentstateDescBootID := agentstateFields[1].Descriptor()
	// agentstate.DefaultBootID holds the default value on creation for the boot_id field.
	agentstate.DefaultBootID = agentstateDescBootID.Default.(string)
	// agentstateDescClockOffsetMs is the schema descriptor for clock_offset_ms field.
	agentstateDescClockOffsetMs := agentstateFields[2].Descriptor()
	// agentstate.DefaultClockOffsetMs holds the default value on creation for the clock_offset_ms field.
	agentstate.DefaultClockOffsetMs = agentstateDescClockOffsetMs.Default.(int64)
	// agentstateDescAppliedDbEpoch is the schema descriptor for applied_db_epoch field.
	agentstateDescAppliedDbEpoch := agentstateFields[3].Descriptor()
	// agentstate.DefaultAppliedDbEpoch holds the default value on creation for the applied_db_epoch field.
	agentstate.DefaultAppliedDbEpoch = agentstateDescAppliedDbEpoch.Default.(string)
	// agentstateDescAppliedSeq is the schema descriptor for applied_seq field.
	agentstateDescAppliedSeq := agentstateFields[4].Descriptor()
	// agentstate.DefaultAppliedSeq holds the default value on creation for the applied_seq field.
	agentstate.DefaultAppliedSeq = agentstateDescAppliedSeq.Default.(int64)
	// agentstate.AppliedSeqValidator is a validator for the "applied_seq" field. It is called by the builders before save.
	agentstate.AppliedSeqValidator = agentstateDescAppliedSeq.Validators[0].(func(int64) error)
	// agentstateDescPushedDbEpoch is the schema descriptor for pushed_db_epoch field.
	agentstateDescPushedDbEpoch := agentstateFields[7].Descriptor()
	// agentstate.DefaultPushedDbEpoch holds the default value on creation for the pushed_db_epoch field.
	agentstate.DefaultPushedDbEpoch = agentstateDescPushedDbEpoch.Default.(string)
	// agentstateDescPushedSeq is the schema descriptor for pushed_seq field.
	agentstateDescPushedSeq := agentstateFields[8].Descriptor()
	// agentstate.DefaultPushedSeq holds the default value on creation for the pushed_seq field.
	agentstate.DefaultPushedSeq = agentstateDescPushedSeq.Default.(int64)
	// agentstate.PushedSeqValidator is a validator for the "pushed_seq" field. It is called by the builders before save.
	agentstate.PushedSeqValidator = agentstateDescPushedSeq.Validators[0].(func(int64) error)
	// agentstateDescRejectedDbEpoch is the schema descriptor for rejected_db_epoch field.
	agentstateDescRejectedDbEpoch := agentstateFields[11].Descriptor()
	// agentstate.DefaultRejectedDbEpoch holds the default value on creation for the rejected_db_epoch field.
	agentstate.DefaultRejectedDbEpoch = agentstateDescRejectedDbEpoch.Default.(string)
	// agentstateDescRejectedSeq is the schema descriptor for rejected_seq field.
	agentstateDescRejectedSeq := agentstateFields[12].Descriptor()
	// agentstate.DefaultRejectedSeq holds the default value on creation for the rejected_seq field.
	agentstate.DefaultRejectedSeq = agentstateDescRejectedSeq.Default.(int64)
	// agentstate.RejectedSeqValidator is a validator for the "rejected_seq" field. It is called by the builders before save.
	agentstate.RejectedSeqValidator = agentstateDescRejectedSeq.Validators[0].(func(int64) error)
	// agentstateDescID is the schema descriptor for id field.
	agentstateDescID := agentstateFields[0].Descriptor()
	// agentstate.IDValidator is a validator for the "id" field. It is called by the builders before save.
	agentstate.IDValidator = agentstateDescID.Validators[0].(func(string) error)
	auditentry.Policy = privacy.NewPolicies(schema.AuditEntry{})
	auditentry.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := auditentry.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	auditentryHooks := schema.AuditEntry{}.Hooks()

	auditentry.Hooks[1] = auditentryHooks[0]
	auditentryInters := schema.AuditEntry{}.Interceptors()
	auditentry.Interceptors[0] = auditentryInters[0]
	auditentryFields := schema.AuditEntry{}.Fields()
	_ = auditentryFields
	// auditentryDescSeq is the schema descriptor for seq field.
	auditentryDescSeq := auditentryFields[2].Descriptor()
	// auditentry.SeqValidator is a validator for the "seq" field. It is called by the builders before save.
	auditentry.SeqValidator = auditentryDescSeq.Validators[0].(func(int64) error)
	// auditentryDescActorID is the schema descriptor for actor_id field.
	auditentryDescActorID := auditentryFields[7].Descriptor()
	// auditentry.DefaultActorID holds the default value on creation for the actor_id field.
	auditentry.DefaultActorID = auditentryDescActorID.Default.(string)
	// auditentryDescCredentialID is the schema descriptor for credential_id field.
	auditentryDescCredentialID := auditentryFields[8].Descriptor()
	// auditentry.DefaultCredentialID holds the default value on creation for the credential_id field.
	auditentry.DefaultCredentialID = auditentryDescCredentialID.Default.(string)
	// auditentryDescAuthMethod is the schema descriptor for auth_method field.
	auditentryDescAuthMethod := auditentryFields[9].Descriptor()
	// auditentry.DefaultAuthMethod holds the default value on creation for the auth_method field.
	auditentry.DefaultAuthMethod = auditentryDescAuthMethod.Default.(string)
	// auditentryDescIP is the schema descriptor for ip field.
	auditentryDescIP := auditentryFields[10].Descriptor()
	// auditentry.DefaultIP holds the default value on creation for the ip field.
	auditentry.DefaultIP = auditentryDescIP.Default.(string)
	// auditentryDescUserAgent is the schema descriptor for user_agent field.
	auditentryDescUserAgent := auditentryFields[11].Descriptor()
	// auditentry.DefaultUserAgent holds the default value on creation for the user_agent field.
	auditentry.DefaultUserAgent = auditentryDescUserAgent.Default.(string)
	// auditentryDescRequestID is the schema descriptor for request_id field.
	auditentryDescRequestID := auditentryFields[12].Descriptor()
	// auditentry.DefaultRequestID holds the default value on creation for the request_id field.
	auditentry.DefaultRequestID = auditentryDescRequestID.Default.(string)
	// auditentryDescAction is the schema descriptor for action field.
	auditentryDescAction := auditentryFields[13].Descriptor()
	// auditentry.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditentry.ActionValidator = auditentryDescAction.Validators[0].(func(string) error)
	// auditentryDescTargetType is the schema descriptor for target_type field.
	auditentryDescTargetType := auditentryFields[14].Descriptor()
	// auditentry.DefaultTargetType holds the default value on creation for the target_type field.
	auditentry.DefaultTargetType = auditentryDescTargetType.Default.(string)
	// auditentryDescTargetID is the schema descriptor for target_id field.
	auditentryDescTargetID := auditentryFields[15].Descriptor()
	// auditentry.DefaultTargetID holds the default value on creation for the target_id field.
	auditentry.DefaultTargetID = auditentryDescTargetID.Default.(string)
	// auditentryDescDiff is the schema descriptor for diff field.
	auditentryDescDiff := auditentryFields[17].Descriptor()
	// auditentry.DefaultDiff holds the default value on creation for the diff field.
	auditentry.DefaultDiff = auditentryDescDiff.Default.(string)
	// auditentryDescReason is the schema descriptor for reason field.
	auditentryDescReason := auditentryFields[18].Descriptor()
	// auditentry.DefaultReason holds the default value on creation for the reason field.
	auditentry.DefaultReason = auditentryDescReason.Default.(string)
	// auditentryDescID is the schema descriptor for id field.
	auditentryDescID := auditentryFields[0].Descriptor()
	// auditentry.DefaultID holds the default value on creation for the id field.
	auditentry.DefaultID = auditentryDescID.Default.(func() string)
	// auditentry.IDValidator is a validator for the "id" field. It is called by the builders before save.
	auditentry.IDValidator = func() func(string) error {
		validators := auditentryDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	audithead.Policy = privacy.NewPolicies(schema.AuditHead{})
	audithead.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := audithead.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	auditheadHooks := schema.AuditHead{}.Hooks()

	audithead.Hooks[1] = auditheadHooks[0]
	auditheadInters := schema.AuditHead{}.Interceptors()
	audithead.Interceptors[0] = auditheadInters[0]
	auditheadFields := schema.AuditHead{}.Fields()
	_ = auditheadFields
	// auditheadDescSeq is the schema descriptor for seq field.
	auditheadDescSeq := auditheadFields[1].Descriptor()
	// audithead.SeqValidator is a validator for the "seq" field. It is called by the builders before save.
	audithead.SeqValidator = auditheadDescSeq.Validators[0].(func(int64) error)
	// auditheadDescID is the schema descriptor for id field.
	auditheadDescID := auditheadFields[0].Descriptor()
	// audithead.IDValidator is a validator for the "id" field. It is called by the builders before save.
	audithead.IDValidator = auditheadDescID.Validators[0].(func(string) error)
	cakeyMixin := schema.CAKey{}.Mixin()
	cakey.Policy = privacy.NewPolicies(cakeyMixin[0], schema.CAKey{})
	cakey.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := cakey.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	cakeyMixinHooks0 := cakeyMixin[0].Hooks()

	cakey.Hooks[1] = cakeyMixinHooks0[0]
	cakeyMixinInters0 := cakeyMixin[0].Interceptors()
	cakey.Interceptors[0] = cakeyMixinInters0[0]
	cakeyFields := schema.CAKey{}.Fields()
	_ = cakeyFields
	// cakeyDescAlgorithm is the schema descriptor for algorithm field.
	cakeyDescAlgorithm := cakeyFields[2].Descriptor()
	// cakey.AlgorithmValidator is a validator for the "algorithm" field. It is called by the builders before save.
	cakey.AlgorithmValidator = cakeyDescAlgorithm.Validators[0].(func(string) error)
	// cakeyDescPublicKey is the schema descriptor for public_key field.
	cakeyDescPublicKey := cakeyFields[3].Descriptor()
	// cakey.PublicKeyValidator is a validator for the "public_key" field. It is called by the builders before save.
	cakey.PublicKeyValidator = cakeyDescPublicKey.Validators[0].(func([]byte) error)
	// cakeyDescCertificate is the schema descriptor for certificate field.
	cakeyDescCertificate := cakeyFields[4].Descriptor()
	// cakey.CertificateValidator is a validator for the "certificate" field. It is called by the builders before save.
	cakey.CertificateValidator = cakeyDescCertificate.Validators[0].(func([]byte) error)
	// cakeyDescID is the schema descriptor for id field.
	cakeyDescID := cakeyFields[0].Descriptor()
	// cakey.DefaultID holds the default value on creation for the id field.
	cakey.DefaultID = cakeyDescID.Default.(func() string)
	// cakey.IDValidator is a validator for the "id" field. It is called by the builders before save.
	cakey.IDValidator = func() func(string) error {
		validators := cakeyDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	compiledsnapshotMixin := schema.CompiledSnapshot{}.Mixin()
	compiledsnapshot.Policy = privacy.NewPolicies(compiledsnapshotMixin[0], schema.CompiledSnapshot{})
	compiledsnapshot.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := compiledsnapshot.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	compiledsnapshotMixinHooks0 := compiledsnapshotMixin[0].Hooks()

	compiledsnapshot.Hooks[1] = compiledsnapshotMixinHooks0[0]
	compiledsnapshotMixinInters0 := compiledsnapshotMixin[0].Interceptors()
	compiledsnapshot.Interceptors[0] = compiledsnapshotMixinInters0[0]
	compiledsnapshotMixinFields0 := compiledsnapshotMixin[0].Fields()
	_ = compiledsnapshotMixinFields0
	compiledsnapshotFields := schema.CompiledSnapshot{}.Fields()
	_ = compiledsnapshotFields
	// compiledsnapshotDescOrgID is the schema descriptor for org_id field.
	compiledsnapshotDescOrgID := compiledsnapshotMixinFields0[0].Descriptor()
	// compiledsnapshot.OrgIDValidator is a validator for the "org_id" field. It is called by the builders before save.
	compiledsnapshot.OrgIDValidator = compiledsnapshotDescOrgID.Validators[0].(func(string) error)
	// compiledsnapshotDescAgentID is the schema descriptor for agent_id field.
	compiledsnapshotDescAgentID := compiledsnapshotFields[0].Descriptor()
	// compiledsnapshot.AgentIDValidator is a validator for the "agent_id" field. It is called by the builders before save.
	compiledsnapshot.AgentIDValidator = compiledsnapshotDescAgentID.Validators[0].(func(string) error)
	// compiledsnapshotDescDbEpoch is the schema descriptor for db_epoch field.
	compiledsnapshotDescDbEpoch := compiledsnapshotFields[1].Descriptor()
	// compiledsnapshot.DbEpochValidator is a validator for the "db_epoch" field. It is called by the builders before save.
	compiledsnapshot.DbEpochValidator = compiledsnapshotDescDbEpoch.Validators[0].(func(string) error)
	// compiledsnapshotDescSeq is the schema descriptor for seq field.
	compiledsnapshotDescSeq := compiledsnapshotFields[2].Descriptor()
	// compiledsnapshot.SeqValidator is a validator for the "seq" field. It is called by the builders before save.
	compiledsnapshot.SeqValidator = compiledsnapshotDescSeq.Validators[0].(func(int64) error)
	// compiledsnapshotDescHash is the schema descriptor for hash field.
	compiledsnapshotDescHash := compiledsnapshotFields[3].Descriptor()
	// compiledsnapshot.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	compiledsnapshot.HashValidator = compiledsnapshotDescHash.Validators[0].(func([]byte) error)
	// compiledsnapshotDescSizeBytes is the schema descriptor for size_bytes field.
	compiledsnapshotDescSizeBytes := compiledsnapshotFields[4].Descriptor()
	// compiledsnapshot.SizeBytesValidator is a validator for the "size_bytes" field. It is called by the builders before save.
	compiledsnapshot.SizeBytesValidator = compiledsnapshotDescSizeBytes.Validators[0].(func(int) error)
	// compiledsnapshotDescSignature is the schema descriptor for signature field.
	compiledsnapshotDescSignature := compiledsnapshotFields[6].Descriptor()
	// compiledsnapshot.SignatureValidator is a validator for the "signature" field. It is called by the builders before save.
	compiledsnapshot.SignatureValidator = compiledsnapshotDescSignature.Validators[0].(func([]byte) error)
	// compiledsnapshotDescKeyID is the schema descriptor for key_id field.
	compiledsnapshotDescKeyID := compiledsnapshotFields[7].Descriptor()
	// compiledsnapshot.KeyIDValidator is a validator for the "key_id" field. It is called by the builders before save.
	compiledsnapshot.KeyIDValidator = compiledsnapshotDescKeyID.Validators[0].(func(string) error)
	// compiledsnapshotDescCreatedAt is the schema descriptor for created_at field.
	compiledsnapshotDescCreatedAt := compiledsnapshotFields[8].Descriptor()
	// compiledsnapshot.DefaultCreatedAt holds the default value on creation for the created_at field.
	compiledsnapshot.DefaultCreatedAt = compiledsnapshotDescCreatedAt.Default.(func() time.Time)
	configrevisionMixin := schema.ConfigRevision{}.Mixin()
	configrevision.Policy = privacy.NewPolicies(configrevisionMixin[0], schema.ConfigRevision{})
	configrevision.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := configrevision.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	configrevisionFields := schema.ConfigRevision{}.Fields()
	_ = configrevisionFields
	// configrevisionDescDbEpoch is the schema descriptor for db_epoch field.
	configrevisionDescDbEpoch := configrevisionFields[1].Descriptor()
	// configrevision.DbEpochValidator is a validator for the "db_epoch" field. It is called by the builders before save.
	configrevision.DbEpochValidator = configrevisionDescDbEpoch.Validators[0].(func(string) error)
	// configrevisionDescActor is the schema descriptor for actor field.
	configrevisionDescActor := configrevisionFields[2].Descriptor()
	// configrevision.ActorValidator is a validator for the "actor" field. It is called by the builders before save.
	configrevision.ActorValidator = configrevisionDescActor.Validators[0].(func(string) error)
	// configrevisionDescCreatedAt is the schema descriptor for created_at field.
	configrevisionDescCreatedAt := configrevisionFields[4].Descriptor()
	// configrevision.DefaultCreatedAt holds the default value on creation for the created_at field.
	configrevision.DefaultCreatedAt = configrevisionDescCreatedAt.Default.(func() time.Time)
	// configrevisionDescID is the schema descriptor for id field.
	configrevisionDescID := configrevisionFields[0].Descriptor()
	// configrevision.IDValidator is a validator for the "id" field. It is called by the builders before save.
	configrevision.IDValidator = configrevisionDescID.Validators[0].(func(int64) error)
	configseqMixin := schema.ConfigSeq{}.Mixin()
	configseq.Policy = privacy.NewPolicies(configseqMixin[0], schema.ConfigSeq{})
	configseq.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := configseq.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	configseqFields := schema.ConfigSeq{}.Fields()
	_ = configseqFields
	// configseqDescSeq is the schema descriptor for seq field.
	configseqDescSeq := configseqFields[1].Descriptor()
	// configseq.SeqValidator is a validator for the "seq" field. It is called by the builders before save.
	configseq.SeqValidator = configseqDescSeq.Validators[0].(func(int64) error)
	// configseqDescID is the schema descriptor for id field.
	configseqDescID := configseqFields[0].Descriptor()
	// configseq.IDValidator is a validator for the "id" field. It is called by the builders before save.
	configseq.IDValidator = configseqDescID.Validators[0].(func(int) error)
	connectorMixin := schema.Connector{}.Mixin()
	connector.Policy = privacy.NewPolicies(connectorMixin[0], schema.Connector{})
	connector.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := connector.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	connectorMixinHooks0 := connectorMixin[0].Hooks()

	connector.Hooks[1] = connectorMixinHooks0[0]
	connectorMixinInters0 := connectorMixin[0].Interceptors()
	connector.Interceptors[0] = connectorMixinInters0[0]
	connectorMixinFields0 := connectorMixin[0].Fields()
	_ = connectorMixinFields0
	connectorFields := schema.Connector{}.Fields()
	_ = connectorFields
	// connectorDescOrgID is the schema descriptor for org_id field.
	connectorDescOrgID := connectorMixinFields0[0].Descriptor()
	// connector.OrgIDValidator is a validator for the "org_id" field. It is called by the builders before save.
	connector.OrgIDValidator = connectorDescOrgID.Validators[0].(func(string) error)
	// connectorDescName is the schema descriptor for name field.
	connectorDescName := connectorFields[1].Descriptor()
	// connector.NameValidator is a validator for the "name" field. It is called by the builders before save.
	connector.NameValidator = func() func(string) error {
		validators := connectorDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// connectorDescSpiffeID is the schema descriptor for spiffe_id field.
	connectorDescSpiffeID := connectorFields[3].Descriptor()
	// connector.SpiffeIDValidator is a validator for the "spiffe_id" field. It is called by the builders before save.
	connector.SpiffeIDValidator = connectorDescSpiffeID.Validators[0].(func(string) error)
	// connectorDescPubkeySha256 is the schema descriptor for pubkey_sha256 field.
	connectorDescPubkeySha256 := connectorFields[4].Descriptor()
	// connector.PubkeySha256Validator is a validator for the "pubkey_sha256" field. It is called by the builders before save.
	connector.PubkeySha256Validator = connectorDescPubkeySha256.Validators[0].(func(string) error)
	// connectorDescEphemeral is the schema descriptor for ephemeral field.
	connectorDescEphemeral := connectorFields[5].Descriptor()
	// connector.DefaultEphemeral holds the default value on creation for the ephemeral field.
	connector.DefaultEphemeral = connectorDescEphemeral.Default.(bool)
	// connectorDescEnabled is the schema descriptor for enabled field.
	connectorDescEnabled := connectorFields[6].Descriptor()
	// connector.DefaultEnabled holds the default value on creation for the enabled field.
	connector.DefaultEnabled = connectorDescEnabled.Default.(bool)
	// connectorDescCreatedAt is the schema descriptor for created_at field.
	connectorDescCreatedAt := connectorFields[9].Descriptor()
	// connector.DefaultCreatedAt holds the default value on creation for the created_at field.
	connector.DefaultCreatedAt = connectorDescCreatedAt.Default.(func() time.Time)
	// connectorDescID is the schema descriptor for id field.
	connectorDescID := connectorFields[0].Descriptor()
	// connector.DefaultID holds the default value on creation for the id field.
	connector.DefaultID = connectorDescID.Default.(func() string)
	// connector.IDValidator is a validator for the "id" field. It is called by the builders before save.
	connector.IDValidator = func() func(string) error {
		validators := connectorDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	enrollmenttokenMixin := schema.EnrollmentToken{}.Mixin()
	enrollmenttoken.Policy = privacy.NewPolicies(enrollmenttokenMixin[0], schema.EnrollmentToken{})
	enrollmenttoken.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := enrollmenttoken.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	enrollmenttokenMixinHooks0 := enrollmenttokenMixin[0].Hooks()
	enrollmenttokenHooks := schema.EnrollmentToken{}.Hooks()

	enrollmenttoken.Hooks[1] = enrollmenttokenMixinHooks0[0]

	enrollmenttoken.Hooks[2] = enrollmenttokenHooks[0]
	enrollmenttokenMixinInters0 := enrollmenttokenMixin[0].Interceptors()
	enrollmenttoken.Interceptors[0] = enrollmenttokenMixinInters0[0]
	enrollmenttokenMixinFields0 := enrollmenttokenMixin[0].Fields()
	_ = enrollmenttokenMixinFields0
	enrollmenttokenFields := schema.EnrollmentToken{}.Fields()
	_ = enrollmenttokenFields
	// enrollmenttokenDescOrgID is the schema descriptor for org_id field.
	enrollmenttokenDescOrgID := enrollmenttokenMixinFields0[0].Descriptor()
	// enrollmenttoken.OrgIDValidator is a validator for the "org_id" field. It is called by the builders before save.
	enrollmenttoken.OrgIDValidator = enrollmenttokenDescOrgID.Validators[0].(func(string) error)
	// enrollmenttokenDescTokenHash is the schema descriptor for token_hash field.
	enrollmenttokenDescTokenHash := enrollmenttokenFields[1].Descriptor()
	// enrollmenttoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	enrollmenttoken.TokenHashValidator = enrollmenttokenDescTokenHash.Validators[0].(func([]byte) error)
	// enrollmenttokenDescEphemeral is the schema descriptor for ephemeral field.
	enrollmenttokenDescEphemeral := enrollmenttokenFields[7].Descriptor()
	// enrollmenttoken.DefaultEphemeral holds the default value on creation for the ephemeral field.
	enrollmenttoken.DefaultEphemeral = enrollmenttokenDescEphemeral.Default.(bool)
	// enrollmenttokenDescMaxUses is the schema descriptor for max_uses field.
	enrollmenttokenDescMaxUses := enrollmenttokenFields[8].Descriptor()
	// enrollmenttoken.MaxUsesValidator is a validator for the "max_uses" field. It is called by the builders before save.
	enrollmenttoken.MaxUsesValidator = enrollmenttokenDescMaxUses.Validators[0].(func(int) error)
	// enrollmenttokenDescUseCount is the schema descriptor for use_count field.
	enrollmenttokenDescUseCount := enrollmenttokenFields[9].Descriptor()
	// enrollmenttoken.DefaultUseCount holds the default value on creation for the use_count field.
	enrollmenttoken.DefaultUseCount = enrollmenttokenDescUseCount.Default.(int)
	// enrollmenttoken.UseCountValidator is a validator for the "use_count" field. It is called by the builders before save.
	enrollmenttoken.UseCountValidator = enrollmenttokenDescUseCount.Validators[0].(func(int) error)
	// enrollmenttokenDescCreatedBy is the schema descriptor for created_by field.
	enrollmenttokenDescCreatedBy := enrollmenttokenFields[11].Descriptor()
	// enrollmenttoken.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	enrollmenttoken.CreatedByValidator = enrollmenttokenDescCreatedBy.Validators[0].(func(string) error)
	// enrollmenttokenDescCreatedAt is the schema descriptor for created_at field.
	enrollmenttokenDescCreatedAt := enrollmenttokenFields[12].Descriptor()
	// enrollmenttoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	enrollmenttoken.DefaultCreatedAt = enrollmenttokenDescCreatedAt.Default.(func() time.Time)
	// enrollmenttokenDescID is the schema descriptor for id field.
	enrollmenttokenDescID := enrollmenttokenFields[0].Descriptor()
	// enrollmenttoken.DefaultID holds the default value on creation for the id field.
	enrollmenttoken.DefaultID = enrollmenttokenDescID.Default.(func() string)
	// enrollmenttoken.IDValidator is a validator for the "id" field. It is called by the builders before save.
	enrollmenttoken.IDValidator = func() func(string) error {
		validators := enrollmenttokenDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	gatewayMixin := schema.Gateway{}.Mixin()
	gateway.Policy = privacy.NewPolicies(gatewayMixin[0], schema.Gateway{})
	gateway.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := gateway.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	gatewayMixinHooks0 := gatewayMixin[0].Hooks()
	gatewayHooks := schema.Gateway{}.Hooks()

	gateway.Hooks[1] = gatewayMixinHooks0[0]

	gateway.Hooks[2] = gatewayHooks[0]
	gatewayMixinInters0 := gatewayMixin[0].Interceptors()
	gateway.Interceptors[0] = gatewayMixinInters0[0]
	gatewayMixinFields0 := gatewayMixin[0].Fields()
	_ = gatewayMixinFields0
	gatewayFields := schema.Gateway{}.Fields()
	_ = gatewayFields
	// gatewayDescOrgID is the schema descriptor for org_id field.
	gatewayDescOrgID := gatewayMixinFields0[0].Descriptor()
	// gateway.OrgIDValidator is a validator for the "org_id" field. It is called by the builders before save.
	gateway.OrgIDValidator = gatewayDescOrgID.Validators[0].(func(string) error)
	// gatewayDescGatewayGroupID is the schema descriptor for gateway_group_id field.
	gatewayDescGatewayGroupID := gatewayFields[1].Descriptor()
	// gateway.GatewayGroupIDValidator is a validator for the "gateway_group_id" field. It is called by the builders before save.
	gateway.GatewayGroupIDValidator = gatewayDescGatewayGroupID.Validators[0].(func(string) error)
	// gatewayDescName is the schema descriptor for name field.
	gatewayDescName := gatewayFields[2].Descriptor()
	// gateway.NameValidator is a validator for the "name" field. It is called by the builders before save.
	gateway.NameValidator = func() func(string) error {
		validators := gatewayDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gatewayDescSlot is the schema descriptor for slot field.
	gatewayDescSlot := gatewayFields[3].Descriptor()
	// gateway.SlotValidator is a validator for the "slot" field. It is called by the builders before save.
	gateway.SlotValidator = gatewayDescSlot.Validators[0].(func(int) error)
	// gatewayDescTunnelEndpoints is the schema descriptor for tunnel_endpoints field.
	gatewayDescTunnelEndpoints := gatewayFields[4].Descriptor()
	// gateway.TunnelEndpointsValidator is a validator for the "tunnel_endpoints" field. It is called by the builders before save.
	gateway.TunnelEndpointsValidator = gatewayDescTunnelEndpoints.Validators[0].(func([]string) error)
	// gatewayDescEnabled is the schema descriptor for enabled field.
	gatewayDescEnabled := gatewayFields[7].Descriptor()
	// gateway.DefaultEnabled holds the default value on creation for the enabled field.
	gateway.DefaultEnabled = gatewayDescEnabled.Default.(bool)
	// gatewayDescCreatedAt is the schema descriptor for created_at field.
	gatewayDescCreatedAt := gatewayFields[9].Descriptor()
	// gateway.DefaultCreatedAt holds the default value on creation for the created_at field.
	gateway.DefaultCreatedAt = gatewayDescCreatedAt.Default.(func() time.Time)
	// gatewayDescID is the schema descriptor for id field.
	gatewayDescID := gatewayFields[0].Descriptor()
	// gateway.DefaultID holds the default value on creation for the id field.
	gateway.DefaultID = gatewayDescID.Default.(func() string)
	// gateway.IDValidator is a validator for the "id" field. It is called by the builders before save.
	gateway.IDValidator = func() func(string) error {
		validators := gatewayDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	gatewaygroupMixin := schema.GatewayGroup{}.Mixin()
	gatewaygroup.Policy = privacy.NewPolicies(gatewaygroupMixin[0], schema.GatewayGroup{})
	gatewaygroup.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := gatewaygroup.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	gatewaygroupMixinHooks0 := gatewaygroupMixin[0].Hooks()

	gatewaygroup.Hooks[1] = gatewaygroupMixinHooks0[0]
	gatewaygroupMixinInters0 := gatewaygroupMixin[0].Interceptors()
	gatewaygroup.Interceptors[0] = gatewaygroupMixinInters0[0]
	gatewaygroupMixinFields0 := gatewaygroupMixin[0].Fields()
	_ = gatewaygroupMixinFields0
	gatewaygroupFields := schema.GatewayGroup{}.Fields()
	_ = gatewaygroupFields
	// gatewaygroupDescOrgID is the schema descriptor for org_id field.
	gatewaygroupDescOrgID := gatewaygroupMixinFields0[0].Descriptor()
	// gatewaygroup.OrgIDValidator is a validator for the "org_id" field. It is called by the builders before save.
	gatewaygroup.OrgIDValidator = gatewaygroupDescOrgID.Validators[0].(func(string) error)
	// gatewaygroupDescName is the schema descriptor for name field.
	gatewaygroupDescName := gatewaygroupFields[1].Descriptor()
	// gatewaygroup.NameValidator is a validator for the "name" field. It is called by the builders before save.
	gatewaygroup.NameValidator = func() func(string) error {
		validators := gatewaygroupDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gatewaygroupDescPublicHostnames is the schema descriptor for public_hostnames field.
	gatewaygroupDescPublicHostnames := gatewaygroupFields[3].Descriptor()
	// gatewaygroup.PublicHostnamesValidator is a validator for the "public_hostnames" field. It is called by the builders before save.
	gatewaygroup.PublicHostnamesValidator = gatewaygroupDescPublicHostnames.Validators[0].(func([]string) error)
	// gatewaygroupDescTrustedProxyCidrs is the schema descriptor for trusted_proxy_cidrs field.
	gatewaygroupDescTrustedProxyCidrs := gatewaygroupFields[4].Descriptor()
	// gatewaygroup.TrustedProxyCidrsValidator is a validator for the "trusted_proxy_cidrs" field. It is called by the builders before save.
	gatewaygroup.TrustedProxyCidrsValidator = gatewaygroupDescTrustedProxyCidrs.Validators[0].(func([]string) error)
	// gatewaygroupDescID is the schema descriptor for id field.
	gatewaygroupDescID := gatewaygroupFields[0].Descriptor()
	// gatewaygroup.DefaultID holds the default value on creation for the id field.
	gatewaygroup.DefaultID = gatewaygroupDescID.Default.(func() string)
	// gatewaygroup.IDValidator is a validator for the "id" field. It is called by the builders before save.
	gatewaygroup.IDValidator = func() func(string) error {
		validators := gatewaygroupDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	instanceMixin := schema.Instance{}.Mixin()
	instance.Policy = privacy.NewPolicies(instanceMixin[0], schema.Instance{})
	instance.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := instance.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	instanceFields := schema.Instance{}.Fields()
	_ = instanceFields
	// instanceDescTrustDomain is the schema descriptor for trust_domain field.
	instanceDescTrustDomain := instanceFields[1].Descriptor()
	// instance.TrustDomainValidator is a validator for the "trust_domain" field. It is called by the builders before save.
	instance.TrustDomainValidator = instanceDescTrustDomain.Validators[0].(func(string) error)
	// instanceDescDbEpoch is the schema descriptor for db_epoch field.
	instanceDescDbEpoch := instanceFields[2].Descriptor()
	// instance.DbEpochValidator is a validator for the "db_epoch" field. It is called by the builders before save.
	instance.DbEpochValidator = instanceDescDbEpoch.Validators[0].(func(string) error)
	// instanceDescCreatedAt is the schema descriptor for created_at field.
	instanceDescCreatedAt := instanceFields[3].Descriptor()
	// instance.DefaultCreatedAt holds the default value on creation for the created_at field.
	instance.DefaultCreatedAt = instanceDescCreatedAt.Default.(func() time.Time)
	// instanceDescID is the schema descriptor for id field.
	instanceDescID := instanceFields[0].Descriptor()
	// instance.IDValidator is a validator for the "id" field. It is called by the builders before save.
	instance.IDValidator = instanceDescID.Validators[0].(func(int) error)
	instancesettingMixin := schema.InstanceSetting{}.Mixin()
	instancesetting.Policy = privacy.NewPolicies(instancesettingMixin[0], schema.InstanceSetting{})
	instancesetting.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := instancesetting.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	instancesettingFields := schema.InstanceSetting{}.Fields()
	_ = instancesettingFields
	// instancesettingDescVersion is the schema descriptor for version field.
	instancesettingDescVersion := instancesettingFields[2].Descriptor()
	// instancesetting.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	instancesetting.VersionValidator = instancesettingDescVersion.Validators[0].(func(int64) error)
	// instancesettingDescUpdatedBy is the schema descriptor for updated_by field.
	instancesettingDescUpdatedBy := instancesettingFields[3].Descriptor()
	// instancesetting.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	instancesetting.UpdatedByValidator = instancesettingDescUpdatedBy.Validators[0].(func(string) error)
	// instancesettingDescUpdatedAt is the schema descriptor for updated_at field.
	instancesettingDescUpdatedAt := instancesettingFields[4].Descriptor()
	// instancesetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	instancesetting.DefaultUpdatedAt = instancesettingDescUpdatedAt.Default.(func() time.Time)
	// instancesetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	instancesetting.UpdateDefaultUpdatedAt = instancesettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// instancesettingDescID is the schema descriptor for id field.
	instancesettingDescID := instancesettingFields[0].Descriptor()
	// instancesetting.IDValidator is a validator for the "id" field. It is called by the builders before save.
	instancesetting.IDValidator = instancesettingDescID.Validators[0].(func(int) error)
	issuedcertificate.Policy = privacy.NewPolicies(schema.IssuedCertificate{})
	issuedcertificate.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := issuedcertificate.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	issuedcertificateHooks := schema.IssuedCertificate{}.Hooks()

	issuedcertificate.Hooks[1] = issuedcertificateHooks[0]
	issuedcertificateInters := schema.IssuedCertificate{}.Interceptors()
	issuedcertificate.Interceptors[0] = issuedcertificateInters[0]
	issuedcertificateFields := schema.IssuedCertificate{}.Fields()
	_ = issuedcertificateFields
	// issuedcertificateDescSubjectID is the schema descriptor for subject_id field.
	issuedcertificateDescSubjectID := issuedcertificateFields[3].Descriptor()
	// issuedcertificate.SubjectIDValidator is a validator for the "subject_id" field. It is called by the builders before save.
	issuedcertificate.SubjectIDValidator = issuedcertificateDescSubjectID.Validators[0].(func(string) error)
	// issuedcertificateDescSpiffeID is the schema descriptor for spiffe_id field.
	issuedcertificateDescSpiffeID := issuedcertificateFields[4].Descriptor()
	// issuedcertificate.SpiffeIDValidator is a validator for the "spiffe_id" field. It is called by the builders before save.
	issuedcertificate.SpiffeIDValidator = issuedcertificateDescSpiffeID.Validators[0].(func(string) error)
	// issuedcertificateDescPubkeySha256 is the schema descriptor for pubkey_sha256 field.
	issuedcertificateDescPubkeySha256 := issuedcertificateFields[5].Descriptor()
	// issuedcertificate.PubkeySha256Validator is a validator for the "pubkey_sha256" field. It is called by the builders before save.
	issuedcertificate.PubkeySha256Validator = issuedcertificateDescPubkeySha256.Validators[0].(func(string) error)
	// issuedcertificateDescRevocationReason is the schema descriptor for revocation_reason field.
	issuedcertificateDescRevocationReason := issuedcertificateFields[11].Descriptor()
	// issuedcertificate.DefaultRevocationReason holds the default value on creation for the revocation_reason field.
	issuedcertificate.DefaultRevocationReason = issuedcertificateDescRevocationReason.Default.(string)
	// issuedcertificateDescID is the schema descriptor for id field.
	issuedcertificateDescID := issuedcertificateFields[0].Descriptor()
	// issuedcertificate.IDValidator is a validator for the "id" field. It is called by the builders before save.
	issuedcertificate.IDValidator = issuedcertificateDescID.Validators[0].(func(string) error)
	leaseMixin := schema.Lease{}.Mixin()
	lease.Policy = privacy.NewPolicies(leaseMixin[0], schema.Lease{})
	lease.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := lease.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	leaseMixinHooks0 := leaseMixin[0].Hooks()

	lease.Hooks[1] = leaseMixinHooks0[0]
	leaseMixinInters0 := leaseMixin[0].Interceptors()
	lease.Interceptors[0] = leaseMixinInters0[0]
	leaseFields := schema.Lease{}.Fields()
	_ = leaseFields
	// leaseDescFencingToken is the schema descriptor for fencing_token field.
	leaseDescFencingToken := leaseFields[2].Descriptor()
	// lease.FencingTokenValidator is a validator for the "fencing_token" field. It is called by the builders before save.
	lease.FencingTokenValidator = leaseDescFencingToken.Validators[0].(func(int64) error)
	// leaseDescID is the schema descriptor for id field.
	leaseDescID := leaseFields[0].Descriptor()
	// lease.IDValidator is a validator for the "id" field. It is called by the builders before save.
	lease.IDValidator = leaseDescID.Validators[0].(func(string) error)
	orgMixin := schema.Org{}.Mixin()
	org.Policy = privacy.NewPolicies(orgMixin[0], schema.Org{})
	org.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := org.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	orgMixinHooks0 := orgMixin[0].Hooks()

	org.Hooks[1] = orgMixinHooks0[0]
	orgMixinInters0 := orgMixin[0].Interceptors()
	org.Interceptors[0] = orgMixinInters0[0]
	orgFields := schema.Org{}.Fields()
	_ = orgFields
	// orgDescName is the schema descriptor for name field.
	orgDescName := orgFields[1].Descriptor()
	// org.NameValidator is a validator for the "name" field. It is called by the builders before save.
	org.NameValidator = orgDescName.Validators[0].(func(string) error)
	// orgDescSlug is the schema descriptor for slug field.
	orgDescSlug := orgFields[2].Descriptor()
	// org.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	org.SlugValidator = func() func(string) error {
		validators := orgDescSlug.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(slug string) error {
			for _, fn := range fns {
				if err := fn(slug); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// orgDescCreatedAt is the schema descriptor for created_at field.
	orgDescCreatedAt := orgFields[3].Descriptor()
	// org.DefaultCreatedAt holds the default value on creation for the created_at field.
	org.DefaultCreatedAt = orgDescCreatedAt.Default.(func() time.Time)
	// orgDescID is the schema descriptor for id field.
	orgDescID := orgFields[0].Descriptor()
	// org.DefaultID holds the default value on creation for the id field.
	org.DefaultID = orgDescID.Default.(func() string)
	// org.IDValidator is a validator for the "id" field. It is called by the builders before save.
	org.IDValidator = func() func(string) error {
		validators := orgDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	orgsettingMixin := schema.OrgSetting{}.Mixin()
	orgsetting.Policy = privacy.NewPolicies(orgsettingMixin[0], schema.OrgSetting{})
	orgsetting.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := orgsetting.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	orgsettingMixinHooks0 := orgsettingMixin[0].Hooks()

	orgsetting.Hooks[1] = orgsettingMixinHooks0[0]
	orgsettingMixinInters0 := orgsettingMixin[0].Interceptors()
	orgsetting.Interceptors[0] = orgsettingMixinInters0[0]
	orgsettingMixinFields0 := orgsettingMixin[0].Fields()
	_ = orgsettingMixinFields0
	orgsettingFields := schema.OrgSetting{}.Fields()
	_ = orgsettingFields
	// orgsettingDescOrgID is the schema descriptor for org_id field.
	orgsettingDescOrgID := orgsettingMixinFields0[0].Descriptor()
	// orgsetting.OrgIDValidator is a validator for the "org_id" field. It is called by the builders before save.
	orgsetting.OrgIDValidator = orgsettingDescOrgID.Validators[0].(func(string) error)
	// orgsettingDescVersion is the schema descriptor for version field.
	orgsettingDescVersion := orgsettingFields[2].Descriptor()
	// orgsetting.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	orgsetting.VersionValidator = orgsettingDescVersion.Validators[0].(func(int64) error)
	// orgsettingDescUpdatedBy is the schema descriptor for updated_by field.
	orgsettingDescUpdatedBy := orgsettingFields[3].Descriptor()
	// orgsetting.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	orgsetting.UpdatedByValidator = orgsettingDescUpdatedBy.Validators[0].(func(string) error)
	// orgsettingDescUpdatedAt is the schema descriptor for updated_at field.
	orgsettingDescUpdatedAt := orgsettingFields[4].Descriptor()
	// orgsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	orgsetting.DefaultUpdatedAt = orgsettingDescUpdatedAt.Default.(func() time.Time)
	// orgsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	orgsetting.UpdateDefaultUpdatedAt = orgsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orgsettingDescID is the schema descriptor for id field.
	orgsettingDescID := orgsettingFields[0].Descriptor()
	// orgsetting.DefaultID holds the default value on creation for the id field.
	orgsetting.DefaultID = orgsettingDescID.Default.(func() string)
	// orgsetting.IDValidator is a validator for the "id" field. It is called by the builders before save.
	orgsetting.IDValidator = func() func(string) error {
		validators := orgsettingDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	revokedidentity.Policy = privacy.NewPolicies(schema.RevokedIdentity{})
	revokedidentity.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := revokedidentity.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	revokedidentityHooks := schema.RevokedIdentity{}.Hooks()

	revokedidentity.Hooks[1] = revokedidentityHooks[0]
	revokedidentityInters := schema.RevokedIdentity{}.Interceptors()
	revokedidentity.Interceptors[0] = revokedidentityInters[0]
	revokedidentityFields := schema.RevokedIdentity{}.Fields()
	_ = revokedidentityFields
	// revokedidentityDescSubjectID is the schema descriptor for subject_id field.
	revokedidentityDescSubjectID := revokedidentityFields[3].Descriptor()
	// revokedidentity.SubjectIDValidator is a validator for the "subject_id" field. It is called by the builders before save.
	revokedidentity.SubjectIDValidator = revokedidentityDescSubjectID.Validators[0].(func(string) error)
	// revokedidentityDescReason is the schema descriptor for reason field.
	revokedidentityDescReason := revokedidentityFields[5].Descriptor()
	// revokedidentity.DefaultReason holds the default value on creation for the reason field.
	revokedidentity.DefaultReason = revokedidentityDescReason.Default.(string)
	// revokedidentityDescID is the schema descriptor for id field.
	revokedidentityDescID := revokedidentityFields[0].Descriptor()
	// revokedidentity.IDValidator is a validator for the "id" field. It is called by the builders before save.
	revokedidentity.IDValidator = revokedidentityDescID.Validators[0].(func(string) error)
	secretmetaMixin := schema.SecretMeta{}.Mixin()
	secretmeta.Policy = privacy.NewPolicies(secretmetaMixin[0], schema.SecretMeta{})
	secretmeta.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := secretmeta.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	secretmetaFields := schema.SecretMeta{}.Fields()
	_ = secretmetaFields
	// secretmetaDescTableName is the schema descriptor for table_name field.
	secretmetaDescTableName := secretmetaFields[0].Descriptor()
	// secretmeta.TableNameValidator is a validator for the "table_name" field. It is called by the builders before save.
	secretmeta.TableNameValidator = secretmetaDescTableName.Validators[0].(func(string) error)
	// secretmetaDescRowID is the schema descriptor for row_id field.
	secretmetaDescRowID := secretmetaFields[1].Descriptor()
	// secretmeta.RowIDValidator is a validator for the "row_id" field. It is called by the builders before save.
	secretmeta.RowIDValidator = secretmetaDescRowID.Validators[0].(func(string) error)
	// secretmetaDescColumnName is the schema descriptor for column_name field.
	secretmetaDescColumnName := secretmetaFields[2].Descriptor()
	// secretmeta.ColumnNameValidator is a validator for the "column_name" field. It is called by the builders before save.
	secretmeta.ColumnNameValidator = secretmetaDescColumnName.Validators[0].(func(string) error)
	// secretmetaDescKekVersion is the schema descriptor for kek_version field.
	secretmetaDescKekVersion := secretmetaFields[3].Descriptor()
	// secretmeta.KekVersionValidator is a validator for the "kek_version" field. It is called by the builders before save.
	secretmeta.KekVersionValidator = secretmetaDescKekVersion.Validators[0].(func(string) error)
	// secretmetaDescCreatedAt is the schema descriptor for created_at field.
	secretmetaDescCreatedAt := secretmetaFields[4].Descriptor()
	// secretmeta.DefaultCreatedAt holds the default value on creation for the created_at field.
	secretmeta.DefaultCreatedAt = secretmetaDescCreatedAt.Default.(func() time.Time)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
